### ISSUE TITLE
Échec du chargement du pack d'histoires. (Failed to load story pack.) Cannot read property 'link' of undefined 

### ISSUE THREAD

**Issue by exmackina** [marian-m12l/studio#100]
**Describe the bug**
J'ai récemment perdu les données de mon SSD et donc ma bibliothèque locale d'histoires faites maison (suite à un défaut du Transcend 480 Go JetDrive :S ). Pour pouvoir modifier mes histoires, je les ai récupérées de ma Lunii, converties avec STUdio, puis ouvertes dans l'éditeur. Sur 3 histoires, 2 se sont ouvertes sans problème, en revanche, 1 histoire n'a pas pu s'ouvrir et a généré le message d'erreur (toast) suivant : Échec du chargement du pack d'histoires.

**Logs**
Dans la console d'erreur javascript j'ai obtenu :
index.js:276 failed to load story pack TypeError: Cannot read property 'link' of undefined
    at reader.js:262
    at Array.forEach (<anonymous>)
    at reader.js:256

**To Reproduce**
Après analyse, il semble qu'une cause directe du problème soit une incohérence dans story.json dans l'archive (elle même sûrement due à une erreur en amont, au niveau du unpack ? ou encore plus en amont, après édition, à la sauvegarde de l'archive ?...). En effet, dans le second stagenode, j'ai **controlSettings.home false, mais homeTransition n'est pas vide** :

        {
            "uuid": "967f9fe9-a5b2-41d8-af03-e8af90c7bbd1",
            "name": "MISSING_NAME",
            "image": null,
            "audio": "4e6d77dd10710fabc9b12b1be8a9717ed1ca329c.ogg",
            "okTransition": {
                "actionNode": "5cfbbc14-8e67-4ee0-b057-c3ebc3c7ed17",
                "optionIndex": 0
            },
            "homeTransition": {
                "actionNode": "5cfbbc14-8e67-4ee0-b057-c3ebc3c7ed17",
                "optionIndex": 0**
            },
            "controlSettings": {
                "wheel": false,
                "ok": false,
                "home": false,
                "pause": true,
                "autoplay": true
            }
        }

Dans reader.js, à la ligne 261 : 
```
if (node.homeTransition) {
  links.push(stageNode.homePort.link(getTransitionTargetNode(node.homeTransition, actionNodes, simplifiedNodes)))
 }
```
Dans story.json, si pour un stagenode le controlSettings.home est false, mais que son homeTransition n'est pas vide, alors **stageNode.homePort est undefined** 

La rustine suivante me permet d'éviter l'erreur, et de bien ouvrir mon histoire : 
```
if (node.homeTransition && stageNode.homePort) {
  links.push(stageNode.homePort.link(getTransitionTargetNode(node.homeTransition, actionNodes, simplifiedNodes)))
 }
```
Sans me lancer dans une root cause analysis, il semble qu'une cause plus profonde du problème soit due à l'encodage d'une information, "ne pas avoir de transition", par 2 moyens et donc 2 valeurs (stageNode.homePort:false ou homeTransition:{}). Sans avoir vérifier moi-même cette partie du code, j'imagine qu'il utilise soit l'une soit l'autre des valeurs. A la ligne 261 le code vérifie qu'il y a bien une transition définie pour homeTransition mais la récupère par la suite par homePort (qui peut être incohérent avec homeTransition).

**Comment by marian-m12l** [comment]
Bonsoir,

Merci pour ce retour extrêmement détaillé !! Bien vu !

Cela confirme un bug que je venais d'identifier grâce à un pack que l'on m'a partagé. Le problème est effectivement à l'enregistrement du pack, lorsqu'on utilise un nœud d'histoire en désactivant le bouton HOME. Même si le bouton est désactivé, le comportement par défaut du nœud (rediriger vers le "premier nœud utile") est enregistré dans la transition.

Visiblement, ça ne pose pas de problème au firmware de la Lunii, ni à l'ouverture dans l'éditeur si le pack reste au format archive. Le problème apparaît lorsqu'on reconvertit depuis le format binaire. Je prépare un correctif pour la sauvegarde, et je vais effectivement ajouter le workaround à l'ouverture pour rester compatible avec les packs corrompus.

**Comment by marian-m12l** [comment]
Fixed with release 0.1.16, thanks for the PR :-)
