### ISSUE TITLE
Chemin de stockage des tokens non trouvé

### ISSUE THREAD

**Issue by ltressens** [marian-m12l/studio#106]
Le chemin de stockage du token indiqué dans le README ne correspond (pas/plus) à la structure actuelle du fichier `.local.properties`

> propriété `tokens`, attribut `tokens.access_tokens.data.firebase`

Voici la structure actuelle du fichier : 
```
{
	"tokens": {
		"access_tokens": {
			"data": {
				"server": "eyJhbGc..."
			},
			"user": {
				"server": "eyJhbGc..."
			},
			"billing": {
				"server": "eyJhbGc..."
			},
			"payment": {
				"server": "eyJhbGc..."
			},
			"studio": "eyJhbGc..."
		},
		"refresh_token": {
			"lunii_site": null,
			"luniistore_desktop": "eyJhbGc..."
		}
	},
	"user_id": "-M-4Zu*********eOYL",
	"password_reset": false
}
```

Tous les tokens présents dans ce fichier donne l'erreur : 
```
{
error: "Expected an ID token, but was given a custom token."
}
```
quand on appelle `https://lunii-data-prod.firebaseio.com/packs.json?auth=...`

**Comment by prbreezy** [comment]
J'ai le meme probleme avec l'appel de l'API avec l'un des tokens du fichier .local.properties la propriété firebase n'existe plus il semblerait.

**Comment by abdelhakel** [comment]
Même problème ici. Comme l'impression qu'une mise à jour a été faite récemment.

**Comment by marian-m12l** [comment]
Bonsoir,
Merci pour l'info. Effectivement il y a eu une mise à jour, et il semble qu'il n'y a plus d'appels (directs) à firebase.
Pour récupérer les données des packs, il faut maintenant utiliser le token `data.server` avec un appel du type :

```
curl -o official.json -H 'Accept: application/json' -H 'Content-Type: application/json; charset=UTF-8' -H 'X-AUTH-TOKEN: valeur_du_token_jwt' https://server-data-prod.lunii.com/v2/packs
```

Le fichier récupéré diffère légèrement, et il faut donc modifier le code pour prendre en compte également ce format.

**Comment by prbreezy** [comment]
Je récupère uniquement ceci dans mon fichier official.json :

"{"code":"1.3"}"

**Comment by marian-m12l** [comment]
> Je récupère uniquement ceci dans mon fichier official.json :
> 
> "{"code":"1.3"}"

Le token est-il bien toujours valide ?

**Comment by ltressens** [comment]
Cela fonctionne. Je pense en effet @prbreezy que vous avez un token invalide.
Je me suis simplement déconnecté/reconnecté au Luniistore pour avoir un token frais

**Comment by prbreezy** [comment]
Exactement j'ai relancer l'application et c'est bon j'ai tous recuperer MERCI.

Et sincèrement merci beaucoup @marian-m12l tu as fais un boulot formidable ! 

Mon fils est aux anges et il est surtout plus coller a la television !

**Comment by abdelhakel** [comment]
ça marche ici aussi ! Merci beaucoup ! Hâte de voir la tête de mes filles quand elles découvriront les histoires enregistrées par leur papa.... :)

**Comment by nebcodigital** [comment]
Super travail @marian-m12l 
La nouvelle commande pull bien les story officielles ==>
![Capture d’écran 2020-06-03 à 22 36 50](https://user-images.githubusercontent.com/26482738/83686620-ce485a80-a5ea-11ea-98f2-e0b58b3abc00.png)

N'oubliez pas : Créer mais soutenez aussi Lunii ! Ils ont comme bcp souffert du covid.. :/
