### ISSUE TITLE
probleme ajout de pack

### ISSUE THREAD

**Issue by remisabo** [marian-m12l/studio#107]
d'abord, merci pour studio, c'est génial de créer ses propres histoires. Mais hélas, lorsque je glisse un pack vers la lunii, la bulle "ajout du pack a l'appareil" apparait mais rien ne se passe (pas de ligne de chargement en couleurs dans la bulle, le pack ne s'enregistre pas)

 - OS: mac os 10,13,6 high sierra
 - Browser firefox
 - STUdio application version 0,1,17
- jdk 14,0,1

**Comment by marian-m12l** [comment]
Bonsoir,
Avez-vous des logs dans la console ? Dans le navigateur ? Les libs lunii sont bien à jour ?

**Comment by Immelman51** [comment]
Bonjour j'ai le même problème. Le pop up "ENregistrement du pack d'histoire dans la bibliothèque" reste affiché en gris, et rien ne se passe. 
Je ne sais pas comment vous envoyer d'éventuels logs. Je suis à votre disposition.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
