### ISSUE TITLE
Maven compilation failed to get dependencies from Central

### ISSUE THREAD

**Issue by marxoo** [marian-m12l/studio#109]
First of all, thank you very much for your work !!
It's amazing !!

I did follow the README instructions to build the application. Could you change the README and add the argument : -Dhttps.protocols=TLSv1.1,TLSv1.2 to the maven commande. The Central repository of Maven is no more accessible with HTTP.

I had to use :
mvn -Dhttps.protocols=TLSv1.1,TLSv1.2 clean install

Thanks again for your great job and regards !

**Comment by marian-m12l** [comment]
Thanks for the feedback. I'll have to look at this, didn't notice the problem. Is your maven up to date?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
