### ISSUE TITLE
[Question] Is it possible to play and control some sound loops in background?

### ISSUE THREAD

**Issue by kaelhem** [marian-m12l/studio#111]
I found your amazing project today. It was an idea that I had since a long time, and you did it! So great!

Since few months, I work on a webapp to create interactive fictions like "choice your own adventure". And so far, it works not too bad. It allows you to create short textual stories with sounds effects and some icons (to symbolize objects/heroes).
I would love to make a side project to export data of my stories in a way that will allow to "vocalize" it, and then use STUdio to put them on the lunii box (will be a perfect device to play them).

In order to make stories created with my app on the lunii, it will be really great if there was any possibility to play sounds (like loops) that could be played in background (say, the same loop on several nodes). I don't think this feature exists in STUdio, and also I'm not sure at all this can be done with the hardware of the box. Have you some advices / clues about this?

If you want to have a better idea of what I'm talking about, you can have a look to my project, it's here (french only):  https://moiki.fr
And a story sample : https://moiki.fr/story/5ec80c1713653b0023a0d3c5

Thanks !

**Comment by marian-m12l** [comment]
Hi,

Sounds like a great project ;-)

From what I know of the Lunii story packs, there is no "smarts" in the box, it's simply a chain of stage and action nodes (as I have dubbed them), plus different controls depending on the stage node's configuration (wheel can be enabled to walk through a menu, ok/home/pause buttons can be disabled, the box can automatically jump to the next node when it's done playing the audio file).

Hope you enjoy the app, and any feedback is welcome :-)

**Comment by kaelhem** [comment]
Thanks for these precisions, I will make a try and I'll keep you informed of my "progress" :)

**Comment by kaelhem** [comment]
Hi,
I've just publish an app to convert stories made with [Moiki](https://moiki.fr) in audio. It allows you to export stories to STUdio format. There are still a lot of improvements to make, but it works !

The project is available on github, here: https://github.com/kaelhem/moiki-vocalizer

**Comment by marian-m12l** [comment]
![qualitywork](https://user-images.githubusercontent.com/50991156/92042260-202f8680-ed7a-11ea-8f89-766d5c9ff759.gif)

Looks great!
I'll need to have a better look to make it run.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
