### ISSUE TITLE
Customize HOME transition not saved

### ISSUE THREAD

**Issue by crazymonster999** [marian-m12l/studio#112]
**Describe the bug**
The cusomized HOME transition button is not saved/restored in the local library

**To Reproduce**
1. Go to the pack editor, and create a classical story (I used the template as example)
2. Click on "Customize HOME editor" 
![image](https://user-images.githubusercontent.com/1176052/84705382-98489600-af5b-11ea-9ff3-f76f5589a335.png)

3. Drag le Home point to a previous step. I don't want the Home button come back to the global main menu, but to the selection of the character.
![image](https://user-images.githubusercontent.com/1176052/84706008-9af7bb00-af5c-11ea-93ef-7343eac0b046.png)

4. Save the story and leave the editor
5. Edit the story from library of import it from file
![image](https://user-images.githubusercontent.com/1176052/84706704-bf07cc00-af5d-11ea-90e7-d7cc24157072.png)

Result : The custom HOME parameters are not displayed.
Luckily, if I push the saved story to the lunii box, the custom Home button works, and the story is back to the character selection instead of the main stories selection :-)
![image](https://user-images.githubusercontent.com/1176052/84706775-d8a91380-af5d-11ea-8446-1ef1825829d3.png)

**Expected behavior**
- Restoring the custom home functionnality
- Allow to return to intermediate step as even while editing, it's still displayed as a dotted line and not a sraight line
- Maybe having a link displayeded outside of the node box instead of crossing it, but it's only for impoving the graphical interface ;-)

**Desktop and environment (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Java version: [JDK 14.0.1 64bit]
 - STUdio application version [0.2.0-beta.2]

**Comment by marian-m12l** [comment]
Thanks for your feedback.
This is actually expected, altough I'll admit it's not very well documented. If you click on the little question mark beside "story node" on the left part of the editor, you'll see that the default behaviour for these nodes is to go back to the "first useful node", which is the one following the cover node. These so-called "simplified" nodes are designed to mimick the usual behaviour of official story packs, and make it somewhat easier to build a similar story pack. But these nodes make some assumptions that may feel counter-intuitive...
So, even though you customized the home transition, you actually re-built the default behaviour, which is what the editor sees when reloading your story pack.

**Comment by marian-m12l** [comment]
Doesn't mean there's no room for improvement, though:
* The story pack format could maybe store the "customized" state of the home transition
* Links could definitely be improved, although this can be manually worked around by adding points and moving the links.

**Comment by crazymonster999** [comment]
Thank you for your answer @marian-m12l 
So as there's no issue here, I'll close this issue.
