### ISSUE TITLE
Windows installation batch - small adjustment

### ISSUE THREAD

**Issue by Samous92** [marian-m12l/studio#113]
Hi,

I just deployed your solution two days ago ; your installation steps are quite clear and easy to follow. One small remark for Windows users : I had to slightly modify the studio-windows.bat.

Cause : The resolution of %~dp0 is having a \ at the end, which was generating a \\ 

set STUDIO_PATH=%~dp0

C:\ProgramData\studio-web-ui-0.2.0-beta.2>set STUDIO_PATH=C:\ProgramData\studio-web-ui-0.2.0-beta.2\

as a result, the copy command and java command were failing ; I just removed one \ after each %STUDIO_PATH% so the proper path could be found - a bit dirty, but efficient : 

here : 
:: Copy agent and metadata JARs
copy **%STUDIO_PATH%agent**\studio-agent-0.2.0-beta.2-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-agent.jar
copy **%STUDIO_PATH%agent**\studio-metadata-0.2.0-beta.2-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-metadata.jar

same for java command line : java -Dvertx.disableDnsResolver=true -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%studio-web-ui-0.2.0-beta.2.jar;%STUDIO_PATH%lib\*;. io.vertx.core.Launcher run studio.webui.MainVerticle

Beside that, I've never been able to execute the curl command properly, but while I was starting investigating the reason, I realised I could anyway run/create a project/connect my lunii, and deploy it successfully on it. Would that mean I'll have to copy the lunii directory in studio directory everytime ? Not such a big deal if so, but still interesting to raise.

Besides that, let me tell you that I find your work trully interesting and well designed, and your tool is giving the lunii a new dimension and use which is making it a lot more attractive for kids so they can build their own tree of story using their imagination  ; lunii itself should have think to distribute this kind of tool - it is making their device so more fun.

On my first project deployed on the lunii and the few attempts made, I've noticed some strange behavior in the "back to menu" function after the story was finished, but I will try to dig a bit more into that and report it properly with clear steps and behaviors if this can help.

Best Regards
Sam

**Comment by marian-m12l** [comment]
Thanks for the feedback.

It's strange that you are having issue with the dp0 path, did you customize it? Other people do not seem to have this issue.. Anyway, I'm trying to move away from launch scripts and home folder in a future release.

The curl command is actually just an example of how to get the file, but I have no idea whether it can work on Windows or not. As you noticed, you can work without that metadata file.

I'm glad you're enjoying :)

FYI there's apparently an official app on its way from Lunii, it seems.

Regarding the "back to menu" behaviour, there's embedded documentation in the editor (the question marks beside each node type). So-called "simplified" nodes are somewhat opiniated, they are designed to mimick the usual behaviour of official story packs and may be counter intuitive at first.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
