### ISSUE TITLE
Home button does not bring back to stories selection

### ISSUE THREAD

**Issue by gregtap** [marian-m12l/studio#114]
Hello there,

First off, thank you for this amazing project. This is gold for tinkering fathers :wrench: 

The first Korean [story](https://storage.googleapis.com/greg_stuff/WhatsApp%20Video%202020-06-19%20at%201.03.27%20PM.mp4) ;)

In a simple setup when I click on the Lunnii home button the story does restart instead of going back to the main menu selection.

**version:** 0.2.0-beta.2 (0.1.16)
I have to try 0.1.17.

![image](https://user-images.githubusercontent.com/26057/85096471-59526300-b22f-11ea-94e3-c773829c0a7f.png)

**Comment by marian-m12l** [comment]
Thanks for the feedback. Good to see the app being put to good use!

This kind of story is indeed not working. Unfortunately it is not trivial to fix and I'll need to take some time to look at it.

The "story node" is designed to mimick the behaviour of some official story packs, and its default behaviour is to go back to what I dubbed the "first useful node", which is the one following the cover. You can see some documentation by click the question mark beside each node type in the editor.

To fix it, you'll need to either use stage nodes and action nodes, or to add a menu between the cover and the story. Or you can have a look at the new official application from Lunii, which seems perfect for this kind of stories.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
