### ISSUE TITLE
Do not manage to create official.json

### ISSUE THREAD

**Issue by jbdeb06** [marian-m12l/studio#116]
Hi,

I'm following the steps and when I try to get my token and create the file "official.json", i copy paste the proposed curl command in Windows terminal. But the file "official.json" does not create. 
First i'm not sure where to get my token in "local.properties"

Here how my "local.properties" file looks like (I deleted all personal data)
Where the token is?
 
#Thu Jun 25 10:12:31 CEST 2020
user_id=XXX
email=XXX@yahoo.fr
token={"firebase"\:"XXX","server"\:"XXX"}
tokens={"tokens"\:{"access_tokens"\:{"data"\:{"server"\:"XXX"},"user"\:{"server"\:"XXX"},"billing"\:{"server"\:"XXX"},"payment"\:{"server"\:"XXX"},"studio"\:"XXX"},"refresh_token"\:{"lunii_site"\:null,"luniistore_desktop"\:"XXX"}},"user_id"\:"XXX","password_reset"\:false}
remember_me=1

thank you

**Comment by jbdeb06** [comment]
here the error on cmd windows

<a href="https://ibb.co/K6Wm99k"><img src="https://i.ibb.co/8M9Xjjp/curl.png" alt="curl" border="0"></a>

**Comment by jbdeb06** [comment]
I did find that the space between ":" and " application" was a problem. I deleted it, as well as space between ";" and "charset=UTF-8"

<a href="https://ibb.co/f2LbhQB"><img src="https://i.ibb.co/Vt5d73r/curl2.png" alt="curl2" border="0"></a>

and I also added the real adress of db folder in .studio, instead of "~"

It does create a file official.json" but the only things in it is "{"code":"1.1"}

**Comment by jbdeb06** [comment]
Ok by replacing all ' by " it works and I have a official.json of several hundred of kb...

Now I have another problem: when executing studio.windows.bat (I added the line " SET PATH=C:\Program Files\Java\jdk-11.0.7\bin" because otherwhise it didn't worked), i have "Succeeded in deploying verticle" at the end, but" http://localhost:8080/" does not work.

To be notted: I skipped the step "mvn clean install" because i didn't understand it at all (not explained what we have to do in the readme"


@echo off
SET PATH=C:\Program Files\Java\jdk-11.0.7\bin
set STUDIO_PATH=%~dp0
set DOT_STUDIO=%UserProfile%\.studio
set LOCAL_LUNIITHEQUE=%UserProfile%\AppData\Roaming\Luniitheque

:: Make sure the .studio subdirectories exist
if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
if not exist %DOT_STUDIO%\db\* mkdir %DOT_STUDIO%\db
if not exist %DOT_STUDIO%\lib\* mkdir %DOT_STUDIO%\lib
if not exist %DOT_STUDIO%\library\* mkdir %DOT_STUDIO%\library

:: Copy Luniistore JARs if needed
if not exist %DOT_STUDIO%\lib\lunii-java-util.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-java-util.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-gateway.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-gateway.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-wrapper.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-wrapper.jar %DOT_STUDIO%\lib\

:: Copy agent and metadata JARs
copy %STUDIO_PATH%\agent\studio-agent-0.1.17-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-agent.jar
copy %STUDIO_PATH%\agent\studio-metadata-0.1.17-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-metadata.jar

java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%/studio-web-ui-0.1.17.jar;%STUDIO_PATH%/lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle

**Comment by jbdeb06** [comment]
I'm still trying to solve my problem....

Now i installed maven and did the step "mvn clean install" but i get error


<a href="https://ibb.co/NNqHH59"><img src="https://i.ibb.co/7pD66Pn/mvn.png" alt="mvn" border="0"></a>

**Comment by marian-m12l** [comment]
Hi, and thank for your feedback.

I'm sorry you're having trouble running the curl command, it was really meant as a hint but not something to use right away, I'm not even sure it works on Windows. That said, the token to use is the first one : ` tokens={"tokens":{"access_tokens":{"data":{"server":"XXX"}`.

The maven command is only meant to build the application from the source code, so all you'd get is the distribution archive that you can download directly from github.

What do you get when you try to open the url while running the script?

**Comment by jbdeb06** [comment]
En regardant d'autre posts j'ai vu que vous parliez français aussi. Ce sera plus simple alors :)

Pour la commande curl, j'ai bien l'impression que ca a fonctionné, car j'ai a présent mon fichier official.json qui fait 507kb.

Je viens de comprendre qu'il faut laisser ouvert le terminal après avoir lancé le script "studio-windows.bat" sinon le lien "http://localhost:8080/" ne marche pas. Ce n'est pas précisé dans le readme et j'ai toujours le reflexe de fermé les fenêtres. Je l'ai fait et maintenant et j'ai accès au studio! Merci beaucoup

Je reviendrai sans doute avec des questions sur l'utilisation ;)

Merci encore pour tout ce travail !
