### ISSUE TITLE
[Feature request] Better support for the (ok, still beta) MyLuniiStudio stories 

### ISSUE THREAD

**Issue by xavbart** [marian-m12l/studio#117]
Currently Lunii is offering MyLuniiStudio in beta. Very basic stories (title and single story) can be recorded and loaded via the app to the luniistore app on the device. 
They can be copied from the device to the library but it seems the entered title is not kept (unique ID only).

**Comment by marian-m12l** [comment]
Hi. That would indeed be nice. I did not take the time to look closer at the application, but it looks like the metadata for custom applications are stored in another endpoint : `https://server-studio-prod.lunii.com/v1/users/<user_id>/packs\?v1\=true`, with user id coming from `.local.properties` file.

**Comment by julaudo** [comment]
Hi. I'm curious to know how you found out the endpoint?
About LuniiStudio I guess there is also a POST endpoint to send pack files, it would be interesting to be able to export custom pack in the Lunii account

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
