### ISSUE TITLE
[Readme] For Mac, recommend using Chrome/Firefox (or the ogg file won't play in preview)

### ISSUE THREAD

**Issue by xavbart** [marian-m12l/studio#118]
Safari is the default browser, but cannot natively play .ogg files. So the preview of the examples, or of the imported files from device, won't play. 
You should add a note in the readme to inform users that the preferred navigator should be Chrome or Firefox which may play ogg files.

**Comment by marian-m12l** [comment]
Thanks for letting me know!

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
