### ISSUE TITLE
Don't Find ".local.properties" in %UserProfile%\AppData\Roaming\Luniitheque folder

### ISSUE THREAD

**Issue by jxdm-dmoreau** [marian-m12l/studio#119]
**Describe the bug**
Don't Find ".local.properties" in %UserProfile%\AppData\Roaming\Luniitheque folder
Despite Luniistore running or not, connected on my accoung or not.
There is no sucjh file...

**Desktop and environment (please complete the following information):**
 - OS: Windows 10 64 bits
 - Browser Firefox
 - Java version:  JDK 11.0.7
 - STUdio application version  0.2.0

**Comment by marian-m12l** [comment]
Hi,

The official application may have changed how it works, I'll have to have a look.

Thanks for the feedback!

**Comment by jin146** [comment]
Luniistore has obviously changed the way it works, making it impossible to install studio if you don't have the old app files.

**Comment by marian-m12l** [comment]
Sorry for the poor reactivity, I've been focused mostly on the new firmware, and didn't run the Luniistore for a while. If this is Windows-specific, there's almost no chance I'd catch this kind of changes... However it shouldn't stop you from running STUdio, this step is optional.

**Comment by severin-lemaignan** [comment]
@marian-m12l same problem on Ubuntu with luniistore 2.2: no `.local.properties`.

**Comment by marian-m12l** [comment]
@severin-lemaignan is there any other interesting file? do you also have an xml file? I definitely need a fresh install of the store...

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
