### ISSUE TITLE
Cannot update a story

### ISSUE THREAD

**Issue by mmaret** [marian-m12l/studio#125]
**Describe the bug**
After few modifications of my story and updating its version number. I cannot replace the previous version.
I have to remove the previous version then push the new one 

**To Reproduce**
Drag n Drop a new version of a story while the previous one is still on the box

**Expected behavior**
Story is updated 

**Screenshots**

**Logs**
in the console log I got:
`2020-07-09 22:37:51,656 [ERROR] [s.w.s.StoryTellerService]: Cannot add pack to device because the device already contains this pack`

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.17-SNAPSHOT . Hum actually this field got autofilled but I'm running the last 2.0.0 build from sources

**Comment by marian-m12l** [comment]
Thanks for the feedback.

When you change the name or version of a pack in the editor (on the "blur" event) you should see a popup asking to generate a brand new uuid to avoid this situation (if you want to).

You say you're running from the sources, which commit exactly are you on? Did you try with the pre-packaged archive?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
