### ISSUE TITLE
Failed to deploy verticle studio.webui.MainVerticle

### ISSUE THREAD

**Issue by bluefr** [marian-m12l/studio#126]
**Hi,
i'm using a fresh Win10Pro system (just installed this week), with latest java 64 bits with official lunii store installed ; and using studio 2.0
The studio is in a path with no spaces ;**
**%PATH% contains** C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
**java -version says** 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

**I get the following error upon launching the script**
[ERROR] [io.vertx.core.impl.launcher.commands.RunCommand] [ClasspathHandler.java:170]: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I'm generally know my way around java ; but can't solve the problem ; any ideas ?

Thanks,

**Comment by bluefr** [comment]
Finally have seemed to got it to work :

- installed latest jdk (14)
- changed %PATH% to point to the java.exe from the latest JDK
(although I did try quite a lot of others things first ; but those 2 steps seems to have done the trick)

**Comment by marian-m12l** [comment]
@bluefr Thanks for the feedback. Indeed, the first error message is telling you that you're trying to use a class compiled for Java 11 (version 55.0) from a Java 8 (version 52.0) JRE. It seems that, for some reason, installing the JDK on Windows does not update your system PATH and the OS keeps using JRE 8... I'll need to have a look at some point...

**Comment by clegros** [comment]
I had the same issue despite a newer JDK installed (11), the problem comes from the order in the %PATH% : 

 `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;` wich use java 8 was  **the first java path discovered to use**, even if a newer JDK is installed, wich is a the end of the %PATH%

**Comment by pierrecorsini** [comment]
Removing all java from computer and re installing latest JDK.21 solve it for me.
