### ISSUE TITLE
STUdio - Story Teller Unleashed Marketplace

### ISSUE THREAD

**Issue by cvandeplas** [marian-m12l/studio#129]
Hello, Bonjour,

I was wondering if there are already ongoing initiatives to build a STUdio marketplace allowing people to share their creations.

The features could be:
- [ ] Allow people to upload their own recorded stories/packs to a website.  (creative commons or free from rights)
- [ ] API to allow STUdio to access icons, description, flowchart and download of the pack.
- [ ] (later) Allow people to create their own story/pack online, and download the pack. A separate small binary/jar could be developed to add the story to the Lunii with less complexity.

Of course, the website would need to comply to the EUCD (European Copyright Directive) and takedown copyrighted material wrongly uploaded to the website.

What are your thoughts? 
I'm happy to contribute to the development of such online portal.

As a first step perhaps a separate github repo could be used to host the zips? 

Some resources:
- (not functional anymore) http://www.crdp-strasbourg.fr/je_lis_libre/
- CC BY-NC-ND - http://www.bibliboom.com/pages/genres/contes-fables-livres-audio-gratuits-a-telecharger.html
- CC0 - https://librivox.org/search?primary_key=2&search_category=language&search_page=1&search_form=get_results
- https://litterature-jeunesse-libre.fr/
- https://outilstice.com/2020/02/5-sites-pour-ecouter-des-livres-audio-gratuits/

Public domain cliparts / images:
- https://openclipart.org/
- https://publicdomainvectors.org/
- http://www.i2clipart.com/

**Comment by marian-m12l** [comment]
Hi,

Thanks for the suggestion :-)

I think I have addressed this earlier; while the idea is very appealing, I just don't think there would be enough eligible material to justify the work and the need to ensure there are no breach of copyright.

**Comment by sebbelese** [comment]
Hi,

I have started to build a sharing platform for open stories in the STUdio format. Hopefully it will be put it online in a not too far future.

It was also my fear that there will be very few shareable contributions. but It was an interesting project for me to learn django/js. I will let you know if I complete this project.

**Comment by sebbelese** [comment]
I put the website online, called mhios. It is not yet completely finalized, but ready for contribution.

[https://www.mhios.com](https://www.mhios.com)

Happy to hear any comment

**Comment by cvandeplas** [comment]
That's a very nice website, with already excellent content ! thank you !
I'll try to upload some stories now and then.

**Comment by sebbelese** [comment]
Thanks for adding stories, it is quite difficult to get content.

There may be some remaining bugs, please let me know if you have difficulties to upload or anything else.

**Comment by cvandeplas** [comment]
Sure, it might be useful to have some resources to help people make story packs while being compliant with copyright. (not only for the audio, but also images)
I might work on a small howto in the future pointing to locations with CC0 images and so on.

**Comment by kaelhem** [comment]
Hi,
Just wanna share with you my project, because it could be complementary to yours.
I've made an editor to write interactive fictions easily (aka. no code) that you can check here : https://moiki.fr
It's in french only, but english translation is on the way! And it's not open-source, but it's entirely free.

In addition to this project, I also made a desktop app named _Moiki-Vocalizer_, that simplify the task of "vocalizing" (record your voice with a microphone) stories made with Moiki.
And last, but not least, I managed to make a ready-to-use STUdio export.
This desktop app is open-source and available here : https://github.com/kaelhem/moiki-vocalizer

If you want an example, a Moiki user posted an export on itch.io which you can download here: https://batteman.itch.io/ohoh-joyeux-bazar (the sound is a bit low, but my sons were able to play it on the Lunii)

I plan to update the application soon to make it compatible with the new framework (there are png in the export which should be in bmp RLE).
Cheers !

**Comment by sebbelese** [comment]
Hi kaelhem,

Thanks for sharing your work. This is a very nice website that you built with already a fair amount of stories.

There may be some possible interaction between the websites. An option from my side - if you would allow it - would be to display the stories from moiki.fr on mhios.com and allow them to be read in mhios.com reader. They would be displayed with the proper credits and link to moiki.fr (something like "Check out the original text-based version of this story on moiki.fr").

It should be possible to write some scripts to automatize the use of your vocalizer on stories freshly added to moiki and upload the result on mhios. 

Unfortunately, doing the other way round is another story, so this proposition may not be very interesting for you.

I wanted to contact you privately to avoid polluting this place, but there is no PM in github. Please contact me at contact@mhios.com if you are interested in finding some ways for our sites to work together. I have a bit of time to do some developments.

**Comment by kaelhem** [comment]
Hi sebbelese,

Apologize if I made you understand that I am looking for this kind of partnership.

I think you misunderstood what Moiki is doing. Moiki's story scheme is more complex than STUdio's and most stories simply cannot be converted. To be compatible with Lunii, stories must be created in "simplified mode" (which is not the case for published stories).
Also, for copyright reasons, it is a no-no to publish these stories on your website.

To clarify, Moiki allows you to create stories with branches and offers a simple way to vocalize them _(and with the simplified mode, there is a Lunii export)_. My previous message, was rather addressed to people wishing to create stories... With the obvious idea of advertising my tool :)

The best I can propose is to add a link from the Moiki-Vocalizer repo to mhios.

**Comment by pozil** [comment]
Thanks for setting up this website @sebbelese. I'm happy that someone took the time to build a place where we could share our work. I've probably spent something like 4-5 hours building a story and I really want others to enjoy it.

@marian-m12l while I totally get why you don't want to build that website yourself could you just link to it in the readme? Few people will see it in this GitHub issue and you're probably safe with a disclaimer that you don't own this site.
Being able to see the work of others might even bring more people to STUdio, who knows :)

**Comment by sebbelese** [comment]
Thanks @pozil for uploading your story, this is exactly the kind of material that the website needs, with interactivity & real voices. I know how long it takes to produce these and how difficult it is to rely only on non-copyrighted material. Hope many will follow your example ;-)

**Comment by marian-m12l** [comment]
@pozil @sebbelese @kaelhem This is great to see other initiatives around the lunii ! I'll make sure to add links when I'll rework the readme for the next release, if that' ok for you of course.

**Comment by sebbelese** [comment]
@marian-m12l thanks for considering including the link in the Readme, I am certainly OK with this.
