### ISSUE TITLE
problem chargement pack

### ISSUE THREAD

**Issue by popostef** [marian-m12l/studio#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Failed to fetch

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.17

**Additional context**

**Comment by bourgouinadrien** [comment]
@popostef how can we able to help you if you don't fill any field of your issue ?

**Comment by popostef** [comment]
Hello,

Sirry, everithing are ok.

Durand Stéphane
06.22.70.20.19
durand.stephane35@gmail.com

Le dim. 9 août 2020 à 18:30, bourgouinadrien <notifications@github.com> a
écrit :
