### ISSUE TITLE
Latest update lunii

### ISSUE THREAD

**Issue by ateliermeteorite** [marian-m12l/studio#132]
Hello Is there a problem with the update of Lunii a few days ago? I did this before running STUdio and it doesn't work for me.
However, I followed all the steps.

Otherwise I wanted to tell you that the work you did on the Lunii is Incredible !!! well done
<img width="1336" alt="Capture d’écran 2020-08-29 à 13 34 12" src="https://user-images.githubusercontent.com/60346598/91635879-58426c80-e9fc-11ea-8fd6-c2ba99ccf5f3.png">

**Comment by PierreLeresteux** [comment]
The same for me ... 

It was working on a linux before the update. I try on Windows and same as you ... unable to display the Lunii content, so unable to add my custom stories.

No error logs in the console to help you to investigate and find the issue :(

**Comment by MetallianFR68** [comment]
I'm not sure but it seems the libraries moves from 'library' to 'packs'. Isn't it ?

**Comment by bourgouinadrien** [comment]
Good morning,

  Current version of STUdio isn't compatible with new Lunii firmware.
Is it possible that @marian-m12l make STUdio compatible again but nothing is sure about that.

**Comment by ateliermeteorite** [comment]
> Good morning,
> 
> Current version of STUdio isn't compatible with new Lunii firmware.
> Is it possible that @marian-m12l make STUdio compatible again but nothing is sure about that.


yes I know that's what your proposal to dd the old firmware and a very good idea. you can do it ?
