### ISSUE TITLE
How to check firmware version ?

### ISSUE THREAD

**Issue by gilles6** [marian-m12l/studio#137]
Is there a way to check firmware version ?

**Comment by marian-m12l** [comment]
@gilles6 sounds like you figured it out?

**Comment by chevallierce** [comment]
> Is there a way to check firmware version ?

Gilles, adid you found how to check the firmware version?

**Comment by marian-m12l** [comment]
@gilles6 @chevallierce The main difference between firmware 1.x and 2.x is that a device with the 2.x will mount a partition of the full SD card when plugged. This partition contains hidden files `.md` and `.pi`, as well as hidden folder `.content`.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
