### ISSUE TITLE
Ability to delete a node link

### ISSUE THREAD

**Issue by dreeco** [marian-m12l/studio#14]
When adding a bad link between 2 nodes it's impossible to delete otherwise than to delete one of the nodes.

**Comment by marian-m12l** [comment]
Actually it is possible, just really not easy to find... That's the behaviour of the underlying lib that I use for the graph editor. When clicking on a link, it creates a new point on it, so pressing "delete" only deletes the created point. To only select a link, one has to shift-click on it, and then "delete" actually deletes the whole link.

I'm leaving the issue open, as this should be documented, or I should see if the lib can now be tweaked to change this behavior. I think this was planned, but in a major overhaul that may take some time to be released.

**Comment by dreeco** [comment]
Ok, that's great.

**Comment by marian-m12l** [comment]
Fixed with version 0.1.2

Simple click on a link now only selects it.
Ctrl+click is used to create additional points.
Shift+click for selecting multiple elements.
