### ISSUE TITLE
Luniistore compatibility?

### ISSUE THREAD

**Issue by ramsestom** [marian-m12l/studio#144]
I did not saw it mentionned in the readme. 
So, if I use Studio with my lunii device to store some custom stories on it, would my lunii device still work with the Luniistore to transfer official stories from Lunii on it (or once I start using Studio, do I have to use it for all transfers to my Lunii device, even for official stories from the Luniistore)?
And if a lunii device with custom stories on it (transfered with Studio) is still usable with the Luniistore, how would these custom stories packs appear on the Luniistore (can I see them? delete them?)
Thanks for precising this point

**Comment by marian-m12l** [comment]
@ramsestom Yes, your device would still work with the Luniistore. Your custom stories would simply appear as "unknown" story packs, and you'd be able to move/delete them on the device.

**Comment by vpoulailleau** [comment]
@marian-m12l I think that this is an important answer that could be added in the README.

BTW, thanks for this project and your time. I'm waiting for #122, but I know what it is to work on free software on free time, so I'll just say thanks! (I may help on #122, but I don't know what I can do)

**Comment by marian-m12l** [comment]
@vpoulailleau That's right, the readme (or a wiki page?) could give more info regarding how to operate the application.

If you want to help with the new firmware, you can have a look at the discussion on #122, there's pretty much everything I know about it. I'm going to post a little update with some observations I made.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
