### ISSUE TITLE
Token et Metadata, Error !

### ISSUE THREAD

**Issue by JitHub0** [marian-m12l/studio#146]
Bonjour, tout d'abord merci pour votre application STUdio, cela va nous permettre de créer nos propres histoires et faire travailler l'imagination des bambins autour de nous :) 

**Describe the bug**
Impossible To fetch the story pack metadata:

C'est la que j'ai un probleme. Je trouve bien mon token qui, si je ne me trompe pas, commence aprés 
tokens={"tokens"\:{"access_tokens"\:{"data"\:{"server"\:"**etQ................**" 

Ensuite je colle mon token a l'adresse https://lunii-data-prod.firebaseio.com/packs.json?auth=**etQ......** , j'appuie sur entrée et j'ai une erreur : error"Missing claim 'kid' in auth header." 

Quand je l'enregistre dans Studio/.db en official.json ou se trouve un unofficial.json, STUdio ne s'ouvre plus. 
Si je le supprime, je peut reutiliser STUdio mais je n'ai toujorus pas les noms.

Pouvez vous me dire ou je me trompe svp car cela fait 4 jours que j'essaie tout ce qui est possible.

Merci

**Comment by JitHub0** [comment]
[Résultat de Terminal.txt](https://github.com/marian-m12l/studio/files/5714725/Resultat.de.Terminal.txt)

**Comment by marian-m12l** [comment]
Bonjour,

Merci pour le retour. Le chemin pour le token semble bon. Est-il toujours valide ? Vous pouvez le décoder sur jwt.io par exemple. Par contre l'URL n'est-elle pas plutôt https://server-data-prod.lunii.com/v2/packs ? Le token devrait être passé en tant que'en-tête HTTP et non comme paramètre de l'URL.

Pour le comportement de STUdio, c'est normal si le contenu du fichier json est invalide.

N'hésitez pas si vous avez d'autres questions :-)

**Comment by gormux** [comment]
Hello,
Je confirme, aucun souci avec un curl en mettant l'entete qui va bien.
L'API n'attends pas un parametre get nommé auth mais un header X-AUTH-TOKEN dans la requete.
notabug du coup, juste mauvaise utilisation.

Peut etre manque-t-il une doc officielle dans le readme pour récupérer ce json ?
Si ca convient je veux bien faire un PR ces jours ci avec les instructions complètes.

**Comment by apic-jeremy** [comment]
> Hello, Je confirme, aucun souci avec un curl en mettant l'entete qui va bien. L'API n'attends pas un parametre get nommé auth mais un header X-AUTH-TOKEN dans la requete. notabug du coup, juste mauvaise utilisation.
> 
> Peut etre manque-t-il une doc officielle dans le readme pour récupérer ce json ? Si ca convient je veux bien faire un PR ces jours ci avec les instructions complètes.

Bonjour,
Oui s'il vous plait, pourriez-vous faire une doc plus détaillé et à jour concernant le script de mise à jour des images officielles ?

Merci beaucoup !

**Comment by apic-jeremy** [comment]
@JitHub0 j'ai trouvé une solution. Créez un .bat avec ce code :

```
@setlocal enableextensions enabledelayedexpansion
@echo off
set STUDIO_PATH=%~dp0
set DOT_STUDIO=%UserProfile%\.studio
set LOCAL_LUNIITHEQUE=%UserProfile%\AppData\Roaming\Luniitheque

:: Copy token
for /f "tokens=5 delims=:," %%a in ('type %LOCAL_LUNIITHEQUE%\.local.properties^|find "tokens"') do (
  set tok=%%a & goto :continue
)
:continue
set tok=%tok:~1%
set tokk=!tok:~0,-2!
SET URL=https://server-data-prod.lunii.com/v2/packs
curl %URL% -o %DOT_STUDIO%\db\official.json
pause
```

Et ça fait le travail ;)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
