### ISSUE TITLE
Je ne vois pas le contenu de mon lunii

### ISSUE THREAD

**Issue by xxchkounexx** [marian-m12l/studio#147]
Bonjour, 

J'ai installé STUdio en suivant les instructions. Il s'ouvre sans souci mais je ne vois pas le contenu du lunii.

Voici une capture d'écran : [](https://ibb.co/0j71PZg)

**Comment by Tharkhun** [comment]
Il me semble que c’est justement le problème avec le nouveau firmware. Si la Lunii est neuve c’est normal, il faut attendre la nouvelle version de STUdio

**Comment by marian-m12l** [comment]
Effectivement, le support pour le nouveau firmware n'est pas encore au point. Vous pouvez suivre l'évolution ici : #122
