### ISSUE TITLE
Même problème...

### ISSUE THREAD

**Issue by Ludman** [marian-m12l/studio#149]
Bonjour Mariam,
je n'arrive pas à visualiser la Luuni Dans STUdio ,j'i bien réussi à créer ma premiere histoire personnalisée, mais rien dans la fenetre de gauche. merci d'avance pour votre aide et pour cet outil qui ouvre le chant des possibles 
<img width="1440" alt="Capture d’écran 2020-12-25 à 17 01 28" src="https://user-images.githubusercontent.com/76585639/103138434-ee4c8200-46d2-11eb-8db7-b1b4811dd667.png">

_Originally posted by @manuelchavanet in https://github.com/marian-m12l/studio/issues/43#issuecomment-751266497_

Bonjour !

Magnifique travail !! L'interface et les possibilités sont incroyables ! Mes fils vont être aux anges d'entendre des histoires avec leurs prénoms et la voix de leurs parents ! Je suis conquis, dans le principe en tout cas, car je suis confronté au même problème que manuelchavanet, je n'ai aucune Lunii qui apparait, malgré l'appli officielle installée et la Lunii reconnue dans celle-ci.

J'ai essayé un autre navigateur (safari n'étant pas toujours le plus... compatible...). J'ai essayé toutes les combinaisons possibles avec les 3 items : allumer la Lunii, lancer STUdio, et lancer le Luniistore... rien n'y fait, aucune Lunii reconnue dans STUdio...

Maintenant que j'ai vu ce qui était possible, je trépigne d'impatience de pouvoir mettre mon propre Pack dans ce petit boitier... Alors si vous avez une idée du problème...

Merci d'avance,

Ludman

**Comment by agademer** [comment]
Nouveau aussi sur le coup (Noël, Noël), il semblerait effectivement que ce soit un problème de nouveau firmware.
Voir ici : https://github.com/marian-m12l/studio/issues/122

Il semblerait aussi qu'il y ait des gens sur le coup (mais il faut leur laisser le temps).

Merci à toute l'équipe !

**Comment by Ludman** [comment]
> Nouveau aussi sur le coup (Noël, Noël), il semblerait effectivement que ce soit un problème de nouveau firmware.
> Voir ici : #122
> 
> Il semblerait aussi qu'il y ait des gens sur le coup (mais il faut leur laisser le temps).
> 
> Merci à toute l'équipe !

Oui merci pour le lien, j'ai farfouillé un peu aussi pour voir, et il semblerait que je sois parti un peu vite en besogne... Je vais patienter gentiment qu'une nouvelle version apparaisse et soit compatible avec le nouveau firmware (en espérant que ce soit possible...). En attendant, je vais grandement céder au store, et commencer tranquillement à réfléchir à mes histoires...

**Comment by xbertrand** [comment]
Bonjour, 
j'avais le même problème de détection pour une Lunii acheté début janvier 2021.
En fait il ne se passait rien quand je branchais et que j'allumais la Lunii. Mais quand je l'étéignais, Dans STUdio, j'avais un message pour indiquer la déconnection de la Lunii.
J'ai résolu le problème en modifiant le fichier bat de lancement :
en 1ère ligne j'ai appelé le jdk dans la version installée sur mon PC :
SET PATH=C:\Program Files\Java\jdk-15.0.1\bin

et j'ai également renseigné le disque sur lequel appairaissait ma Lunii dans la commande FS_MOUNTPOINT :
set FS_MOUNTPOINT=F:\

Depuis ma Lunii est visible dans STUdio.

**Un immense merci à marian pour ce travail,** mes enfants sont contents de retrouver leurs histoires que j'avais sur CD en plus de celles disponibles sur le Luniistore.

**Comment by campafap** [comment]
J'ai le même souci mais sur MAC... Je ne comprends pas comment régler le probleme... une aide ?

**Comment by snefrou2** [comment]
bonjour, 
j'ai une lunii depuis 1 an, j'ai réussi a la connecter au studio hier et à transférer des histoires, depuis, ma lunii est reconnu mais le studio ne récupère pas les fichiers présents dessus et je ne peux plus rien y mettre. la version 4.2.0 elle ne se lance pas. je suis sous mac M1

<img width="1255" height="567" alt="Image" src="https://github.com/user-attachments/assets/93ada017-0615-4f09-a13a-09ccb1e22823" />
