### ISSUE TITLE
Unable to copy pack to device - Failed to convert archive format pack to binary format

### ISSUE THREAD

**Issue by nicorio** [marian-m12l/studio#151]
**Describe the bug**
I installed the STUdio (branch firmware2dot4, updated this morning with the latest fixes) and tried to install the default archived pack (SimplifiedSamplePack). The transfer cannot finish (error message "Échec de l'ajout du pack à l'appareil.").
Latest version of the Lunii device, with the new framework.

**To Reproduce**
1. Go to the STUdio home screen ("BIBLIOTHÈQUE LOCALE")
2. Drag the default pack SimplifiedSamplePack to the Lunii device
3. See error "Échec de l'ajout du pack à l'appareil. (see screenshot)

**Expected behavior**
The SimplifiedSamplePack should be uploaded on the device

**Screenshots**
![image](https://user-images.githubusercontent.com/469923/103480594-7ae2f880-4dd5-11eb-8d01-13e3bbf0ae92.png)

**Logs**
2021-01-03 15:25:07,625 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:253]: Pack to transfer is in archive format. Converting to FS folder format and storing in temporary folder: /var/folders/h9/375cyxss70vbt0pmz03zn_4h0000gn/T/SimplifiedSamplePack-d6ea7caa-f51f-42cd-a9a4-8af5acd3ae0f-v1.zip13337267884505482963
2021-01-03 15:25:07,626 [WARN ] [studio.webui.service.LibraryService] [LibraryService.java:255]: Reading archive format pack
2021-01-03 15:25:07,682 [ERROR] [studio.webui.service.LibraryService] [LibraryService.java:270]: Failed to convert archive format pack to binary format
2021-01-03 15:25:07,682 [ERROR] [studio.webui.api.DeviceController] [DeviceController.java:131]: Failed to read or convert pack
2021-01-03 15:25:07,683 [ERROR] [studio.webui.MainVerticle] [MainVerticle.java:96]: Exception thrown
io.vertx.core.impl.NoStackTraceThrowable: Failed to read or convert pack to folder format

In the network tab of my browser's developer tools : error 500 when calling http://localhost:8080/api/device/addFromLibrary. Here are the headers (copied as fetch from chrome console):

fetch("http://localhost:8080/api/device/addFromLibrary", {
  "headers": {
    "accept": "*/*",
    "accept-language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://localhost:8080/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"uuid\":\"d6ea7caa-f51f-42cd-a9a4-8af5acd3ae0f\",\"path\":\"SimplifiedSamplePack-d6ea7caa-f51f-42cd-a9a4-8af5acd3ae0f-v1.zip\",\"allowEnriched\":false,\"driver\":\"fs\",\"deviceUuid\":\"bc1fdc407ccd007316f4aba468213b8e36fa2a1cbf6faa110380862f532e34095aca7f6a80a7f5c17ff28cc50ce39519c1474f1e9596e5c65cf065f6ec5f5ff1862566249236d72f85649768915e9ecfb241671627ae0d9c07c20a6ae78a7e5b831343bad59d4275a6d346ad357c114423b4499ea8e1faa4d6e4d05dbeaaca54be10579f736e396791fcc22a05151de6dabaa159844847e7c34e011285de3586e62a6b1209c4fbd00c69f16856dfe33ba92f368e0e65ad24b584de21a0a2e1f990ae48b058265f55b9a807301c89d8f221985ef4aae413be9cb1ec9aa2b58a7b4a6de220686f3d7de06ebc4c75394aa0c9743653d54d2b482666e975cc9bd297\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});

> Internal Server Error: Error 500: Internal Server Error

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.2.1-SNAPSHOT

**Comment by t4w4n3** [comment]
This story pack cannot be uploaded to the Lunii because the audio files don't have the correct format, according to my understanding of the logs.

**Comment by t4w4n3** [comment]
You can try with the pack I just created, which works for me :
[patpatrouille.zip](https://github.com/marian-m12l/studio/files/5761773/patpatrouille.zip)

**Comment by nicorio** [comment]
Indeed, your pack has been uploaded! Thanks for the tip!
I close the issue
