### ISSUE TITLE
Firmware 2.2 / Studio 0.3.0-alpha : Copy of the pack success but not seen on the Lunii

### ISSUE THREAD

**Issue by agademer** [marian-m12l/studio#152]
**Describe the bug**
Using a newly bought Lunii (Firmware 2.2) with the studio 0.3.0-alpha release on Windows 10.

The Lunii is seen, i was able to copy the story from the Lunii app to my local hard drive.
I was unable to copy the SimplifedSamplePack to the Lunii (as https://github.com/marian-m12l/studio/issues/151) but I was able to copy the patpatrouille pack (seen as answer in the same issue).

Nevertheless the pack is not seen on the Lunii (I can see the new directory on the mounted point, so the copy went effectively well).

Not sure were to look to make it work...

**To Reproduce**
1. Go to Studio
2. Import the patpatrouille.zip to the library
3. Drag & Drop the pack to the Lunii
4. Disconnect the Lunii and try to choose the pack.

**Expected behavior**
The pack should appear and play on the lunii.

**Screenshots**
Not applicable.

**Logs**
[studio-20210103-5.log](https://github.com/marian-m12l/studio/files/5762226/studio-20210103-5.log)

You can see in the log that the number of pack seen on the Lunii (8) is the same before and after the upload.

**Desktop and environment (please complete the following information):**
 - OS : Windows
 - Browser : Firefox
 - Java version: JDK 15.0.1
 - Maven version: 
 - STUdio application version : 0.3.0-alpha

**Comment by agademer** [comment]
After connecting the Lunii to the official store, it seems the copied folder was supressed.

Not sure it is a normal behaviour (official store suppress all custom packs) or not (official store supress this pack because it is somehow invalid).

Maybe the marian or the old-schooler of STUdio can help on that :)

**Comment by marian-m12l** [comment]
@agademer Thanks for the feedback. There seems to be a bug on Windows, the story pack is copied but is not added to the "packs index" which lists the packs installed on the device. You can manually edit this file (`.pi` at the root of the device partition) to add your pack's 16 bytes UUID. You'll need an hex editor for this. I believe the luniistore removed the story pack precisely because it was not on the index.

**Comment by agademer** [comment]
It's worked !
Found the UUID in the Editor Panel of STUdio.
Wrote it in `.pi` file with [HxD](https://mh-nexus.de/en/hxd/) and the pack is seen by the Lunii !
The official store see it too as "Unkown Album" and does not try to supress it.

Many thanks @marian-m12l for your quick and precise response and all your absolutly great work !

Thanks also to have done a alpha release because I wasn't able to properly install from source (weird message from maven, but I'm not familiar with this tool).

My daughter will be amazed and I'll will be so happy to tweak and build packs for her ! (The official app for recording stories is so limited.... it's sad it does not profit of all the branching possibilities of the Lunii (yet?))

All in all, many thanks again !

**Comment by marian-m12l** [comment]
This should be fixed with the new alpha release: https://github.com/marian-m12l/studio/releases/tag/0.3.0-alpha.2

Let me know.

**Comment by agademer** [comment]
I confirm that the upload of the pack is working on Windows with the 0.3.0-alpha.2 version. 

Thanks a lot !
