### ISSUE TITLE
Re-uploading a pack not working

### ISSUE THREAD

**Issue by agademer** [marian-m12l/studio#153]
**Describe the bug**
When trying to upload a pack that is already on the Lunii. We get an "bug" error message.

**To Reproduce**
1. Upload a pack successfully (w/ drag & drop)
2. Drag & Drop the same pack
3. Get a red banner "Error : report this bug"

**Expected behavior**
1/ The "new" pack erase and replace the old one.
or
2/ We get an error message : "Please remove the pack from the Lunii before reuploading it".

**Logs**
[studio-latest.log](https://github.com/marian-m12l/studio/files/5774396/studio-latest.log)

**Desktop and environment (please complete the following information):**
 - OS: Win 10 (64b)
 - Browser Firefox
 - Java version: 15.0.1
 - Maven version: 
 - STUdio application version: 0.3.0-alpha.2

**Additional context**
Not a very annoying bug (it is intuitive to erase before reuploading), but I though I would report it for the future :)

**Comment by marian-m12l** [comment]
Thanks. Behaviour 2) is what should happen.

**Comment by marian-m12l** [comment]
And maybe also add an option to change this behaviour to "replace".

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
