### ISSUE TITLE
Impossible to edit a story previously partially created by STUdio

### ISSUE THREAD

**Issue by sebbelese** [marian-m12l/studio#157]
**Describe the bug**
I **partly** created a story on STUdio, then saved it to the library. Some sounds are missing, but all the structure is there.

When trying to continue edits on the next day, I got an error message "Failed to load story pack" and could not load it in the editor

**To Reproduce**
1. Start with a clean STUdio setup
2. Import the attached story, created using STUdio
[Le_lion_et_le_rat-1fca8beb-d2e4-4b94-9cb5-1fc5053b9ab3-v1.zip](https://github.com/marian-m12l/studio/files/5783590/Le_lion_et_le_rat-1fca8beb-d2e4-4b94-9cb5-1fc5053b9ab3-v1.zip)
3. Open this story pack in editor
4. "Failed to load story pack" message should appear

**Logs**
No error message appears on the console.

It appears that an object is null:

> Cannot read property 'actionNode' of null

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.2.0

**Comment by marian-m12l** [comment]
Ah, haven't had this kind of bug for a long time. Need to look at the pack file. Thanks for the feedback.

**Comment by marian-m12l** [comment]
Oh, that one's easy :-) This was fixed after the 0.2.0 release: see #123 and https://github.com/marian-m12l/studio/commit/acb7914ff78b04a0cde3eb4932a4379641631d62

You can either build from the source or get the 0.3.0 alpha release. Hopefully it does not break compatibility with the old firmware :-D

**Comment by sebbelese** [comment]
Thanks it works! I should have tried before posting...

**Comment by marian-m12l** [comment]
No worries :-) And you were using the latest stable version.

**Comment by sebbelese** [comment]
I was using 0.2.0 when it failed.

I tried on a 0.2.1-snapshot that I already had on my computer, and it worked
Also worked with 0.3.0-alpha

I did not try to connect to the Lunii however
