### ISSUE TITLE
Popup to test 0.2.0-beta still present

### ISSUE THREAD

**Issue by BrunoSpy** [marian-m12l/studio#159]
On master, the popup to try the new beta version still points to the 0.2.0-beta

**Comment by marian-m12l** [comment]
@BrunoSpy Thanks for the feedback. You see this popup only once, right? How are you running the application? IIRC the popup should not show if the build is more recent than the "announce" file.

**Comment by BrunoSpy** [comment]
Yes the popup appears only the first time.
I built the latest master on linux : 0.3.0-alpha.3-SNAPSHOT

**Comment by marian-m12l** [comment]
Sounds like a bug.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
