### ISSUE TITLE
Adding pack to device... popup still remains once story has been added

### ISSUE THREAD

**Issue by cvandeplas** [marian-m12l/studio#165]
**Describe the bug**
The adding pack to device... popup still remains, even when the story has been successfully added.

**To Reproduce**
1. Add a story
2. Watch the pop up say the story is being added
3. It does not dissapear

**Expected behavior**
The message goes away when the story has been uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/1073662/105623501-77fa8700-5e1a-11eb-901c-99401e963fb0.png)

**Logs**
```
2021-01-24 07:59:51,280 [INFO ] [s.w.s.StoryTellerService]: Transferring pack folder to device: /tmp/Les_histoires_de_pomme_d'api-d7daed69-5e3c-4334-a892-35710dd9bee0-v1.zip722166074712433959/0DD9BEE0
2021-01-24 08:00:34,427 [INFO ] [s.w.s.StoryTellerService]: Pack added.
```

**Desktop and environment (please complete the following information):**
 - OS: Linux
 - Browser : chrome (latest)
 - STUdio application version: latest git

**Comment by marian-m12l** [comment]
@cvandeplas I'm trying to improve the whole pack conversion / upload UX, so I'll keep this in mind. Thanks.

**Comment by mansmotown** [comment]
Hi

Same issue for me. Each time a pop up appears, it doesn't disappear. I create a pack, the simulation works fine (when clicking on the eyes), but when I want to save, the pop ups stay forever so nothing happens. Same thing when I want to import a pack.
Thanks

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
