### ISSUE TITLE
[WINDOWS] I'm not able to create de Json

### ISSUE THREAD

**Issue by Cuhesse** [marian-m12l/studio#174]
I have my authentification token and try the curl command from de Readme section but i have an error . I've tried the one with " instead of ' like I read in another issue.

Here's the curl command i used:
`curl -o ~/.studio/db/official.json -v -X GET -H 'Accept: application/json' -H 'Content-Type: application/json; charset=UTF-8' -H "X-AUTH-TOKEN: my token" https://server-data-prod.lunii.com/v2/packs`
Here's the response i got in the command prompt:

Note: Unnecessary use of -X or --request, GET is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Could not resolve host: application
* Closing connection 0
curl: (6) Could not resolve host: application
Note: Unnecessary use of -X or --request, GET is already inferred.
* Could not resolve host: application
* Closing connection 1
curl: (6) Could not resolve host: application
Note: Unnecessary use of -X or --request, GET is already inferred.
* Rebuilt URL to: charset=UTF-8'/
* Could not resolve host: charset=UTF-8'
* Closing connection 2
curl: (6) Could not resolve host: charset=UTF-8'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 52.17.153.171...
* TCP_NODELAY set
* Connected to server-data-prod.lunii.com (52.17.153.171) port 443 (#3)
* schannel: SSL/TLS connection with server-data-prod.lunii.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 197 bytes...
* schannel: sent initial handshake data: sent 197 bytes
* schannel: SSL/TLS connection with server-data-prod.lunii.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with server-data-prod.lunii.com port 443 (step 2/3)
* schannel: encrypted data got 2929
* schannel: encrypted data buffer: offset 2929 length 4096
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with server-data-prod.lunii.com port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with server-data-prod.lunii.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /v2/packs HTTP/1.1
> Host: server-data-prod.lunii.com
> User-Agent: curl/7.55.1
> Accept: */*

Can someone help me? I'm not good with code.

**Comment by vpoulailleau** [comment]
This command worked great for me: https://github.com/marian-m12l/studio/discussions/155#discussioncomment-266385

Note that you have to get the token (a long text) with your browser, and update the commands accordingly.

The command you use is for Linux or Mac, are you using one of these operating system?

**Comment by Cuhesse** [comment]
Thanks I did'nt saw the [#155]. My bad.
I used your command line and changed the tilde with the exact folder destination and it worked like a charm.
Thank you.
