### ISSUE TITLE
Lunii story left panel does not display on http://localhost:8080/

### ISSUE THREAD

**Issue by Menzbenz** [marian-m12l/studio#177]
Hello Experts,
First of all, i want to thank you for you time and effort providing us the maintenance of the studio. 
**Describe the bug**
I'am unable to display the left panel (see picture 1) of my device. Everything was applied like in this URL https://www.hteumeuleu.fr/mettre-ses-propres-histoires-sur-la-lunii/
My device is connected to luniistore without any problem. I have tried many wire to connect my lunii in order to display the left panel with all stories that i have already bought .

**To Reproduce**
1-download the version studio-web-ui-0.2.0-dist .
2- from my MS windows command line , execute : studio-windows.bat
3- My defaut internet browser open in this page http://localhost:8080/.
4- I can see the stories editor and i can edit stories, but the device panel is absent.

**Expected behavior**
Seeing the left panel in order to copy my homemade stories to the lunii device

**Screenshots**
See picture 2

**Logs**
2021-02-14 15:54:18,598 [INFO ] [studio.webui.service.StoryTellerService] [StoryTellerService.java:47]: Setting up story teller driver
2021-02-14 15:54:18,606 [INFO ] [studio.driver.LibUsbHelper] [LibUsbHelper.java:215]: Initializing libusb...
2021-02-14 15:54:18,647 [INFO ] [studio.driver.LibUsbHelper] [LibUsbHelper.java:255]: Hotplug is NOT supported. Scheduling task to actively poll USB device...
2021-02-14 15:54:18,760 [INFO ] [studio.webui.MainVerticle] [MainVerticle.java:106]: Opening URL in default browser...
2021-02-14 15:54:18,860 [INFO ] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:81]: Succeeded in deploying verticle

**Desktop and environment (please complete the following information):**
 - OS: Windows 8 professionnel
 - Browser : chrome , mozilla
 - Java version: 14.0.1
 - Maven version: i dont know how to get it
 - STUdio application version 0.2.0 

**Additional context**
In the file studio-windows.bat, i added these lines:
set FS_MOUNTPOINT=D:
-Dstudio.fs.mountpoint=%FS_MOUNTPOINT% (in option of the command java ..) 

I have tried D:\ , D: , D:/ with and without double-quotes 

----
Could you please help me , I would like to please my children :) 
Thank you in advance 

![1-device left panel](https://user-images.githubusercontent.com/79024771/107880850-acc1a180-6ee1-11eb-8b6e-49e134d65f99.png)
![2- what i see](https://user-images.githubusercontent.com/79024771/107880853-ae8b6500-6ee1-11eb-91b0-98407d77e20d.png)

**Comment by Coleim** [comment]
Hello,
Same here on linux, with latest studio-web-ui-0.3.0-beta.2.jar
Thanks

**Comment by Menzbenz** [comment]
Hello,

It works well with the latest version , thank you very much.

Best regards,
