### ISSUE TITLE
Import from Scratch Programming Language

### ISSUE THREAD

**Issue by alexvaut** [marian-m12l/studio#179]
My kids like their Lunii and even more now since I added a couple of stories that I grab here and there. I also add some fancies sounds in the menu which make them laugh.

My kids are old enough to play with scratch (the programming language). https://scratch.mit.edu/ and they love building stories their with sounds, images...

So what about exporting their scratch programs to Lunii ? Of course, the program will have to follow some patterns but I believe that background changes, sound plays, switch case blocks can already make something nice. It could work pretty well I believe.

What do you think ?

**Comment by thi71126** [comment]
Hello,
I don't know scratch but all is possible.
Can you here upload an exemple of a scratch generated package?
Maybe it is possible to convert it for Lunni.
All Lunni need is :
- images 
- waves
- a JSON file that respect Lunni Format

**Comment by marian-m12l** [comment]
@alexvaut I've actually thought about this :-) However I don't know enough of Scratch (just used it once with my kids) to think of a way that would be both idiomatic to Scratch and constrained enough to achieve a consistent conversion. Let the user use any block and most will be ignored when converting, leaving the user puzzled. Define custom blocks and you're constraining the user so much that they'd better use the dedicated editor in STUdio. I'd be happy to be wrong, though :-)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
