### ISSUE TITLE
No visible or hidden DB folder in %userprofile%\AppData\Roaming\Luniitheque

### ISSUE THREAD

**Issue by pntasle** [marian-m12l/studio#181]
Hello,
Thank for making this app available.
I've done a fresh install of the Lunii app on windows 10 20H2 and after connecting the box, authenticating on the apps, loading the content library and having no issue with the official app,  the folder "DB" doesn't exist en therefore I can't execute the curl command.
Do you have any clue for me  ?
thanks
PN

**Comment by thi71126** [comment]
Hi,
what is the version you use?
have you a error message?

if your userprofile name hat a <space> inside, you must maybe add doublequots  in your studio-windows.bat:
set DOT_STUDIO="%UserProfile%"\.studio

**Comment by marian-m12l** [comment]
@pntasle You can try the [latest beta release](https://github.com/marian-m12l/studio/releases/tag/0.3.0-beta.3), it fetches the "official metadata" automatically.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
