### ISSUE TITLE
Bibiliothéque invisible

### ISSUE THREAD

**Issue by djarnaud** [marian-m12l/studio#182]
Bonjour à tous,

J'arrive bien à accéder au Studio via localhost:8080. 
le problème c'est que sur la gauche je ne vois pas ma Lunii alors que celle-ci est bien connecté. De plus il est indiqué qu'il n'y a rien dans la bibliothèque, alors que j'ai des histoires officielles.

D'avance merci

Cordialement

**Comment by thi71126** [comment]
Salut,

as tu modifié le fichier studio-windows.bat
afin d'indiquer quelle lettre de lecteur la lunii utilise?
ex:
:: Configure mount point of the device
set FS_MOUNTPOINT=D:

as tu une erreur dans les logs?
postes le fichier studio-latest.log

**Comment by djarnaud** [comment]
Bonjour thi71126,

Oui le problème venait du fait que je n'avais pas rentré la lettre du lecteur de la lunii!

Merci beaucoup!
