### ISSUE TITLE
Issue loading pack

### ISSUE THREAD

**Issue by ildrada** [marian-m12l/studio#197]
**Describe the bug**
Cannot load a pack I was able to load 2 months ago

**To Reproduce**
Load a
[studio-latest.log](https://github.com/marian-m12l/studio/files/6528581/studio-latest.log)
[studio-20210523-3.log](https://github.com/marian-m12l/studio/files/6528582/studio-20210523-3.log)

 pack (using drag and drop)

**Expected behavior**
Loading of the pack failed. While I tested them 2 months ago (but did not kept them on the device to add them progressively.
My set up did not change apart for standard updates

**Screenshots**
![image](https://user-images.githubusercontent.com/59011493/119270343-82783200-bbfc-11eb-854f-e5636d02d44e.png)

**Logs**
Logs for 2 packs I tried to add are attached

**Desktop and environment (please complete the following information):**
 - OS: W10
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
 - Java version: screenshot attached
![image](https://user-images.githubusercontent.com/59011493/119270419-de42bb00-bbfc-11eb-882d-e0dac8f00a6e.png)

 - Maven version: What is Maven ? the lunii is in 2.20
 - STUdio application version: 0.3.0-beta.3

Comment 
- I updated the lunii app and the java to the latest version => same issue
- My Lunii screen is going black for 1 sec when the issue happpens. like if it was unpluggued then pluggued
- tested with beta 2 and 3

**Comment by marian-m12l** [comment]
@ildrada Thanks for the feedback. Can you give a try to the latest release, just to be safe? Looks like your device is detected correctly, but transfer fails when creating the story pack folder on the device. I figure your device is working correctly with the official store? Do you have some sort of anti-virus software that could be getting in the way of the application trying to write to the mounted partition?

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
