### ISSUE TITLE
impossible to open studio

### ISSUE THREAD

**Issue by chamcham75** [marian-m12l/studio#198]
hello, When I run studio-windows.bat under windows 10 with java + 11 installed I get the following error message thank you if you can help me please

**Comment by chamcham75** [comment]
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by thi71126** [comment]
Hello

try to modify studio-windows.bat to add doublequots in this line:
set DOT_STUDIO="%UserProfile%"\.studio
because there is a space in your name

PS : you have forgessen one time to delete your real name  in the image above

**Comment by chamcham75** [comment]
Hello Thi71126,

thanks for my name

I modified as requested 

@echo off

_set STUDIO_PATH=%~dp0
set DOT_STUDIO="%UserProfile%"\.studio

:: Make sure the .studio subdirectories exist
if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
if not exist %DOT_STUDIO%\db\* mkdir %DOT_STUDIO%\db
if not exist %DOT_STUDIO%\library\* mkdir %DOT_STUDIO%\library

:: Copy agent and metadata JARs
copy %STUDIO_PATH%\agent\studio-agent-0.3.0-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-agent.jar
copy %STUDIO_PATH%\agent\studio-metadata-0.3.0-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-metadata.jar

java -Dvertx.disableDnsResolver=true -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%/studio-web-ui-0.3.0.jar;%STUDIO_PATH%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle_

now I have this as an error
![image](https://user-images.githubusercontent.com/84720618/119367234-0809e980-bcb2-11eb-85c4-046402f83855.png)

**Comment by chamcham75** [comment]
set DOT_STUDIO="%UserProfile%"\.studio

**Comment by chamcham75** [comment]
It's good, for my part, it was just necessary to put the folder at the root of my C drive:

thank you for your help

**Comment by marian-m12l** [comment]
@chamcham75 Should be fixed with the latest nightly build. Thanks for your feedback!
