### ISSUE TITLE
le menu pour créer des histoires disparait

### ISSUE THREAD

**Issue by chamcham75** [marian-m12l/studio#199]
Bonjour, au début ça fonctionnait normalement mais depuis je n'arrive plus à voir le menu pour créer un pack d'histoire et à partir d'un exemple.
Lorsque je F5 la page le menu réapparait quelques secondes et disparait.

Merci 

windows 10
chrome et firefox

![image](https://user-images.githubusercontent.com/84720618/119395357-ae1a1b80-bcd3-11eb-892a-1cf8f058db57.png)

![image](https://user-images.githubusercontent.com/84720618/119395642-1d900b00-bcd4-11eb-9981-5b17f8799327.png)

**Comment by thi71126** [comment]
![image](https://user-images.githubusercontent.com/77553154/119552481-e59fcb00-bd9a-11eb-898a-40e8a05a8767.png)

Salut, vas dans l'éditeur avec le bouton dans la barre noire puis réinitialise pour repartir de zéro.

**Comment by chamcham75** [comment]
salut, ok je vais essayer merci.

**Comment by marian-m12l** [comment]
@chamcham75 Merci pour le retour. Effectivement ce message s'affiche seulement si la bibliothèque est vide, mais serait tout aussi utile quand on a déjà des packs d'histoires.

**Comment by appenzellois** [comment]
Je suis d'accord. Ce n'est pas super intuitif de partir d'une histoire existante pour en faire un double et/ou faire une réinitialisation pour créer de nouvelles histoires. Une fois qu'on le sait, c'est ok, mais il faut le savoir ^^

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
