### ISSUE TITLE
Échec conversion des gros pack avec une v1

### ISSUE THREAD

**Issue by MiekBrantovskii** [marian-m12l/studio#204]
Lors d'un chargement d'un gros pack, plus de 250Mo, sur une boîte en firmware 1,2 il est impossible de réussir la conversion, STUdio me fait une erreur Java heap Space .

![16226247047481866992457878496267](https://user-images.githubusercontent.com/85223631/120452511-87727980-c392-11eb-916a-d2b194c14c1f.jpg)

**Desktop and environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Chrome
 - STUdio application version 0.3.0

**Additional context**
Désolé je suis un néophyte en informatique, si il manque d'infos n'hésitez pas à demander.

**Comment by MiekBrantovskii** [comment]
Bon alors, une gentille personne m'a aidé par ailleurs. Il semble que l'espace alloué de base pour java soit un peu court, du coup il faudrait ajouter un -Xmx4g quelque part. Ce que l'on m'a fait, et ça fonctionne désormais.
Ça vous parlera sûrement, pourriez vous faire la modification ?

Merci en tout cas, votre initiative a prolongé la durée de vie de la boîte de mon fils et il prend beaucoup de plaisir a écouter des histoires racontées par la famille ou divers podcasts qui lui sont plus facilement accessible.

**Comment by marian-m12l** [comment]
Effectivement la conversion peut consommer beaucoup de mémoire, elle n'est absolument pas optimisée car j'avais en tête plutôt des packs d'histoires assez légers. L'options de JVM "Xmx" permet d'allouer plus de mémoire, mais je ne suis pas sûr du comportmeent si la machine en question possède moins de mémoire.

**Comment by ofayau** [comment]
Devrait être corrigé par le merge de #255

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
