### ISSUE TITLE
Impossible de se connecter à la page avec URL

### ISSUE THREAD

**Issue by Christa2582** [marian-m12l/studio#208]
version MacOS 10.11.6
Version JDK 14
Studio-web-ui-0.3.0
J’ai suivi les instructions à la lettre: installation de JDK 14, ouverture de l’exécutable puis accès refusé au moment de mettre l’URL...

Voilà le résultat lors du lancement de l’exécutable dans le terminal:
![BC63E2C9-062B-4214-8563-1952A3C41E23](https://user-images.githubusercontent.com/86292660/122900534-11d44a80-d34d-11eb-9a77-2bb590cd7ca4.jpeg)

Avez-vous une solution? Est-ce un problème de version de Mac OS ?

**Comment by marian-m12l** [comment]
@Christa2582 Merci pour le retour ! Effectivement l'erreur semble liée à la version de macOS et un bug dans le SDK d'Apple : https://github.com/libusb/libusb/issues/836

**Comment by marian-m12l** [comment]
J'ai lu en diagonale, mais a priori ce bug n'affecte que les versions inférieures à 10.12

**Comment by Christa2582** [comment]
Merci, effectivement j’ai téléchargé le dernier OS et j’accède à l’URL.
je vais fermer l’issue.

je vais par contre en ouïr une autre avec un problème de transfert d’un pack déjà dispo (histoire pomme d’api)
