### ISSUE TITLE
Lunii box not responding

### ISSUE THREAD

**Issue by gilles6** [marian-m12l/studio#211]
I made and installed a new package with the v0.3.0 on macos, it worked well and suddenly displayed `ERROR` on the screen. Since then, it's not working anymore : not detected by my computer, no sound, nothing displayed on the screen when turned on. The only thing I can see is the LED lit up (red or green) when the USB cable is plugged in.

I tried to reset it via the Lunii Store, but the reset button is always greyed because the box is not recognized anymore by my computer ? I also tried to unplug/replug the different cables in the box and the sdcard, but without any better result.

Any idea how to fix it ?

**Comment by marian-m12l** [comment]
@gilles6 Do you know if your device is running on the newer firmware? If so, it should still get mounted when plugged into your computer. Did you try with different cables?

**Comment by gilles6** [comment]
Thanks for your reply.

Yes, the device is running on the new firmware which was installed last winter by the Luniistore app on macos. When I plug the box, I don't see anything mounted when running `ls /Volumes`, only `Macintosh HD`. Also, the Disk Utility app doesn't detect the Lunii device either. (the Volume is turned on on the Lunii box in my tests)

I tried with different cables on two different machines (both Apple computers with macos) with the same result.

Besides, I was able to read the sdcard content with an sdcard reader.

**Comment by marian-m12l** [comment]
This sounds more like a hardware problem. The device does nothing when powered on (unplugged), except light the green LED?

**Comment by gilles6** [comment]
No, I get nothing except from the LED when powered on unplugged. No screen light, no sound.

**Comment by gilles6** [comment]
@marian-m12l Thanks for following this issue. I sent the box back to Lunii and received it a few days ago repaired. I will make some checks and come back to you about my assumptions about the failure I had. I hope I won't be able to reproduce it ;-)

**Comment by marian-m12l** [comment]
@gilles6 I hope you'll be fine with your device. Is it the same device which has been repaired, or a replacement one? I fit's ok with you I'll wlose this issue, but feel free to open another one if need be.

**Comment by cylwin** [comment]
Hello,

I have a similar problem. On macos, every time I plug my lunii when studio is launched, my lunii stop responding, and don't start anymore. I have to format the SD card (by removing the sd card and puting it on a sd card reader) and then it's work again.

I can be available if you need to debug something.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
