### ISSUE TITLE
Chargement d’ancien pack d’histoire, problème lié au format d’image

### ISSUE THREAD

**Issue by Christa2582** [marian-m12l/studio#213]
**Describe the bug**
Il s’agit plus d’une remontée d’expérience.
Les anciens pack disponibles présentent des formats d’image non en 320*240 qui empêche l’export vers la Lunii.

**To Reproduce**
1. Bancher la Lunii à l’ordinateur
2. Lancer studio en cliquant sur le fichier correspondant à votre OS
3.  Importer le  fichier zip contenant le pack  d’ histoires 
4. Glisser le fichier vers la gauche
Pas de message d’erreur, mais log indiquant un problème de format d’image incompatible ( erreur conversion format FS... format attendu 320*240

Pour corriger le problème :
1.dézipper et trouver le ou les images qui ne font pas la bonne taille (sous Mac  soit on faiit  «%I» pour voir l’information sur chaque image soit on modifie l’affichage des fichiers pour pouvoir lire l’information en cliquant sur l’image)
2.mettre l’image au bon format ( sur Mac, double clique pour ouvrir l’image. Puis aller dans outil/ modifier format)
3. IL n’est pas possible de re-ziper  le dossier ainsi obtenu, l’import dans studio ne se fera pas.
On contourne cela en suivant les instructions suivantes:
3.1 importer l’ancien pack dans studio
3.2 sélectionner l’icône de modification d’histoire 
3.3 supprimer le/les images de mauvaise taille par les images que vous avait redimenssioner
4. Enregistrer
5. Faites glisser le pack ainsi corriger vers la gauche dans la bibliothéque lunii 

Resultat:
Le log indique que le pack est importé avec succé 
Un populaire de message d’erreur apparaît indiquant que le pack n’a pas pu être importé apparaît
Le pack n’est pas visible dans studio/ bibliothèque Lunii de gauche

cependant le pack est bien disponible dans la Lunii et marche correctement 
En fermant studio et en le relançant le pack apparaît dans la bibliothèque studio/Lunii de gauche
En espérant que ce  retour soit utile à d’autres. Je vous remercie pour le travail accompli qui permet à mon fils d’avoir un regain d’intérêt pour sa boîte Lunii. C’est aussi sympa de pouvoir mettre nos propre histoires sous forme de pack avec nos voix.

**Comment by nassertom** [comment]
Hello,

je vous conseil d'utiliser un script imagemagik c'est plus simple.

idéalement puisque l'on fait déjà du ffmpeg pour le son je pense que ce serait une bonne idée d'automatiser également la conversion des images.

la commande est du type
`onvert /home/thomas/Bureau/assets/059ba06c20da8f4c94d4c49b78f49b89d4925f95.png -resize 320x240^ -extent 320x240 thomas/Bureau/059ba06c20da8f4c94d4c49b78f49b89d4925f95.png
`

**Comment by nassertom** [comment]
pour un traitement en masse : 
`for file in /home/thomas/Bureau/resize/assets/*.png; do convert $file -resize 320x240^ -extent 320x240 $file; done`

**Comment by marian-m12l** [comment]
@Christa2582 @nassertom Merci pour les retours. Concernant le traitement automatique, je préfère qu'il reste limité autant que possible aux conversions de format, et laisser la main à l'utilisateur. N'hésitez pas à compléter le wiki pour y ajouter des commandes utiles de ce type.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
