### ISSUE TITLE
Installed launch script fails

### ISSUE THREAD

**Issue by G4m4** [marian-m12l/studio#217]
**Describe the bug**
This commit: https://github.com/marian-m12l/studio/commit/3ed38da8381f896e6a335f101a4fa533423185df breaks the "installed" version - when launching the script studio_windows it fails with this message:
```
Error: Could not find or load main class io.vertx.core.Launcher
Caused by: java.lang.ClassNotFoundException: io.vertx.core.Launcher
```

**To Reproduce**
1. Sync the depot at tag 0.3.0
2. Cherry-pick 3ed38d
3. mvn clean install
4. launch the script studio_windows from the extracted dist archive

**Expected behavior**
The server should be launched and a browser open localhost

**Logs**
No logs - the server simply cannot be launched.

**Desktop and environment (please complete the following information):**
 - Windows
 - openjdk version "16.0.1" 2021-04-20
 - Apache Maven 3.8.1
 - STUdio application version: 0.3.0 works fine, 0.3.0 plus commit 3ed38d breaks

**Comment by marian-m12l** [comment]
@G4m4 Thanks for the feedback. I don't know much about windows script tbh, the idea was to improve support for paths with spaces. Can you maybe pinpoint which of the two variables causes the error?

**Comment by G4m4** [comment]
Hello and thanks for your work!
I've eventually created a PR (#222 ) that keep the fix without creating issues - I am using it on Windows 10 now.
