### ISSUE TITLE
Updating the version number doesn't change the file name

### ISSUE THREAD

**Issue by misterbenj34** [marian-m12l/studio#22]
The filename in .studio\library\ is not modify when i update the version number in a story.

**Comment by marian-m12l** [comment]
Thanks for the feedback.

Indeed, that is a behaviour that should change. Not sure if it is really that straightforward, though.

Actually, there are 2 cases here
* Either a pack is opened from the local library, and we should expect to save it to that exact same file, whatever its name. That is the current behaviour.
* Or the pack was just created / imported from another archive file, and a filename should be generated when saving to the local library.

Now, which changes should trigger generating a new filename? Only a version increase?

In this case, version number should be made really clear on the local library view. And the version input should probably be more constrained (at least prevent it from being decreased)?

WDYT?

**Comment by misterbenj34** [comment]
I think this is a more global subject about the file management system.
Also, when you change the title on an existing pack, it doesn't change the filename.

My idea is:
- save the pack with the current title and version into a file (overwrite it only if title and version is not changed)
- add a delete option in the local librairy to manage the duplicate
- add the display of version on the local librairy

For now, title and version are only used at first creation of a pack.

**Comment by misterbenj34** [comment]
Also another side effect of this:
- I create a pack "Toto1"
- I upload it to the box and disconnect the box
- I modifiy the pack "Toto1" and rename it to "Toto2" (the filename won't change :) )
- The pack is well displayed at "Toto2" in the local librairy
- When I plug back the box, the pack on the box is been renamed by "Toto2"..

**Comment by marian-m12l** [comment]
> Also another side effect of this:
> 
>     * I create a pack "Toto1"
> 
>     * I upload it to the box and disconnect the box
> 
>     * I modifiy the pack "Toto1" and rename it to "Toto2" (the filename won't change :) )
> 
>     * The pack is well displayed at "Toto2" in the local librairy
> 
>     * When I plug back the box, the pack on the box is been renamed by "Toto2"..


That's right, because the metadata database uses the pack UUID as a key. So if your second pack shares that UUID, it will overwrite metadata. To fix this, UUID should be regenerated when saving to another file.
There may be a tricky case when importing a pack from an external file instead of the library, though...

**Comment by marian-m12l** [comment]
Fixed with release 0.1.3 (filename and UUID may be renewed when name or version is changed)
