### ISSUE TITLE
Erreur lors de l'import vers la Lunii

### ISSUE THREAD

**Issue by charlotterazon** [marian-m12l/studio#223]
**Describe the bug**
Cela me dit échec quand je tente d'ajouter l'histoire créée à ma Lunii...
Est-ce qu'il faut impérativement que le fichier dure moins de 8 minutes ? Ou n'ya tel pas de limite ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.0

**Additional context**

**Comment by marian-m12l** [comment]
@charlotterazon Bonjour. À ma connaissance, il n'y a pas de limite particulière concernant la durée des sons. S'il y a un message d'erreur lors du transfert vers la Lunii, il doit certainement y avoir plus de détails dans le fichier de logs (`studio-latest.log` pour la dernière exécution, ou bien un fichier `.log` incluant la date pour une exécution antérieure). Merci pour ce retour.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
