### ISSUE TITLE
Going back to main menu (to switch pack)

### ISSUE THREAD

**Issue by misterbenj34** [marian-m12l/studio#23]
Hi again,

I've got difficulties on my box, to get back to main menu when I'm navigating on a custom pack.
The only solution to select original pack, is to switch off and switch on the box.

My first node is a stage node defined as "squareone".

Ps: Thanks for your amazing work ! I'd like to help as much as I can (also I'm French)

**Comment by misterbenj34** [comment]
Ok, not an issue.

If you want to go back to the main menu, do not link the home button to anything.

**Comment by marian-m12l** [comment]
Reopening. This should be documented.

**Comment by marian-m12l** [comment]
Fixed with release 0.1.14
