### ISSUE TITLE
 Unsupported device metadata format version: 3

### ISSUE THREAD

**Issue by justori** [marian-m12l/studio#230]
**Describe the bug**
After updating Lunii V1 to the latest FW version 2.7, STUdio started to throw a java exception error
"Unsupported device metadata format version: 3"

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch STudio 
2. Connect Lunii v1
3. See error

**Expected behavior**
I am using Lunii V1 and studio was working correctly and I could load custom stories.
After updating it to v 2.7, i started to get the "Failed to plug device 2.x"

I also have a Lunii V2 with FW 2.19 and it is still working with STUdio. I am not willing to update it fearing not to work with STUdio.

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
See attached
[studio-latest.log](https://github.com/marian-m12l/studio/files/6970367/studio-latest.log)
[studio-latest.log](https://github.com/marian-m12l/studio/files/6970375/studio-latest.log)
[studio-latest.log](https://github.com/marian-m12l/studio/files/6970364/studio-latest.log)

**Desktop and environment (please complete the following information):**
Applicable for MacOS and Windows 10 (supported versions)

**Comment by illuniinati** [comment]
same issue as #227

- V1 and V2 refer the hardware version
- 2.x refer the firmware version (here 2.7)
- metadata version refer the version of the internal structure of metadata file '.md'. The metadata version has updated to 3 with the new firmware 2.7

**Comment by marian-m12l** [comment]
@justori @illuniinati  Should be fixed with the latest nightly build. Let me know how it goes.

**Comment by marian-m12l** [comment]
New version released with support for firmware 2.7 / 2.22 and basic support for night mode: https://github.com/marian-m12l/studio/releases/tag/0.3.1

**Comment by Nuvzz** [comment]
Thank you.
I am responding with my other handle nuvzz instead of justori.

I confirm that the new release fixed the issue for both Lunii old and new devices.

I tested both last night and all work fine.

Many thanks to @marian-m12l for the excellent work and reactivity.
@illuniinati , thank you for your contribution.
