### ISSUE TITLE
Unsupported device metadata format version: 3 lunii

### ISSUE THREAD

**Issue by BDafflon** [marian-m12l/studio#234]
Hi,

New verion of lunii frimeware does not seem to be taken into account by studio.

I've a Error message :
Unsupported device metadata format version: 3 

when a turn on lunii device and an alert in STUdio.

**Comment by illuniinati** [comment]
Same issue #227

**Comment by marian-m12l** [comment]
@BDafflon Should be fixed with the latest nightly build. Let me know how it goes.

**Comment by gael4910** [comment]
Sorry but i can't find where to download this nightly build zip ?

**Comment by marian-m12l** [comment]
@gael4910 The CI builds are available in the [Actions tab](https://github.com/marian-m12l/studio/actions/workflows/maven.yml). Each successful run generates an artifact that you can download.

**Comment by mplu** [comment]
Ça remarche ! Merci tout plein ! (pour tout le taf, j'utilise STUdio depuis le début, c'est juste génial)

**Comment by marian-m12l** [comment]
New version released with support for firmware 2.7 / 2.22 and basic support for night mode: https://github.com/marian-m12l/studio/releases/tag/0.3.1
