### ISSUE TITLE
[HELP] Need a sample workflow to enable night mode

### ISSUE THREAD

**Issue by PxxBxx** [marian-m12l/studio#238]
Sorry to open this issue, It's not for a bug.

I would love to create packs with the night mode feature, but I (yet) did not found the correct way to do that.
Does someone could screenshot a diagram that works with the night mode (ie. the X medias next to the one chosen will be played in cue, without any interaction in between) ?

In the meantime, I just put a whole 45min story... I hope the interactive voices at the end won't wake up my kid tonight ^^

This project is awesome. My kid loves her Lunii, now I also put her favorites audio tracks/albums inside !!!
Lunii SAS made a great but commercial-only product, YOU gave us the way to extend its usage !

**Comment by illuniinati** [comment]
Hi,

It seems the night node feature is coded into the pack structure. Try to run the [0.3.2 snapshot](https://github.com/marian-m12l/studio/suites/3503541000/artifacts/83501797) which allow Night Mode pack creation.
The other point that you need to use the advanced mode with stage and action node.

Hope it can help.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.

**Comment by lrq3000** [comment]
I am also interested in a sample workflow for the night mode, I also tried to tinker with various ways to make it work but so far no luck.
