### ISSUE TITLE
story.json file specifications

### ISSUE THREAD

**Issue by diegantobass** [marian-m12l/studio#246]
Salut,
Aurais-tu les spécifications ou une documentation pour la création du fichier story.json ? J'aimerais automatiser la création d'un pack d'histoire, puis pouvoir la modifier ensuite dans l'interface de Studio.
Merci beaucoup,
dab

for reference and english search : would you have the specifications for the story.json files please? I'd like to automate story pack creation.

**Comment by TheBlusky** [comment]
Egalement intéressé par une réponse ^^
J'ai 500 fichiers que j'aimerai mettre sur le Lunii, et scripter un générateur en python, importable dans l'outil, serait beaucoup plus pratique :-)

**Comment by diegantobass** [comment]
On est dans le même cas, python compris. J'ai commencé le retro-engineering de la structure du json. Les types de noeuds sont déductibles, leurs propriétés pourquoi pas, même si j'aimerais savoir lesquelles sont obligatoires sans devoir les tester une à une.

Mais j'ai surtout une question : quel est le format des uuid, et les contraintes imposées, et par qui (studio ou le firmware) ?

Merci encore pour tout l'excellent boulot !

**Comment by jersou** [comment]
Salut tout le monde !
C’est marrant, je travaillais sur le même sujet dernièrement :D 
J'ai fait un convertisseur de dossier ou flux RSS vers un pack Studio (fichier zip avec le story.json et les assets).

Je viens de le poster sur https://github.com/jersou/studio-pack-generator

C'est fait en Typescript pour [Deno](https://deno.land/), il y a des binaires pour Windows/Linux/MacOs, ou possibilité de le lancer avec deno.

**Comment by jersou** [comment]
Bon, c'est bête, je découvre l'issue https://github.com/marian-m12l/studio/issues/68 dans laquelle on parle de https://github.com/laruche/audiotolunii

J'avais vérifié la partie "THIRD-PARTY APPLICATIONS" du Readme, qui ne parlait pas d'outil du genre, dommage... Après, 
audiotolunii n'a pas exactement les mêmes fonctionnalités non plus, il ne semble pas gérer les menus ni les fichiers audio de titres.

Ça pourrait être utile de mettre à jour le readme avec les outils "liés" à Studio du coup.

**Comment by diegantobass** [comment]
J'étais à peine en train de commencer à penser à... et non, c'est déjà fait EN DOUBLE !
Merci @jersou pour ces deux outils. Ça suffira largement pour l'usage que j'avais en tête : convertir les audiobooks d'Harry Potter en pack pour la Lunii :)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
