### ISSUE TITLE
Add delay before any sound

### ISSUE THREAD

**Issue by misterbenj34** [marian-m12l/studio#25]
I used the website https://ttsmp3.com/text-to-speech/French/ to genereate voice for the menu.
But the box seem to cut a small part of the beginning of each sound/text.

It could be nice to add 500ms-1s of blank sound during the conversion.

**Comment by marian-m12l** [comment]
As of today, I think the app targets tech-savvy users. Creating the assets requires the use of non-trivial software. So I think it is the responsibility of the users to fine-tune the assets.

So for now, I think the need of a "blank" at the beginning (and preferably the end too) should be clearly documented, but not enforced. This would not be trivial to do anyway.

Maybe this should be revisited if someday a sound recorder/editor is introduced directly within the app.

**Comment by marian-m12l** [comment]
BTW I'd recommend Audacity for the creation / edition of audio assets.

**Comment by jin146** [comment]
This can be achieved with ffmpeg.
Some tips here https://video.stackexchange.com/questions/20717/ffmpeg-add-3-seconds-of-black-to-video-head-and-tail

**Comment by marian-m12l** [comment]
> This can be achieved with ffmpeg.
> Some tips here https://video.stackexchange.com/questions/20717/ffmpeg-add-3-seconds-of-black-to-video-head-and-tail
> 
> This way you can edit all your files at once.

Thanks for the tip!

**Comment by itdaboyz** [comment]
FYI, I also used https://ttsmp3.com/text-to-speech/French/ and you can add a delay by adding `<break time=".5s"/>`
I think it's the best TTS to use with this project: free, fast, decent speaking and download as a compatible mp3 without registering.

**Comment by Shasdo** [comment]
Amazon Polly https://aws.amazon.com/fr/polly/ , with a free AWS account is more natural with the "Léa" voice in french. 
You can add break and more in the ssml input field, ex:
<speak><break time="1s"/>Choisis ton personnage</speak>

You can try to tweak the pronounciation by writing in phonetic for better results when the voice sounds a bit odd on certain syllables with the real spelling.

Really easy to use, can convert to mp3 and ogg, but not in 44100Hz but neither ttsmp3.com can.
Anyway I convert everything after with audacity.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
