### ISSUE TITLE
Is version 0.3.1 compatible with Lunii 2.7 firmware?

### ISSUE THREAD

**Issue by lbineau** [marian-m12l/studio#250]
Hello and thank you for this amazing software!

I'd like to know if Studio version 0.3.1 is compatible with Lunii 2.7 firmware?
Sorry for opening an bug for a question, but there was no other type of issue available.

Thank you.

**Comment by jersou** [comment]
it seems ok : https://github.com/marian-m12l/studio/discussions/233#discussioncomment-1186649

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
