### ISSUE TITLE
Personaliser le repertoire de la bibliothèque locale

### ISSUE THREAD

**Issue by kirtapix** [marian-m12l/studio#253]
Bonjour,

Sous windows, je souhaiterai pouvoir choisir le répertoire dans lequel est stocker la bibliothèque.
Le but est de rendre "portable" ma bibliothèque ou de pouvoir la partager facilement à quelqu'un de novice en informatique.
J'ai tenter une modif rapide dans le .bat, mais STUdio ne se lance plus.

Serait-il possible d'ajouter cette feature pour une prochaine version ?

Merci d'avance.

ET bravo pour le travail accompli sur ce super outil !

**Comment by ofayau** [comment]
TL;DR use java system properties : -Dstudio.library and -Dstudio.tmpdir

Bonjour,

Il suffit de passer 2 options au lancement de java.

Ex Linux (dans `studio-linux.sh`) :

`
[...]
export STUDIO_LIB=/var/local/Lunii/library/
export STUDIO_TMP=/tmp/Lunii/
[...]
java -Dstudio.library=$STUDIO_LIB -Dstudio.tmpdir=$STUDIO_TMP -Dvertx.disableDnsResolver=true [...]
`

Ex Windows (dans `studio-windows.bat`) :

`
[...]
set STUDIO_LIB=C:/Lunii/library/
set STUDIO_TMP=C:/tmp/Lunii/
[...]
java -Dstudio.library="%STUDIO_LIB%" -Dstudio.tmpdir="%STUDIO_TMP%" -Dvertx.disableDnsResolver=true [...]
`

Conseil : utiliser / pour le chemins et éviter les caractères spéciaux (dont les espaces) dans les chemins.

**Comment by kirtapix** [comment]
Bonjour et bonne année !

Merci @ofayau pour la réponse.
J'ai encore une petite erreur :
```
studio.metadata.DatabaseMetadataService] [DatabaseMetadataService.java:55]: Missing official metadata database file
java.io.FileNotFoundException: C:\Users\pd715379\.studio\db\official.json (Le chemin d’accès spécifié est introuvable)
```
Est-il possible de spécifier le répertoire de la DB official et nonofficial?

**Comment by ofayau** [comment]
Bonne année!

Tout à fait, avec 2 autres options : `-Dstudio.db.official=` et `-Dstudio.db.unofficial=`

**Comment by kirtapix** [comment]
Bon doit y avoir un truc qui m'échappe, j'ai tout fait comme tu m'as dit dans le .bat : 
```
[...]
set STUDIO_PATH=%~dp0
set DOT_STUDIO="%~dp0/.studio"
set STUDIO_LIB="%DOT_STUDIO%/library"
set STUDIO_TMP="%DOT_STUDIO%/tmp"
set STUDIO_DBOFF="%DOT_STUDIO%/db/official.json"
set STUDIO_DBUNOFF="%DOT_STUDIO%/db/unofficial.json"
[...]
java -Dstudio.library="%STUDIO_LIB%" -Dstudio.tmpdir="%STUDIO_TMP%" -Dstudio.db.unofficial="%STUDIO_DBUNOFF%" -Dstudio.db.official="%STUDIO_DBOFF%" [...] io.vertx.core.Launcher run studio.webui.MainVerticle
```
mais j'ai toujours cette erreur de chargement des dbs, voici un extrait du log : 

```
2022-01-04 16:50:55,522 [WARN ] [studio.metadata.DatabaseMetadataService] [DatabaseMetadataService.java:55]: Missing official metadata database file
java.io.FileNotFoundException: C:\Users\pd715379\.studio\db\official.json (Le chemin d’accès spécifié est introuvable)
[...]
2022-01-04 16:50:55,777 [ERROR] [studio.metadata.DatabaseMetadataService] [DatabaseMetadataService.java:72]: Failed to initialize unofficial metadata database
java.io.FileNotFoundException: D:\Lunii\studio-web\.studio\db\unofficial.json -Dstudio.db.official=D:\Lunii\studio-web\.studio\db\official.json (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)
[...]
```
Je ne connais pas bien le java, du coup j'ai du mal à me sortir de cette impasse.
Merci du coup de main !

**Comment by ofayau** [comment]
Erreur 1 : il faut déclarer au debut pour que les répertoires soient créés.
Erreur 2 : Je suppose qu'il y a trop de guillemet ;-)

Je suis actuellement sous linux, je suppose que ça doit le faire sous Windows (avec peut-être quelques guillemets à rajouter) :

```
@echo off

set STUDIO_PATH=%~dp0

:: -- debut
:: set DOT_STUDIO="%UserProfile%\.studio"
set DOT_STUDIO="%~dp0\.studio"
set STUDIO_LIB=%DOT_STUDIO%/library
set STUDIO_TMP=%DOT_STUDIO%/tmp
set STUDIO_DBOFF=%DOT_STUDIO%/db/official.json
set STUDIO_DBUNOFF=%DOT_STUDIO%/db/unofficial.json
set STUDIO_OPTIONS=-Dstudio.library=%STUDIO_LIB% -Dstudio.tmpdir=%STUDIO_TMP% -Dstudio.db.unofficial=%STUDIO_DBUNOFF% -Dstudio.db.official=%STUDIO_DBOFF%
:: -- fin


:: Make sure the .studio subdirectories exist
if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
if not exist %DOT_STUDIO%\db\* mkdir %DOT_STUDIO%\db
if not exist %DOT_STUDIO%\library\* mkdir %DOT_STUDIO%\library

:: Copy agent and metadata JARs
copy "%STUDIO_PATH%\agent\studio-agent-0.3.1-jar-with-dependencies.jar" %DOT_STUDIO%\agent\studio-agent.jar
copy "%STUDIO_PATH%\agent\studio-metadata-0.3.1-jar-with-dependencies.jar" %DOT_STUDIO%\agent\studio-metadata.jar

:: -- ajout de %STUDIO_OPTIONS%
java %STUDIO_OPTIONS% -Dvertx.disableDnsResolver=true -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp "%STUDIO_PATH%/studio-web-ui-0.3.1.jar";"%STUDIO_PATH%/lib/*";. io.vertx.core.Launcher run studio.webui.MainVerticle
```

**Comment by kirtapix** [comment]
`Erreur 2 : Je suppose qu'il y a trop de guillemet ;-)`

Bonne supposition ! ca marche.

Merci bcp !

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
