### ISSUE TITLE
Can't transfert ZIP PACK to lunii

### ISSUE THREAD

**Issue by epoxsv** [marian-m12l/studio#27]
Hello,
Thanks for your work, it's amazing !
I have an problem when I want to upload an ZIP PACK to my lunii.
Can you help me ?

KG

_

> dÚc. 21, 2019 10:24:05 PM studio.webui.service.LibraryService
> AVERTISSEMENT: Pack to transfer is in archive format. Converting to binary format and storing in temporary file: C:\Users\matth\AppData\Local\Temp\LES_AVENTURES DE ZOE-9c836c24-34c4-4cc1-b9e6-d8646c8d9cf1-v0.zip6233093935764099345.pack
> dÚc. 21, 2019 10:24:05 PM studio.webui.service.LibraryService
> AVERTISSEMENT: Reading archive format pack
> dÚc. 21, 2019 10:24:05 PM studio.webui.service.LibraryService
> AVERTISSEMENT: Uncompressing pack assets
> Exception in thread "Timer-0" java.lang.NoSuchMethodError: java.io.ByteArrayOutputStream.writeBytes([B)V
>         at studio.core.v1.utils.AudioConversion.anyToWave(AudioConversion.java:60)
>         at studio.core.v1.utils.AudioConversion.oggToWave(AudioConversion.java:23)
>         at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:113)
>         at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:133)
>         at studio.webui.api.DeviceController$1.run(DeviceController.java:65)
>         at java.base/java.util.TimerThread.mainLoop(Unknown Source)
>         at java.base/java.util.TimerThread.run(Unknown Source)

_

**Comment by epoxsv** [comment]
Hello,
I have solved my issue by install JRE11 and correct java path.
It it possible to change UUID directly on STUdio ? (it doesnt work if 2 pack have same uuid)

KG

**Comment by marian-m12l** [comment]
Hi,

Thanks for the feedback. Glad you could work it out!
Changing uuid is not possible at the moment, but I'm trying to improve the way files/pack are managed. See #22 for updates on this.
The easiest way at the moment is to open the archive file and change the uuid of the start node in `story.json`.
