### ISSUE TITLE
Erreur de conversion "Failed to convert archive format pack to raw format"

### ISSUE THREAD

**Issue by mymakao** [marian-m12l/studio#294]
Bonjour
J'ai une erreur de conversion quand j'essaye de convertir mon pack en V1. 

"2022-06-24 12:47:51,325 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to raw format
javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format"

Mes fichiers sont actuellement en mp3, certains sont assez longs (pour autant j'ai déjà créé des packs avec des histoires longues sans trop de problèmes).
Comment identifier quel fichier bloque ?
Si le mp2 n'est pas la meilleure option, je peux sans doute effectuer une première conversion pour coller au plus près des formats acceptés, du type... wav ? Y'a-t-il des spécificités que je devrais connaitre pour optimiser au mieux la chose ?
D'avance merci beaucoup !

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
