### ISSUE TITLE
Cannot load pack that contain an error

### ISSUE THREAD

**Issue by cyril42e** [marian-m12l/studio#299]
**Describe the bug**
When there are some kind of errors in the diagram, it is possible to save it without getting any warning, but then it is impossible to edit it ("Failed to load story pack"). There is no error in the terminal. It happens with missing links, but not with missing asset.

**To Reproduce**
1. Create a diagram with errors (for instance missing link between cover and menu)
2. Click on button "Save pack to library"
3. Click on button "Pack library"
4. Click on "Open this story pack in editor"
5. See error

**Expected behavior**
Being able to edit a diagram with error in order to fix it. Would be even better if it was also automatically performing a check upon save, with warning, and upon conversion, with error.

**Screenshots**
-

**Logs**
No console log displayed when the error occurs.

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20220101 Firefox/102.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
