### ISSUE TITLE
On creation, pictures of a pack are shown 9 times

### ISSUE THREAD

**Issue by misterbenj34** [marian-m12l/studio#30]
After creation of my 2nd pack, and after upload on my box, pictures (of options) of a pack are shown 9 times.

My pictures are in 320x240
It also happens on my first pack (the first time)

As a picture is worth a thousand word : https://photos.app.goo.gl/rVDjW1CdzHyGh5cq6

**Comment by marian-m12l** [comment]
Hi,

That's strange!

Can you tell more about the image file you are using? Or share it?

One way I can see something that strange/unpredictable happening is if you're using bitmap files that are not exactly in the format expected by the device. Bitmaps are **not** converted when generating a binary pack (contrary to png/jpeg files) but are embedded "as-is".

**Comment by misterbenj34** [comment]
I used a JPG first, and PNG later, but still same problem.
Here is an example : https://drive.google.com/open?id=1f8CACsIjagv6Rk5efjS-uGSfLDpThNnI
Here is the story.json : https://drive.google.com/open?id=1fbSI3wNhvRPoQ2foy_r5DlARQQ4NoaHo

For my first pack, in version 0.1.2, it happens also the first time.. and it disappear.
I'm gonna try to reproduce it.

**Comment by marian-m12l** [comment]
It seems to be related to the color mode of your PNG file. It seems to be in grayscale. If I switch back to RGB mode (see attachment), conversion happens correctly.

![d88f6e07bb932483d608a5b4717e84f9e8c4f5d1](https://user-images.githubusercontent.com/50991156/71603531-8d40ab80-2b5d-11ea-9db0-91a5e14aeab1.png)

**Comment by marian-m12l** [comment]
This should be documented. Adding the `documentation` label to this issue.
