### ISSUE TITLE
Thumbnail size ?

### ISSUE THREAD

**Issue by gilles6** [marian-m12l/studio#304]
What should be the size of the thumbnail ?
<img width="959" alt="image" src="https://user-images.githubusercontent.com/612946/183645381-42788354-4237-4929-b25e-4a13ac0296ad.png">

**Comment by vpoulailleau** [comment]
I don't find documentation, but the screen is 320x240.

This generator (https://github.com/jersou/studio-pack-generator) produces the good output.

**Comment by vpoulailleau** [comment]
This is also the dimension I can see in official packs.

**Comment by marian-m12l** [comment]
the thumbnail is only used in STUdio, not in the device, Any dimensions are ok but better keep them small as they are displayed in the browser.
