### ISSUE TITLE
probleme studio : echec à la convertion du pack d'histoire

### ISSUE THREAD

**Issue by Vince71390** [marian-m12l/studio#305]
**Describe the bug**
probleme : echec à la convertion du pack d'histoire

**To Reproduce**
1. Go to 'convertir ce pack d'histoires au format brut v1'
2 au bout d'un certain temps, la barre d'état ne bouge pas.
4. See error echec à la convertion du pack d'histoire

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: {"error":{"code":500,"message":"Failed to convert ARCHIVE format pack to RAW format"},"stack":["studio.webui.service.LibraryService.addConvertedRawPackFile(LibraryService.java:195)","studio.webui.service.LibraryService.addConvertedPack(LibraryService.java:151)","studio.webui.api.LibraryController.lambda$apiRouter$4(LibraryController.java:92)","io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)","io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)","io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)","io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)","java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)","java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)","io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)","java.base/java.lang.Thread.run(Thread.java:833)"]}

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.4.2

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
