### ISSUE TITLE
Mutliples spaces in pack title

### ISSUE THREAD

**Issue by misterbenj34** [marian-m12l/studio#31]
Mutliples spaces in pack title are not all replaced by a _
Only the first one

(Are spaces a problem ?)

**Comment by marian-m12l** [comment]
Hi,

I cannot check the code right now but I think this has been fixed recently (maybe in master only). Spaces in filenames should not be a problem, but that's me being overly cautious, the app being on multiple OSes I am wary of the usual "traps" like spaces in file paths...

Anyway, I'll have a look as there may still be a bug here.

**Comment by marian-m12l** [comment]
Fixed in master.

**Comment by marian-m12l** [comment]
Fixed with release 0.1.4
