### ISSUE TITLE
error pour convertir d'un pack déjà converti

### ISSUE THREAD

**Issue by Nyctalope92** [marian-m12l/studio#311]
**Describe the bug**
j'avais déjà copié le pack sur la lunii, donc il était converti une première fois
là j'ai modifié des choses dans les noeuds, et maintenant je souhaite le recopier sur la lunii, mais j'ai cette erreur
j'ai également supprimé l'ancien pack converti dans Studio pour le reconvertir, même erreur

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: {"error":{"code":500,"message":"Failed to convert ARCHIVE format pack to FS format"},"stack":["studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:269)","studio.webui.service.LibraryService.addConvertedPack(LibraryService.java:154)","studio.webui.api.LibraryController.lambda$apiRouter$4(LibraryController.java:92)","io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)","io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)","io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)","io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)","java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)","java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)","io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)","java.base/java.lang.Thread.run(Thread.java:833)"]}

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.4.2

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
