### ISSUE TITLE
Chrome - Out of memory

### ISSUE THREAD

**Issue by cristof56** [marian-m12l/studio#313]
**Describe the bug**
Lors du chargement d'une grosse histoire pour édition, le navigateur Crash avec le message out of memory

**To Reproduce**
Mon histoire contient 65 histoires, c'est un arbre avec une profondeur de 4. Chaque histoire fait environ 20mo.

Google Chrome
Version 104.0.5112.102 (Build officiel) (64 bits)

**Comment by cristof56** [comment]
En utilisant Firefox 102, il semblerait que cela fonctionne. Néanmoins il utilise entre 4 et 5Go de RAM lors du chargement et de l'enregistrement.

**Comment by marian-m12l** [comment]
Merci pour le retour.
En effet l'éditeur est très loin d'être optimisé pour les packs volumineux, puisque les assets sont chargés en mémoire.
