### ISSUE TITLE
Impossible de charger une histoire créée

### ISSUE THREAD

**Issue by WonderAleph** [marian-m12l/studio#336]
**Describe the bug**
Impossible de copier l'histoire sur le Lunii après la validation de l'histoire créée

**To Reproduce**
Drag and drop du pack converti au bon format vers le lunii

**Expected behavior**
Copie effectuée

**Screenshots**

![image](https://user-images.githubusercontent.com/121264923/209233912-64a62b9e-2a89-42ff-9854-b524e3df0df4.png)

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

[studio-latest.log](https://github.com/marian-m12l/studio/files/10290674/studio-latest.log)

**Desktop and environment (please complete the following information):**
 - OS: Win64
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0.1
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**
Mince

**Comment by Yoann-Git** [comment]
Parfois le message apparait mais le transfert s'execute tout de meme.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
