### ISSUE TITLE
fail with studio

### ISSUE THREAD

**Issue by cintakou** [marian-m12l/studio#342]
**Describe the bug**
Hello, I hope you are well, 

Here is my issue with studio,

Each time I try to send a zipfile to import in studio, I got a failure message and can't import or export the zip file.
I attach a pic in this message. 

How can I fix this ? 

Thank you for your reply,
take care

**To Reproduce**
![Capture d’écran 2023-01-17 à 01 01 45](https://user-images.githubusercontent.com/122841026/212782431-90921da7-8c45-4e84-a200-ef7f7c199648.png)

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> e.file(...) is null

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
