### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by RedMinotor** [marian-m12l/studio#343]
**Describe the bug**

Good morning, 

studio refuses to add the library file to Lunii 2. Could you please help me?

**To Reproduce**
1 In editor: create a story with cover node, node menu and story node and save.
2 Click on export package.
3 In the local library: click on the convert icon (V1.x) in the yellow box inside the pack.
4 In local library: click on the convert icon to FS format (V2.x) in the yellow box inside the pack.
5 Drag one of the two newly created V1 or V2 files to the Lunii library below Device
6 Error appears 

**Expected behavior**

Normally the case of the two files must be able to be added to the Lunii but it is not.

**Screenshots**

![Capture d’écran 2023-01-17 à 16 21 38](https://user-images.githubusercontent.com/122894596/212938354-d797d3ea-2d34-4dc7-ab4d-146ba985b64f.png)

**Logs**
no

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
