### ISSUE TITLE
problem with install on windows 10

### ISSUE THREAD

**Issue by gael4910** [marian-m12l/studio#35]
Hello, im sorry but i can't get "Studio story teller" working on my win10 computer. I updated Java JRE and JDK but "studio-windows.bat" keep giving me those errors :

***************************************
JRE
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
***************************************
JDK
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)_**
***************************************

**C:\studio-web-ui-0.1.11-dist\studio-web-ui-0.1.11>studio-windows.bat**
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
[DEBUG] 2020-02-24 11:32:54,520 InternalLoggerFactory.newDefaultFactory() - Using SLF4J as the default logging framework
[DEBUG] 2020-02-24 11:32:54,523 ResourceLeakDetector.<clinit>() - -Dio.netty.leakDetection.level: simple
[DEBUG] 2020-02-24 11:32:54,524 ResourceLeakDetector.<clinit>() - -Dio.netty.leakDetection.targetRecords: 4
[DEBUG] 2020-02-24 11:32:54,537 MultithreadEventLoopGroup.<clinit>() - -Dio.netty.eventLoopThreads: 24
[DEBUG] 2020-02-24 11:32:54,552 NioEventLoop.<clinit>() - -Dio.netty.noKeySetOptimization: false
[DEBUG] 2020-02-24 11:32:54,553 NioEventLoop.<clinit>() - -Dio.netty.selectorAutoRebuildThreshold: 512
[DEBUG] 2020-02-24 11:32:54,565 PlatformDependent.isWindows0() - Platform: Windows
[DEBUG] 2020-02-24 11:32:54,567 PlatformDependent0.explicitNoUnsafeCause0() - -Dio.netty.noUnsafe: false
[DEBUG] 2020-02-24 11:32:54,567 PlatformDependent0.javaVersion0() - Java version: 8
[DEBUG] 2020-02-24 11:32:54,568 PlatformDependent0.<clinit>() - sun.misc.Unsafe.theUnsafe: available
[DEBUG] 2020-02-24 11:32:54,569 PlatformDependent0.<clinit>() - sun.misc.Unsafe.copyMemory: available
[DEBUG] 2020-02-24 11:32:54,569 PlatformDependent0.<clinit>() - java.nio.Buffer.address: available
[DEBUG] 2020-02-24 11:32:54,570 PlatformDependent0.<clinit>() - direct buffer constructor: available
[DEBUG] 2020-02-24 11:32:54,570 PlatformDependent0.<clinit>() - java.nio.Bits.unaligned: available, true
[DEBUG] 2020-02-24 11:32:54,570 PlatformDependent0.<clinit>() - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
[DEBUG] 2020-02-24 11:32:54,571 PlatformDependent0.<clinit>() - java.nio.DirectByteBuffer.<init>(long, int): available
[DEBUG] 2020-02-24 11:32:54,572 PlatformDependent.unsafeUnavailabilityCause0() - sun.misc.Unsafe: available
[DEBUG] 2020-02-24 11:32:54,572 PlatformDependent.tmpdir0() - -Dio.netty.tmpdir: C:\Users\gael\AppData\Local\Temp (java.io.tmpdir)
[DEBUG] 2020-02-24 11:32:54,574 PlatformDependent.bitMode0() - -Dio.netty.bitMode: 64 (sun.arch.data.model)
[DEBUG] 2020-02-24 11:32:54,575 PlatformDependent.<clinit>() - -Dio.netty.maxDirectMemory: 3806855168 bytes
[DEBUG] 2020-02-24 11:32:54,575 PlatformDependent.<clinit>() - -Dio.netty.uninitializedArrayAllocationThreshold: -1
[DEBUG] 2020-02-24 11:32:54,577 CleanerJava6.<clinit>() - java.nio.ByteBuffer.cleaner(): available
[DEBUG] 2020-02-24 11:32:54,577 PlatformDependent.<clinit>() - -Dio.netty.noPreferDirect: false
[DEBUG] 2020-02-24 11:32:54,582 PlatformDependent.<clinit>() - org.jctools-core.MpscChunkedArrayQueue: available
[DEBUG] 2020-02-24 11:32:54,762 DefaultDnsServerAddressStreamProvider.<clinit>() - Default DNS servers: [/192.168.1.254:53, /10.49.27.6:53, /10.49.27.7:53] (sun.net.dns.ResolverConfiguration)
fÚvr. 24, 2020 11:32:54 AM io.vertx.core.impl.launcher.commands.RunCommand
GRAVE: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:242)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:215)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:182)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:155)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:144)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)

2020-02-24 11:32:54,819 vert.x-internal-blocking-0 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

Could you help me please ?

**Comment by marian-m12l** [comment]
Hi,

It looks like your JRE is still Java 8 (as evidenced by the error message mentioning class file versions support up to 52.0). Try updating to JRE 11 or higher. I rarely use Windows, so not sure how it handles different versions of Java, but maybe you have several JREs/JDKs installed and you could fix the default one with environment variables ?

Please, don't be sorry to ask for help or report issues. I'm glad to know new people keep installing and using it :-) Also, as I mentioned, there may be issues specific to Windows (or the combination with certain browsers) that I am not aware of, if you find any please feel free to report them so it can get fixed for everyone.

**Comment by gael4910** [comment]
Thanks for your quick answer ! I can't find better than JRE 8 on windows... https://www.java.com/fr/download/. Seems that Version 8 Update 241 is the latest (14/01/2020).
I succeeded in installing studio story teller on ubuntu 18 with virtualbox. I tried to edit a quick "test" story, but I don't understand how to transfer it on my children lunii ?

**Comment by marian-m12l** [comment]
That's strange... Anyway, JRE is included in JDK, so you should be able to uninstall Java 8 and keep your recent JDK.
I did not do any tests from within a VM, although theoretically it could work. The app uses Lunii's official USB driver to transfer story packs, so you'd need to make your USB ports available to the VM. Also, you'll need to have Luniistore installed in the VM as well. When the Lunii is plugged, the app detects it and shows the device's installed packs. From there, you can drag-and-drop your custom story pack to transfer.

**Comment by gael4910** [comment]
Java is not running after unistalling jre on windows, but whatever... I'll try to install luniistore on ubuntu. My first goal was to user lunii as a simple mp3 reader (songs or stories). It seems that a story architecture is necessary on story packages.

**Comment by marian-m12l** [comment]
When you add a story pack, it is added to the "main menu" that is played by the Lunii on startup. Depending on what you want to achieve, you could either create a really simple pack for each mp3 file (basically the cover node for pack selection and a story node with your song/story), or a single pack with an inner menu to select a song/story. I really need to take the time to write (at least some basic) usage documentation...
Be aware that all audio files are converted to raw PCM / wave to be transferred, though, so it can quickly add up.
Let me know if you get it to work (or not).

**Comment by gael4910** [comment]
Do you know how this kind of pack with songs are made  ? https://www.lunii.fr/catalogue/pack/product?packId=-KorU5auiZrarMaQvb_V
I firstly thought your program could open and modify official packs, but it is not possible, right ?

**Comment by marian-m12l** [comment]
You're right, transfer is disabled for official packs, so as to not "compete" with Luniistore, and to not encourage copying and sharing of licensed content.

You cannot open and modify official packs, but you can use the example pack as a good start. If you take enough time and look at the example pack, I think designing a simple story pack is not too hard (hopefully). I don't have any pack of songs, so I don't know how you navigate in these. My guess would be a simple structure like this :

```

cover node                         menu node (with list of songs)
----------                         ------------------------------
(story pack image)        ====>    (option 1 (image+audio))         ====>    story node (1st song, audio only)
(story pack name/audio)            (option 2 (image+audio))         ====>    story node (2nd song, audio only)

```

**Comment by gael4910** [comment]
I just uploaded my first pack with 2 songs and 1 story (read by text to speech engine), it works fine except the 2 songs, probably wrong format so it read the sample speech instead. My song files are stereo MP3, 44100Hz, 32bits, 128kbits/s

**Comment by marian-m12l** [comment]
Thanks for the feedback!
That's strange, MP3 and OGG files are expected to be 44KHz before conversion. I'll need to have a look at it. Can you share the files that did not work?

**Comment by gael4910** [comment]
Here are the 2 mp3 files I had to convert to 32000hz :
http://78.236.219.170:63631/share/Q5kftO7F1ViLPcqo/mp3.zip

**Comment by marian-m12l** [comment]
see #36 to track audio conversion failure issue
