### ISSUE TITLE
Problème chargement histoire et bibliothèque

### ISSUE THREAD

**Issue by Windoxs** [marian-m12l/studio#356]
Bonjour,
de mon côté, lors du chargement d'un fichier histoire en ".ZIP" j'ai un problème de mise à jour de la bibliothèque.
L'histoire n'apparait pas sur la boite à histoire.

Message : Caused by: java.nio.charset.MalformedInputException: Input length = 1

Merci d'avance pour votre aide,
Cordialement

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
