### ISSUE TITLE
Audio conversion from 44KHz MP3 file not working (on Windows ?)

### ISSUE THREAD

**Issue by marian-m12l** [marian-m12l/studio#36]
see #35

**Comment by marian-m12l** [comment]
@gael4910 Tried your MP3 files on the latest version on Windows 10, and conversion looks OK for me. Did you get that problem again?

**Comment by gael4910** [comment]
Thank You ! I didnt try again, i was using a virtual Ubuntu.

Gael

**Comment by marian-m12l** [comment]
You're welcome, but I actually didn't do any fix. I just finally took the time to test this and couldn't reproduce the problem. The thing is, I gave it a quick try when you shared your files, and I cannot remember for the life of me whether I had the problem or not back then...
