### ISSUE TITLE
échec de la récupération des packs d'histoire de la bibliothèque

### ISSUE THREAD

**Issue by pc2-cer** [marian-m12l/studio#363]
* la plateforme STUdio web a bien fonctionné pendant 2 jours et puis stop, impossible de charger des histoires pour les installer dans ma lunii.
* Des que la plateforme s'ouvre, je reçois un message d'erreur "échec de la récupération des packs d'histoire de la bibliothèque".
* Je suis sur Mac, j'ai suivi la procédure indiquée en installant toutes les ressources les plus à jour (application lunii+oracle+studioweb)
![doc1](https://user-images.githubusercontent.com/130933103/232341160-08c43ec4-bbfd-4db7-94f3-0c0261560aa6.png)
![doc2](https://user-images.githubusercontent.com/130933103/232341163-f81ff94d-c985-42f5-af04-ae2c6fd7a232.png)

**Comment by marian-m12l** [comment]
Certainement une archive corrompue dans la bibliothèque.
