### ISSUE TITLE
Unable to scroll in Editor

### ISSUE THREAD

**Issue by laverdanny** [marian-m12l/studio#364]
Almost any official story are very large

The only way I've found to see items out of screen is to zoom out, but it is the impossible to read and even to precisely click on it

Is there a way to add horizontal and vertical scroll sliders ?

Regards

**Desktop and environment (please complete the following information):**
 - Windows 10 64
 - Brave Browser up to date
 - Java latest
 - Maven ???
 - STUdio 0.3.1

**Comment by marian-m12l** [comment]
you should be able to move the canvas with ctrl+drag

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.

**Comment by laverdanny** [comment]
Thanks
