### ISSUE TITLE
Problèmes avec des packs officiels

### ISSUE THREAD

**Issue by seqn63** [marian-m12l/studio#365]
**Describe the bug**
J'ai récupéré des packs que j'ai importé dans la bibliothèque, or ces packs présentent un bandeau vert "officiel"
![ok](https://user-images.githubusercontent.com/131195696/232864941-0463369f-7308-4e01-864b-09ef9dc95e84.jpg)
. Impossible de le téléverser dans ma lunii. Est-ce normal ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

**Desktop and environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version [e.g. 0.1.11]

**Additional context**

**Comment by vpoulailleau** [comment]
https://github.com/marian-m12l/studio/issues/241#issuecomment-913138153

Ça semble mal parti !

**Comment by MenardCOGIP** [comment]
J'ai le même problème 😕

**Comment by bac88** [comment]
bonjour, une solution ?

**Comment by marian-m12l** [comment]
Oui c'est tout à fait normal :)
