### ISSUE TITLE
Web UI: dragging is disabled once text is edited.

### ISSUE THREAD

**Issue by anoril1979** [marian-m12l/studio#37]
Browser: latest Chrome & Firefox.

=== Explanation
When in editor mode, if I edit a text from a node (option name, title...), then I'm no more able to move the nodes or link them on the graph layout. 

=== Reproduction steps:
1/ Create a simple story with some nodes.
2/ Place the nodes arround on the graph editor
3/ Start editing a node name or option title
4/ Validate the edition by clicking on the graph background or by pressing "enter" key
5/ Try to move a node arround.
==> Nodes are stuck. Impossible to me to move them or to create links between them from dots.

=== Workarround
1/ Save your graph by pressing the floppy-disk icon (to be sure not to loose anything)
2/ Click the "Library" icon on the top right bar to be moved to the Library View
3/ Click the "edit" icon on the Pack you were working on
==> You are back onto the Editor View and nodes are now movable again.
Note: just clicking library then editor icons from the top panel has no effect. I guess this is due to a simple display swap when the "edit" icon on the Pack refresh in some way the editor layout...

Regards,

**Comment by marian-m12l** [comment]
The problem should now be fixed on `master` (not yet released). However I think it should only have been a problem when pressing enter or escape, not when clicking outside the text box. Can you give it a try?
Thanks for reporting :-)

**Comment by anoril1979** [comment]
You are right: no problem when click outside the node. I'm too used to press enter when typing... :)

**Comment by marian-m12l** [comment]
fixed with release 0.1.12
