### ISSUE TITLE
problem with story pack conversion...why? Because of new Lunii version??

### ISSUE THREAD

**Issue by clelong** [marian-m12l/studio#377]
**Describe the bug**
When droping a story pack in the left part of the studio, to put it on my lunii, I have 2 error messages 👍 "Echex de la conversion du pack d'histoires dans la bibliotheques" and "Echec de l ajout du pack à l appareil"

**To Reproduce**
Open Studio dev lunii
drop an existing pack on the left side (where we have the stories of the lunii)
the error appears

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Failed to fetch

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.3.1

**Additional context**

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
