### ISSUE TITLE
character font

### ISSUE THREAD

**Issue by T1nd4** [marian-m12l/studio#38]
Hi,

I have problems displaying accents.
When webserv shows my official packs, named are broken.
ex : 
- SorciÃ¨res  (Sorcières)
- Lâ€™Anniversaire volÃ© (L'anniversaire volé)

Thanks

**Comment by marian-m12l** [comment]
Hi,

Thanks for the feedback! Is this the same as #29 ?

**Comment by T1nd4** [comment]
Hi,
I think we all have the same prob.

**Comment by marian-m12l** [comment]
Duplicate of #29
