### ISSUE TITLE
Bug à l'installation via Terminal

### ISSUE THREAD

**Issue by Couchey** [marian-m12l/studio#380]
Hello tout le monde,

Je suis le process pour enrichir la Lunii. 
Java OK.
Brew : je pense que c'est bon.

👇👇👇👇
<img width="752" alt="Capture d’écran 2023-07-13 à 13 32 21 copie" src="https://github.com/marian-m12l/studio/assets/139460922/a460fe57-32ed-482e-80fb-6a8f20d18343">

Je suis sur MacOs Ventura 13.3.

Qd je lance /studio-macos.sh via le terminal, cela n'ouvre pas la page localhost.
voici ce que cela donne.

👇👇👇👇👇
<img width="654" alt="Capture d’écran 2023-07-13 à 13 27 36" src="https://github.com/marian-m12l/studio/assets/139460922/f5201782-1cd2-4180-b6d1-ea9a95804630">

Je vous remercie 
A vous lire !

**Comment by marian-m12l** [comment]
Duplicate of #244
