### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by eldudi** [marian-m12l/studio#384]
Hello everyone. I use version 3.1
That's been a while I am using this app and that worked pretty well so far. 
I am currently facing an issue : I have added some nodes with new stories but we can hear nothing when trying to listen from the lunii. What is strange is that the format are good (mp3) and when I listen the samples on the editor, the stories work well ! 
And it's not an issue of device because the other stories are working well. I just have a few audio stories with this issue. 
Has someone experienced the same ?
![2023-08-10_16h25_26](https://github.com/marian-m12l/studio/assets/84008240/a3dbafb6-8afa-4c1a-803d-53d073eeae84)

**Comment by marian-m12l** [comment]
Thanks for your feedback.
Can you spot any difference in your mp3 files encoding compared to other story packs you made? STUdio won't reencode if it thinks the mp3 files are correct for the lunii, but there may be unchecked corner cases. An alternative is to use non-mp3 audio files and let STUdio reencode them.

**Comment by eldudi** [comment]
Thanks for your reply. I tried your alternative and it worked! I have re encoded the files in .wav and let the studio deal with it. It worked! Thanks for your work!

**Comment by marian-m12l** [comment]
Thanks for the feedback!
