### ISSUE TITLE
Detailed video

### ISSUE THREAD

**Issue by Worlgun** [marian-m12l/studio#39]
198/5000
Hello, I allow myself to disturb you. I'm completely sucked. Could you please. make a video. To show how to do it. Thank you very much in advance. 

Worlgun

**Comment by marian-m12l** [comment]
Hi,
I'm not planning on making a video. I'd prefer to improve documentation. Can you be more specific about what bothers you? Where are you at and what are you missing? Did you try to play with the sample story?
Thanks for your feedback!

**Comment by Worlgun** [comment]
Thank you for your reply.

I'm using windows 10

In this case I do not understand how I should apply the file.
like this: .studio
or
like this: $ DOT_STUDIO

---------------------------------------------------------- ----------
For Token I also don't understand what needs to be done.

may be a picture of the address to be copied to the browser? Because after several tests I can't do it. and a picture of how the file should look when finished.

---------------------------------------------------------- -----------

If I use the distribution archive, it doesn't work.

I have an error:

""
Thanks for your help.

**Comment by marian-m12l** [comment]
Hi,

To answer your questions:
- The folder should be name `.studio` (`$DOT_STUDIO` is just a way to describe every step in a way that is cross-platform)
- The token must be recovered from a Luniistore file (`.local.properties`) **soon** after logging in. On Windows, it would be located in `%UserProfile%\AppData\Roaming\Luniitheque`. It should contain a row starting with `tokens=` followed by a JSON document. Within the JSON document, look for the key `tokens.access_tokens.data.firebase` (meaning the key `firebase` within the object `data` within the object `access_tokens` within the object `tokens`) which should contain a JWT token. This is the token you must use in place of the `TOKEN` placeholder
- Did you try running studio-windows.bat from within the folder? (i.e. "cd" into `C:\Users\Newte.studio\` beforehand)

Please feel free to ask any question or report missing elements in the documentation. I'll try to improve it.

**Comment by Worlgun** [comment]
What should i take here plz

local.properties :   

token={"firebase"\:"eyJhbGciOiJSUzI1NiIsImtpZCI6IjA0NjUxMTM5ZDg4NzUyYjY0OTM0MjUzNGE2YjRhMDUxMjVkNzhmYmIiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiR1VFU1QiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHVuaWktZGF0YS1wcm9kIiwiYXVkIjoibHVuaWktZGF0YS1wcm9kIiwiYXV0aF90aW1lIjoxNTc1ODY5OTkzLCJ1c2VyX2lkIjoiR3Vlc3QiLCJzdWIiOiJHdWVzdCIsImlhdCI6MTU3NTg2OTk5MywiZXhwIjoxNTc1ODczNTkzLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.RfU1EaHnkrreTh735CWWxERFQsvU9g4wbVLsZjJpnV-bsmw2eUGurzkjyS73Y3bEFDTuOxd01ZEHorNkwHuNMRUB8ukbFBWhZtYfAuM0OHGzX6ujQNk_-zOYNyK__fy4KPHSEA4wRW46zNZrdwiYxzXo4be3wGcYbBgeFiTaU0S5bcDeTkz_o-Q9IkpXdk7alIzEx6fbVWIJ3FeG9JL5MFoXaIMSifUxr4fbXqUCCoPKfj_S4WxG87tDILECg1OLw5T1J0UcMqCD_YDFxf6HaND5tyfMOIbPodCoKTXmHB9mfJaSo8cpP8dBPsbxkixa3iAl5cbJdqqRSfxXdmkyiQ","server"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTU3NTg2OTk5MywiZXhwIjoxNTc1ODczNTkzLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1vaTR5dkBsdW5paS1kYXRhLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay1vaTR5dkBsdW5paS1kYXRhLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiJHdWVzdCIsImNsYWltcyI6eyJyb2xlIjoiR1VFU1QifX0.aYY6oCU6h_JvJH6cQ3mBb861eRs-0oatoRL9oAWwZFogt87M9XmCBvMA1Wr-fVQrjwJnrPSspAa870oxKFk3x7xTOODI9DCiAoqFZ5w7PTD8IfbQoglnwiY4sD-jHT4B1PVBZxbfgaap5gV_2hATrufdqHfSo2uGfI7RhWx6l4aRDLxIxWMIALaKdVBsucBFQWajtOSHsnzTSVQT-XDivfCHL2eRsV20uPaWS5DEmpdqccbXjxssOHfWRu8YknxgcFw1dB3ekE7tXwxnxFML-OUdxURjAWBDLOoN-2yUt0wOmccLy-TI2e58ZWC48It9dClXn1VTJwDoEsYey2jxSQ"}


------------------------------------------------------------------------------------------

tokens={"tokens"\:{"access_tokens"\:{"data"\:{"firebase"\:"eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHVuaWktZGF0YS1wcm9kIiwiYXVkIjoibHVuaWktZGF0YS1wcm9kIiwiYXV0aF90aW1lIjoxNTg1NzQxODIyLCJ1c2VyX2lkIjoiLUx1c0piZ2NiQWFEMGpHQnNtTkMiLCJzdWIiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.fOcI7UvY6Fwzbg_PkMyJUpEHaeNIlPmcza7OqLryDJruVkr0umgwXCup9pT1MVODWzlLqaoOxqyy8Cjtf7zarIhuDGnAn0JjPBJ-073a36SuarD_eKhG9oZiN-kkPOV4y3KDlWlR6fhcSio9q5IuAB-6nn1gN_tfeVCIkJi4o_yv66ovv1TPkU4_K2bzZ0sxcXj15pgcM8IOnxrF67nhiuevIsdb2m1Iby_txtsk37Rd8dOAV7qDYXMfNM0q9zm77m5VHOU6Uc4GGF9g8DR2c16xlESdjDgm1UQPXiFTSyL4opx3KETpSG027TSi-BE7eIT5WEgMP92x5z9LvuQJyg","server"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1vaTR5dkBsdW5paS1kYXRhLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay1vaTR5dkBsdW5paS1kYXRhLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImNsYWltcyI6eyJyb2xlIjoiQ1VTVE9NRVIifX0.FjFi4D-ZMTNKbXOonqtyT2YnUrwLcWPMIbCteqrlqJOvfN56qumvCmvUJFKrm4aa3TiyN3Yud7xdu99Des_tJAkFUtgWzebfj2ktE3zgtewKYHpDPFZXIB5Wvlw7g2cwWFjeAyFFLJzCdaV5vQz5T4m1N0dRziTtgbQPtaLV1XsNs0Oa6Lp7CJ-G9aWYK3WcNaKuDgKHh6QF2aJXuy_ksX62Pa52qsygymUshpUTD_-l29u4M78kIu60rn2vHLbiEhCY0v9rRLZts5lVV-mZGlyTbx_xtlUjgfBf6biar2XJXjI8pMGQ6GnphsQDSA4UjTSDZ5rziu8g_HOsWaMzig"},"user"\:{"firebase"\:"eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHVuaWktdXNlci1wcm9kIiwiYXVkIjoibHVuaWktdXNlci1wcm9kIiwiYXV0aF90aW1lIjoxNTg1NzQxODIyLCJ1c2VyX2lkIjoiLUx1c0piZ2NiQWFEMGpHQnNtTkMiLCJzdWIiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.OfRe1k26m_YdH40a34IF1uEPYE4tFKHuNgpVAiTmIsn7NWVs_Gm35TkXrfKCT00U6GXs9L0sgPQKPhvhDjmVkAIxLi6wKMs-Ct8FU4SKyxY8sPPF3XyfQn2ZqELwTmmgHK0rmikmGGhW976dJuZ6ItQBRCmGbCgVNiJU-U7rJOgFnVQGCr4-rvH5mhlPhiyQCjII4aoh0wQiwhcFIJ-vcvGeO1YVT8vlb0OdAqdE_Kk4mGktQhIkV7JUXiankeOt3NDwZ27JPXIuqo6HDmcX-rygRfQXprVcp-pT9t0cr0PZKxyNRcrLKfE9X8E5JyWH6a12PUhaQ1r2k3bJ4ZUjgQ","server"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay11a3BmakBsdW5paS11c2VyLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay11a3BmakBsdW5paS11c2VyLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImNsYWltcyI6eyJyb2xlIjoiQ1VTVE9NRVIifX0.ujpjbMvvIQ8rYkLa4YFyfkUPRkXfhlXmkg1y6mAjU3EsZbrtYfujz1dUCtUZNqrSB138OXnQHEoQD2bu0weB3xUUEHkr7peXbXMeZ0TUcZly-Y_b88nxZ-BPwykJZlGqKaNrNLT5m6AIfTECItNGzuvR43hgXScfx9XIqWiECFgrTyvbwdypWDuyNguOdIK-qeca4knhIDHMpK1TdUZ2-U6Fffls7d3ZKkyhWLW0jgsdWQh6KJyMEoN5ppr9hLbjeMjBQxwRVlfg-WpB8TqWkECQb7adMRQO5LkwDRq9RXmze45yMbEBqHw3FRqf4JvjW_wHExKuiarWI6xr_q5uig"},"billing"\:{"firebase"\:"eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHVuaWktYmlsbGluZy1wcm9kIiwiYXVkIjoibHVuaWktYmlsbGluZy1wcm9kIiwiYXV0aF90aW1lIjoxNTg1NzQxODIyLCJ1c2VyX2lkIjoiLUx1c0piZ2NiQWFEMGpHQnNtTkMiLCJzdWIiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.E3sBEJs7QuStxqzvZjunH2IzzgQAGg6Gl3Qs04oMVUt3mBeOkoFkzh8gdlXywHVLx5P_lHIU5FmGoB1EKa5xtVyffYGExpseVbsMBq-51h5Uqf_yMBf_JLuQkdOCblkXLbwqxo9QwyGKXU20DDuegQbxLrY0OefaFIJ947PCA_UKMF1SE9z0sKZBthx5PD2uOXUWxhkl2-BKUnG73NZDLoIbzXMwYOg5XjpK6L0wi1PZ9SoiIGN8st3ikS668xXuo_Q5prrh1XNO5meMyTvZ6ndu3BC4dJ-Ie-svZqxJL_nAVm6X3h9EPjJvC1xvpSV0rTEfUistxWl36E77ZOWuIA","server"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay04MndpeEBsdW5paS1iaWxsaW5nLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay04MndpeEBsdW5paS1iaWxsaW5nLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImNsYWltcyI6eyJyb2xlIjoiQ1VTVE9NRVIifX0.Yx2ruqF7W6EImH34SBVhuwvAdHGShDaWbNiufJ0mIIpx6b2usLEazw9uPyOrGVPO4ej5_uWSChh5OOgOMhZDjiiveaWVQNftFtqlPBDf-A1lcgSnzYbUHgOFpfIl55CPdVHulrkeVSMG-sIapip_SrxaIGIny6oG7W2zrzr_AbTE2a9Apx9eT0fE-_68tmLC1C-xHfYL-pHqDqY-wYu8_fcO5-KYevqlOcIaO80BwVMhdPSfLlivsgeDeXjIB77UxMq1SFqkcCWf3KWY-tx5-H2Rfg-DFziydgfTnfzci2psmxLJiP7hT4Rjcd8kkP9wSlNLflRyc6n3oV22EbJ1KQ"},"payment"\:{"firebase"\:"eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYTczOGUyMWI5MWNlMjRmNDM0ODBmZTZmZWU0MjU4Yzg0ZGI0YzUiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHVuaWktcGF5bWVudC1wcm9kIiwiYXVkIjoibHVuaWktcGF5bWVudC1wcm9kIiwiYXV0aF90aW1lIjoxNTg1NzQxODIyLCJ1c2VyX2lkIjoiLUx1c0piZ2NiQWFEMGpHQnNtTkMiLCJzdWIiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.AQ4qBiJ5qM1maAMmIWDps4CZErnSt9ODymm6TtapXZRkJQ9F-hjssnnpqr1LB7wwequVAyIx8hZE40Egplh1L2T0h0xroy1cHqjj832zfbqsY09YN0JpSTcQ8rI5Xe_xUXVPzHBt6n_kCdSMZ6e48BBLQqSsMtq3P6ZL8TuMa6naePZvWaCPKYBPfcpP0h397P6gx8YVplxxOj8kkR86F6HrrE4V-oQpwXEFgkAb1-XntOcpoceqWNZBbBgSYK77bId9qDHcxmTB-qqVvKa0Gn8ESiEqyqPi6OCVwh0Irrg-1KktxYMEizkWaRkPpfWW8RCy3aoxzESNBSF1B9vA4A","server"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTU4NTc0MTgyMiwiZXhwIjoxNTg1NzQ1NDIyLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay11aHg5YkBsdW5paS1wYXltZW50LXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay11aHg5YkBsdW5paS1wYXltZW50LXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImNsYWltcyI6eyJyb2xlIjoiQ1VTVE9NRVIifX0.3YOENbQtXn8unO64hCtfaKdqD-gYS35ZnFjvC4T6TR69NqYcVvhnzgf_l2RRuLkuEjKBjComt4573--Yu5XVx-SmmBxrxDUMptPlk1WskVMIXjQRk6zq9M2uOPN998S3S5z7eMvc4T3tQbXGpfSyZ5pJtCuqmkTB631xM6ISDmrttCttts_HWMPwDvxbZ9TVkyU4MDQs_qD-kQYwAtAt_5oOjUzQiYEigLOQwI1dy1SuBs8Jpelbr1hZW0AiZ02GR9dzdomufiA6uleI7EH8kbfNWG8tiHupaLp1VV_GLqfaSUAMWGJyNl8WQKXj-A7As0j1BNDmGebXZhjIXSj9XA"}},"refresh_token"\:{"lunii_site"\:null,"luniistore_desktop"\:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiItTHVzSmJnY2JBYUQwakdCc21OQyIsImFwcGxpY2F0aW9uIjoibHVuaWlzdG9yZV9kZXNrdG9wIiwiaWF0IjoxNTg1NzQxODIyLCJpc3MiOiJMdW5paSBTQVMiLCJzdWIiOiItTHVzSmJnY2JBYUQwakdCc21OQyJ9.jPFVgIhIfk4f6orc90ndtikMP1nS2I4tKgZd3VLi1JX0QmgVgkJFN8RtZPsyfCqLBJQnNv3w3SQhIHIx24gkToqpGC29MIqwX05Sp8uiPsefKC-WWdTz5XcoCWNF_RyIW8BpbFJIVu4vIQpsPdIAQnJw48rpQuxhCQz7Zl3ty0vefBa5M94jcGMm-QPAv0jFBn_HFpv50xzrVUjJYODhGw5dChYOStCbPIW3DlA0humL69cBQMBT5Y5Cfbq-Uv9Uq00UsdPXYK3COgywn7Q6WJZW7Ahw7y8lZsc24scp9cPL04BsouNhM2ChcDLXOMSToYMhbk5o9DCbEPFH66S2WQ"}},"user_id"\:"-LusJbgcbAaD0jGBsmNC","password_reset"\:false}

**Comment by marian-m12l** [comment]
The first token in "tokens" is the right one. Starting at `eyJhbGciOiJSU` and ending at `5z9LvuQJyg`. It's valid for 1 hour.
I'm removing your tokens, though, as they could be used to impersonate your account.

**Comment by Worlgun** [comment]
Thank you very much.

So I take the token. I create a .json file.
and I paste this: url -v -X GET https://lunii-data-prod.firebaseio.com/packs.json?auth= (here my I paste my token). and I save it?

**Comment by marian-m12l** [comment]
Sorry I forgot that part.

You should use the token to fetch the URL (in a browser or with curl): https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN (where you replace `TOKEN` with your JWT token)

The file we're fetching is a JSON file, which looks like this:
```
{
  "-KAewGUfvRk5JMf9gFjS": {
    "age_max": -1,
    "age_min": 3,
    "authors": {
      "-LTYprxFW53trxwLmXGP": {
        "image_url": "/public/images/avatars/avatar5.png",
        "name": "Charles Deinausard"
      },
      "-LTYprxFW53trxwLmXGS": {
        "image_url": "/public/images/avatars/avatar1.png",
        "name": "Claude Delafosse"
      },
      "-LTYprxFW53trxwLmXGX": {
        "image_url": "/public/images/avatars/avatar2.png",
        "name": "Jeanne Delafosse"
      },
      "-LTYprxFW53trxwLmXGd": {
        "image_url": "/public/images/avatars/avatar2.png",
        "name": "Mickaël Ndongo"
      }
    },
    "checksum": "d07fc356ce89cb45ee0b0f450ae4927f",
    "creation_date": 1544443660079,
    "duration": 11293173,
    "is_factory": true,
    "keywords": "pirate,père-noël,merveilleux,courage,héros,rêve,lutin,apprentissage,aventure,princesse,baleine,fantôme,Chateau,loup,baby-sitter,souris,Piscine,héroïne,sorcière,audace,Mer,Forêt,aventures,ogre,sirène,",
    "locales_available": {
      "fr_FR": true
    },
    "localized_infos": {

[...]
```

The file should weight hundreds of KB. You should save this file as `.studio/db/official.json`
Hope this is clearer.

**Comment by Worlgun** [comment]
Thank you so much. I successfully compiled.

**Comment by Worlgun** [comment]
Sorry again a little problem.

The compilation was successful, but I have a new error.
[WARNING] Some problems were encountered while building the effective model for studio:studio-core:jar:0.1.12-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.xiph:vorbis-java:jar should not point at files within the project directory, ${project.basedir}/../libs/vorbis-java-1.0.0-beta.jar will be unresolvable by dependent projects @ line 57,
column 25


when I go on line 57 here is what there is:   <systemPath>${project.basedir}/../libs/vorbis-java-1.0.0-beta.jar</systemPath>

**Comment by marian-m12l** [comment]
This looks like just a warning, shouldn't prevent packaging to succeed. Did you try to run it?

**Comment by Worlgun** [comment]
After executing here is the error I have.

- Error: unable to find or load the main class io.vertx.core.Launcher

**Comment by Worlgun** [comment]
I run from the folder where the script is located. or also with Windows PowerShell.

I do both

**Comment by marian-m12l** [comment]
OK I think I see where this is coming from. You need to "cd" into the `studio-web-ui-0.1.12-SNAPSHOT-dist` folder and execute the script from there (you must be in the same folder as the script). I'll update the readme to make this clear.

**Comment by Worlgun** [comment]
an upgrade : 

Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Testez le nouveau système multiplateforme PowerShell https://aka.ms/pscore6

PS C:\Users\Newte> C:\Users\Newte\.studio\web-ui\target\studio-windows.bat
Le chemin d’accès spécifié est introuvable.
Le chemin d’accès spécifié est introuvable.
Erreur : impossible de trouver ou charger la classe principale io.vertx.core.Launcher
PS C:\Users\Newte> cd C:\Users\Newte\.studio\web-ui\target\studio-web-ui-0.1.12-SNAPSHOT
PS C:\Users\Newte\.studio\web-ui\target\studio-web-ui-0.1.12-SNAPSHOT> C:\Users\Newte\.studio\web-ui\target\studio-web-ui-0.1.12-SNAPSHOT\studio-windows.bat
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure
Log4j 2
avr. 03, 2020 10:05:26 PM io.vertx.core.impl.launcher.commands.RunCommand
GRAVE: Failed to deploy verticle studio.webui.MainVerticle
java.lang.UnsupportedClassVersionError: studio/webui/MainVerticle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:242)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:215)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:182)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:155)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:144)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:677)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)

PS C:\Users\Newte\.studio\web-ui\target\studio-web-ui-0.1.12-SNAPSHOT>


but it still doesn't work. If I enter this address: http://localhost:8080

**Comment by marian-m12l** [comment]
The error message indicates that you are running Java 8 (version 52.0), while the classes were compiled with JDK 11 (version 55.0). Make sure your default `java` command is Java 11. Or you could modify `studio-windows.bat` to replace the `java` command with the full path to your JDK 11 `java` executable

**Comment by Worlgun** [comment]
might i have the example of ordering a car to fit it doesn't work when i do. JRE 11 No longer exists. And I only have JDK 11 and 14 installed.

**Comment by Worlgun** [comment]
it's good I succeeded with my jdk 14 thank you very much for everything. 

<a href="https://zupimages.net/viewer.php?id=20/14/r1g8.jpg"><img src="https://zupimages.net/up/20/14/r1g8.jpg" alt="" /></a>
