### ISSUE TITLE
Unsupported device metadata format version: 6

### ISSUE THREAD

**Issue by r4cker** [marian-m12l/studio#390]
Hi, 

I got a brand new Lunii with usb C and Wifi  (My old one is broken) and I got this message. I think it s related to #227 and #230

2023-09-03 19:06:26,477 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device 2.x
studio.core.v1.utils.exception.StoryTellerException: Unsupported device metadata format version: 6
        at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:128)
        at studio.webui.service.StoryTellerService.lambda$new$5(StoryTellerService.java:99)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

It was working with my old one. I spent days making stories with your tool....

**Comment by Chopin85** [comment]
Same problem. 

Studio-web-ui-0.3.1.
MacOS Ventura 13.5.1 (22G90).
MacBook 2,3 GHz Intel Core i5 quad-core.

**Comment by hackteur** [comment]
Same problem with lunii v3

**Comment by Lafabriquemanolo** [comment]
+1

**Comment by fregate84** [comment]
Same problem.
My lunii is a Lunii-3 with fireware 3.1

**Comment by lukalu** [comment]
+1

**Comment by ghnf** [comment]
+1

**Comment by blewis1510** [comment]
+1

**Comment by FrancoisDeBellescize** [comment]
Same for me

**Comment by pierrecorsini** [comment]
+1

**Comment by pierrecorsini** [comment]
https://github.com/marian-m12l/studio/blob/d78ae820c3e03a9499f3d08fff77b2100e7223b6/driver/src/main/java/studio/driver/fs/FsStoryTellerAsyncDriver.java#L121

The current code only handle versions `1 to 3`. The error indicates that a version `6` is used on recent devices. I am not sure if this format version is documented, but if it's fully proprietary; this could be hard work to fix.

**Comment by tdopierre** [comment]
Same issue

**Comment by tdopierre** [comment]
> https://github.com/marian-m12l/studio/blob/d78ae820c3e03a9499f3d08fff77b2100e7223b6/driver/src/main/java/studio/driver/fs/FsStoryTellerAsyncDriver.java#L121
> 
> The current code only handle versions `1 to 3`. The error indicates that a version `6` is used on recent devices. I am not sure if this format version is documented, but if it's fully proprietary; this could be hard work to fix.
> 
> P.S. You can find other repos on github with this issue already fixed => moving.

Can you point to another repo where this is fixed so we can still import our stories to our devices?

**Comment by SnowKhanOfficial** [comment]
Found another repo here that handle Lunii V3: https://github.com/DantSu/studio.git

**Comment by tdopierre** [comment]
EDIT: Managed to make it work with https://github.com/olup/lunii-admin-web
You need to point to the zip.

**Comment by pierrecorsini** [comment]
> Can you point to another repo where this is fixed so we can still import our stories to our devices?

https://github.com/DantSu/studio/blob/master/driver/src/main/java/studio/driver/fs/FsStoryTellerAsyncDriver.java

(Repo might have diverged too much to be sync)

**Comment by marian-m12l** [comment]
Experimental support for V3 devices has been merged on master. This remains mostly untested.

**Comment by r4cker** [comment]
Now working with the last version. Thanks you :)

**Comment by nicholass33** [comment]
Hello I have the same probleme for the V7 :/ Unsupported device metadata format version: 7 du you know if someone will work on it ?

**Comment by a-camacho** [comment]
> Hello I have the same probleme for the V7 :/ Unsupported device metadata format version: 7 du you know if someone will work on it ?

Same problem here.
Have been able to modify source code to allow V7, stories appear, can be sent to device.

**But any custom story sent to device shows as "SD Card Error" when navigating to it on device**

Any info about where should we start debugging ?
Is it really a new "version 7 story format" ?
