### ISSUE TITLE
Link to mhios.com est broken (le site is down actually)

### ISSUE THREAD

**Issue by paulz1** [marian-m12l/studio#416]
**Describe the bug**

Dans le README il y a un lien vers le site (Mes Histoires Interactives Open Stories : _mhios.com_ ).
Ce site est arrêté actuellement, cela est confirmé sur le github de son créateur : https://github.com/sebbelese/mhios

Ce serait bien, peut-être d'enlever le lien, ou de le remplacer avec le lien vers le dépôt guthub?

**Comment by marian-m12l** [comment]
PR mergée
