### ISSUE TITLE
impossible d'ouvrir avec l'éditeur

### ISSUE THREAD

**Issue by lorenzo59320** [marian-m12l/studio#417]
**Describe the bug**
Quand je clique sur "ouvrir ce pack d'histoire avec l'éditeur" g un message d'erreur alors qu'avec les autres histoires, j'ai pu le faire, j'ai ce message d'erreur

![image](https://github.com/marian-m12l/studio/assets/154459376/37f8271d-b85e-433c-ada0-86ba8b4b833e)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Cannot read properties of undefined (reading 'link')

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.4.2

**Additional context**

**Comment by lorenzo59320** [comment]
suis sur windows 10

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
