### ISSUE TITLE
Dev lint React error in the compilation

### ISSUE THREAD

**Issue by djcaesar9114** [marian-m12l/studio#423]
**Describe the bug**

I have this error in the build log: 

[ERROR] warning "react-scripts > @typescript-eslint/eslint-plugin@1.6.0" has unmet peer dependency "typescript@*".
[ERROR] warning "react-scripts > @typescript-eslint/parser@1.6.0" has unmet peer dependency "typescript@*".
[ERROR] warning "react-scripts > @typescript-eslint/eslint-plugin > @typescript-eslint/typescript-estree@1.6.0" has unmet peer dependency "typescript@*".
[ERROR] warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

**To Reproduce**
`git clone` then `mvn clean install`

**Expected behavior**
No error in the log

**Screenshots**

**Logs**
Cf. supra

**Desktop and environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser irrelevant
 - Java version: openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

 - Maven version: 
 - Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.21, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "6.2.0-37-generic", arch: "amd64", family: "unix"

 - STUdio application version: `feature/v3` branch of today

**Additional context**
Bonne année!

**Comment by Cervoz** [comment]
Same error here.

- Windows 11
- Master branch
- Maven 3.9.6 (I also tried with an older version)
- JDK 21

**Comment by marian-m12l** [comment]
Thanks for the feedback. Does it build? Is it a warning or an error?

p.s.: I'm closing issues from past years. Feel free to reopen if needed.
