### ISSUE TITLE
Java cp error

### ISSUE THREAD

**Issue by djcaesar9114** [marian-m12l/studio#424]
**Describe the bug**
I have a strange message in the console.

**To Reproduce**
1. compile from `feature/v3`
2. launch studio-linux.sh
3. read the console

**Expected behavior**
I'd like a clean log.

**Screenshots**
irrelevant

**Logs**
cp: impossible d'évaluer './agent/studio-agent-0.3.2-SNAPSHOT-jar-with-dependencies.jar': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer './agent/studio-metadata-0.3.2-SNAPSHOT-jar-with-dependencies.jar': Aucun fichier ou dossier de ce type

**Desktop and environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser irrelevant
 - Java version: openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

 - Maven version: 
 - Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.21, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "6.2.0-37-generic", arch: "amd64", family: "unix"

 - STUdio application version: `feature/v3` branch of today

**Additional context**
Merry Christmas!

**Comment by marian-m12l** [comment]
Thanks for the feedback. That's strange, those files should be there in the dist archive.
Anyway new release 0.4.0 has support for v3.
I'm closing issues from past years. Feel free to reopen if needed.
