### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by hteumeuleu** [marian-m12l/studio#43]
This is not an issue but just a thank you for this project. A few months ago, I was looking for a way to put homemade files on the Lunii and someone redirected me here. I only finally had time to play with it tonight and managed to get my first homemade story pack (with a custom invented story recorded by my 2 and 4 years old) on the device. I can't wait to do more. Thanks for the work you put into this project! (Obviously you can close this issue once you read it.)

**Comment by marian-m12l** [comment]
Thanks for your feedback!
You're very welcome. I'm just glad that this is becoming useful to other people. Making stories with the kids is the reason I started this (apart from my own curiosity, I guess), I hope you and your kids had fun crafting stories :raised_hands:
(P.s.: there may be a bug with the newest Lunistore libraries that prevent STUdio from interacting correctly with the device (#40), so be careful when updating libs)

**Comment by itdaboyz** [comment]
I jump in to say the same: thank you!
It's working great and gives us many possibilities. I used STUdio to put some music files in a custom story and my son is really happy with it.

**Comment by marian-m12l** [comment]
@itdaboyz Good to hear :smile:

**Comment by MiX-FR** [comment]
Deep thanks for this work !! My little girl (5 yo) is really happy to hear new stories in her device !

**Comment by imfloflo** [comment]
Big thanks, my little girl love the story with her name and her photo :)

**Comment by DenisMotte** [comment]
It work the first install !  Many thank's for this great job.
Denis

**Comment by marian-m12l** [comment]
@MiX-FR @imfloflo @DenisMotte Thanks for putting this app to great use! :-)

**Comment by jqueguiner** [comment]
https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif

**Comment by jqueguiner** [comment]
![image](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)

**Comment by GooGuiz** [comment]
Thank you soooooo much! Fantastic job! 
All the best for you and your lunii users!!!

**Comment by signix** [comment]
We made a pack of stories told by our family (who lives overseas). With travel restrictions we were not able to see them this year and our daughter is so happy to hear them every time she opens her lunii.
It is a very nice project.
Thank you.

**Comment by marian-m12l** [comment]
Happy to read this :-)

**Comment by manuelchavanet** [comment]
Bonjour Mariam,
je n'arrive pas à visualiser la Luuni Dans STUdio ,j'i bien réussi à créer ma premiere histoire personnalisée, mais rien dans la fenetre de gauche. merci d'avance pour votre aide et pour cet outil qui ouvre le chant des possibles 
<img width="1440" alt="Capture d’écran 2020-12-25 à 17 01 28" src="https://user-images.githubusercontent.com/76585639/103138434-ee4c8200-46d2-11eb-8db7-b1b4811dd667.png">

**Comment by signix** [comment]
> 
> 
> Bonjour Mariam,
> je n'arrive pas à visualiser la Luuni Dans STUdio ,j'i bien réussi à créer ma premiere histoire personnalisée, mais rien dans la fenetre de gauche. merci d'avance pour votre aide et pour cet outil qui ouvre le chant des possibles
> <img alt="Capture d’écran 2020-12-25 à 17 01 28" width="1440" src="https://user-images.githubusercontent.com/76585639/103138434-ee4c8200-46d2-11eb-8db7-b1b4811dd667.png">

Bonjour
Avez-vous branché et allumé la Lunii ?
Il faut également avoir installé les drivers de la Lunii qui viennent avec l'installation de l'applicaiton officielle.

**Comment by Ludman** [comment]
> > Bonjour Mariam,
> > je n'arrive pas à visualiser la Luuni Dans STUdio ,j'i bien réussi à créer ma premiere histoire personnalisée, mais rien dans la fenetre de gauche. merci d'avance pour votre aide et pour cet outil qui ouvre le chant des possibles
> > <img alt="Capture d’écran 2020-12-25 à 17 01 28" width="1440" src="https://user-images.githubusercontent.com/76585639/103138434-ee4c8200-46d2-11eb-8db7-b1b4811dd667.png">
> 
> Bonjour
> Avez-vous branché et allumé la Lunii ?
> Il faut également avoir installé les drivers de la Lunii qui viennent avec l'installation de l'applicaiton officielle.


Bonjour ! 

Magnifique travail !! L'interface et les possibilités sont incroyables ! Mes fils vont être aux anges d'entendre des histoires avec leurs prénoms et la voix de leurs parents ! Je suis conquis, dans le principe en tout cas, car je suis confronté au même problème que manuelchavanet, je n'ai aucune Lunii qui apparait, malgré l'appli officielle installée et la Lunii reconnue dans celle-ci. 

J'ai essayé un autre navigateur (safari n'étant pas toujours le plus... compatible...). J'ai essayé toutes les combinaisons possibles avec les 3 items : allumer la Lunii, lancer STUdio, et lancer le Luniistore... rien n'y fait, aucune Lunii reconnue dans STUdio... 

Maintenant que j'ai vu ce qui était possible, je trépigne d'impatience de pouvoir mettre mon propre Pack dans ce petit boitier... Alors si vous avez une idée du problème...

Merci d'avance,

Ludman

**Comment by Luckycorto** [comment]
Même problème... avec un modèle acheté pour noël, Il semble que ça soit récent. Une nouvelle version du firmware ? Une protection ?

**Comment by marian-m12l** [comment]
Effectivement, la version 2.x du firmware n'est pas encore supportée (c.f. #122)

**Comment by remyFasol** [comment]
Hi Mariam,
I came here in 2020, appreciate your product but could no do much as my box was already a version 2 :(.
Came back today and installed version 3.1 --> my daughter is currently listening to a new story pack I could upload using STUdio
GREAT, thanks for this great product and the continuous work on it.
Merci beaucoup !

**Comment by r3g31rk** [comment]
thank you

**Comment by nicoesiea** [comment]
Nothing else to add, I come from https://www.hteumeuleu.fr/mettre-ses-propres-histoires-sur-la-lunii/ where the author created a really good Doc in french. Thanks you very much for this excellent job

**Comment by Airwiwin** [comment]
Thx a lot Marian, very useful tool !

**Comment by Nezenlair** [comment]
> Nothing else to add, I come from https://www.hteumeuleu.fr/mettre-ses-propres-histoires-sur-la-lunii/ where the author created a really good Doc in french. Thanks you very much for this excellent job

As Nicoesiea I came from the same blog and could easily set up STUdio and created stories.
Un très très gros MERCI !

**Comment by djspatule** [comment]
Thank you so much ! Everything about this project is amazing !

**Comment by Ticas87** [comment]
Hi Marian !
A BIG Thank You fot this project !! It's Amazing =). 
I come from  https://www.hteumeuleu.fr/mettre-ses-propres-histoires-sur-la-lunii/ too and never in my craziest dreams would I have thought that i would so easily find à so complete solution to this problem ! 
Your Job is amazing !
My three kids are huge fans of the Lunii and now we have the possibility to add some story they have on CD or add some music or kids podcasts ! 
Thank you for them =)
