### ISSUE TITLE
Impossible d'ajouter le pack a la bibliothèque

### ISSUE THREAD

**Issue by VE988** [marian-m12l/studio#430]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: {"error":{"code":500,"message":"Internal Server Error"}}

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.5.0

**Additional context**

**Comment by marian-m12l** [comment]
Merci pour le retour. Je ferme cette issue car il n'y a pas assez d'informations. Si le problème persiste, ouvrez un nouvelle issue avec une description du problème et si possible les logs de la console.
