### ISSUE TITLE
Histoire qui disparait

### ISSUE THREAD

**Issue by sbonaime** [marian-m12l/studio#460]
Avec un lunii V3, j'ai bien réussi a mettre une nouvelle histoire que j'ai créé et mon enfant l'a écouté plusieurs fois. Mais 2 jours après l'histoire à disparu !
Comment est-ce possible ? 
Merci

**Comment by marian-m12l** [comment]
@sbonaime L'appareil a été connecté entretemps à un PC ou un téléphone ? En branchant sur un PC, est-ce que le dossier du pack (les premiers caractères de son UUID) est toujours présent ?
Je ne connais pas le fonctionnement de la V3, ne l'ayant pas eue en main, mais le logiciel officiel de Lunii pourrait facilement détecter un pack inconnu et le supprimer le cas échéant.

**Comment by sbonaime** [comment]
J'ai compris le problème. Les lunii V3 se connectent presque tout le temps à internet pour "vérifier des choses". Et c'est à ce moment que la lunii fait le ménage des histoires qu'elle ne connait pas ! Problème résolu en supprimant le fichier /et/wifi.prefs

**Comment by marian-m12l** [comment]
ok, c'est bon à savoir. je pensais qu'il fallait passer la lunii en mode wifi manuellement pour transférer des histoires.

**Comment by sbonaime** [comment]
Non, on peut aussi par un cable USB-C, j'imagine comme les lunii V2 (et v1 ?). Par contre en supprimant /etc/wifi.prefs on ne peut plus faire de synchronisation avec le téléphone..
