### ISSUE TITLE
impossible d'ajouter Profession croque-mitaine ?

### ISSUE THREAD

**Issue by dimahna258741** [marian-m12l/studio#462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.4.0

**Additional context**

**Comment by marian-m12l** [comment]
Merci pour le retour. Y a-t-il un message d'erreur sur l'interface web ou dans les logs ?
