### ISSUE TITLE
STUdio 0.5.0 fabrique histoires

### ISSUE THREAD

**Issue by mcolfr** [marian-m12l/studio#470]
Bonjour 
une erreur à la conversion de certain pack m'empeche la conversion
Fabrique histoires vers 3
STUdio 0.5.0
Ré installation java derniere version

Merci par avance pour vos idees et peut etre des solutions
Cordialement 

![erreur conversion pack](https://github.com/user-attachments/assets/3a57b0a4-9dff-4cec-adb7-162fc87ca9ea)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: {"error":{"code":500,"message":"Failed to convert FS format pack to ARCHIVE format"},"stack":["studio.webui.service.LibraryService.addConvertedArchivePackFile(LibraryService.java:232)","studio.webui.service.LibraryService.addConvertedPack(LibraryService.java:157)","studio.webui.api.LibraryController.lambda$apiRouter$4(LibraryController.java:92)","io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)","io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)","io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)","io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)","java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)","java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)","io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)","java.base/java.lang.Thread.run(Thread.java:833)"]}

**Desktop and environment (please complete the following information):**
 - OS: Win32
 - Browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.5.0

**Additional context**

**Comment by marian-m12l** [comment]
Bonjour,
La version 0.5.0 correspond certainement à un fork de STUdio (la dernière version publiée est la 0.4.0). Il n'y a pas de méthode `readAsset` dans ma version de la classe `FsStoryPackReader`. Mais il y a visiblement un souci de lecture du nom des assets depuis le fichier `ri`.

**Comment by marian-m12l** [comment]
Je viens de corriger un bug d'extraction des packs. Depuis la version 0.4.0 de STUdio les packs sont déchiffrés lors du transfert depuis l'appareil, mais ils n'étaient pas correctement marqués comme déchiffrés. La nouvelle version 0.4.1 devrait corriger ce problème et tenter de réparer les packs "cassés".
