### ISSUE TITLE
Lunii V3 - importation depuis la bibliothèque vers Lunii

### ISSUE THREAD

**Issue by mikhailo34** [marian-m12l/studio#471]
**Describe the bug**
Certaines histoires (exemple en PJ) sont importées avec succès dans la bibliothèque, mais le transfert depuis la bibliothèque vers Lunii est impossible - le curseur a la forme du "panneau interdit" et non de la "main drag&drop". 
[Ernest et Célestine.zip](https://github.com/user-attachments/files/16573167/Ernest.et.Celestine.zip)

**To Reproduce**
1. Importer l'histoire en PJ dans la bibliothèque
2. Essayer de l'importer dans Lunii

**Logs**
L'importation dans la bibliothèque ne semble pas générer de logs, et l'impossibilité de transfert non plus

**Desktop and environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox, Chrome
 - Java version: JDK 22.0.2.0
 - STUdio application version: 0.4.0

**Comment by marian-m12l** [comment]
Si c'est une histoire officielle de Lunii, c'est bien le comportement attendu, passez par le luniistore pour transférer vers l'appareil.

**Comment by mikhailo34** [comment]
Ok merci
