### ISSUE TITLE
ERROR message on Lunii device

### ISSUE THREAD

**Issue by oliv43** [marian-m12l/studio#474]
Hello,

I created a simple story and copied it to the device (V2).
Story is made with a mono MP3 file (128 Kbps, 44 KHz).
Everything seems OK in the editor (no error detected and story works in the simulator).
When I try it on the device I get an "ERROR" message. Any idea on what may be wrong and how to fix it?

Thanks.

**Comment by marian-m12l** [comment]
Hello,

I can't tell for sure, but it could be possible your particular "flavour" of mp3 is badly supported by the device, maybe try another format or encoder settings?
Or it could be something unrelated in you story pack. In the editor, did you run the validation?

Thanks for the feedback.
