### ISSUE TITLE
Cannot find .local.properties file

### ISSUE THREAD

**Issue by fatruc** [marian-m12l/studio#51]
**Describe the bug**

In the installation instructions, it is written that it is necessary to retrieve the authentication token in the .local.properties file.

This file does not exist even after logging into the lunistore.

Lunistore v2.0
Windows 10

**Comment by marian-m12l** [comment]
Hi. Thanks for the feedback.
In which folder did you look? Does the Luniistore run correctly? Also, you may need to force the display of hidden files in Windows Explorer.

**Comment by fatruc** [comment]
It was hidden, thx, issue closed
