### ISSUE TITLE
Feature Request - Reorganizing options order in menu node

### ISSUE THREAD

**Issue by Shasdo** [marian-m12l/studio#53]
In the Menu node, it would be great if there was a way to reorder the different options.
So if I need to add a story inbetween them, I don't have to remove and redo every options nodes that should be after.

**Comment by marian-m12l** [comment]
Definitely needed.

**Comment by Shasdo** [comment]
Happy to hear it! Keep up the good work!

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
