### ISSUE TITLE
Improvement: Windows Command automatic retrieval of token

### ISSUE THREAD

**Issue by xberg** [marian-m12l/studio#61]
Hi,
I improved the windows command file to automatically retrieve the token. The box needs to be connected and luniistore running.

Add the following lines just before the java call (last line)

:: Copy token

for /f "tokens=5 delims=:," %%a in ('type %LOCAL_LUNIITHEQUE%\.local.properties^|find "tokens"') do (
  set tok=%%a & goto :continue
)
:continue
set tok=%tok:~1%
set tokk=!tok:~0,-2!
SET URL=https://lunii-data-prod.firebaseio.com/packs.json?auth=%tokk%
curl %URL% -o %DOT_STUDIO%\db\official.json

Also at the beginning of the .BAT file add:
`@setlocal enableextensions enabledelayedexpansion`

**Comment by xberg** [comment]
That said I'm not sure curl (required above) is available and installed on all windows versions...

**Comment by marian-m12l** [comment]
Hi. Thanks for the script. Although it would be nice to automate this part somehow, I feel like it should be done without external dependencies (requiring the JDK seems already like a hurdle), and consistently on all supported OSes. Maybe this sort of tips could be shared on the wiki for now?

**Comment by xberg** [comment]
I agree. 
Perhaps indeed just create a token.bat file to be added in the wiki.

**Comment by xberg** [comment]
I created the wiki. First time using this so feel free to edit / delete / comment.

**Comment by marian-m12l** [comment]
Thanks for the contribution! Don't worry, the wiki will need to be better organized at some point, but it's pretty rough right now.
