### ISSUE TITLE
Use another SD card (higher capacity) for Lunii 

### ISSUE THREAD

**Issue by rockmanqh** [marian-m12l/studio#63]
Hi,

Sorry, it's not related to the Studio but I want to know it's is possible to use a higher SD card for Lunii? And someone had tried to do that.

Thanks

**Comment by marian-m12l** [comment]
Hi,
I'm afraid I don't have an answer to this. I think the official word from Lunii is that they are working on this possibility.

**Comment by iautran** [comment]
Try using dd commande to backup and then restore to a larger SD Card (it worked for me)
