### ISSUE TITLE
OK button didn't work

### ISSUE THREAD

**Issue by xstu25** [marian-m12l/studio#64]
Hi.

First of all, many thanks for your great job !

I"m sorry to ask that here (I think It's noob question !) but I try to do my own story, but something didn't work: the OK button didn't do nothing when mp3 playing.
I need It to switch to the next song, but It didn't works. All others things works, like transition between songs at the end of each one. 

MY only one pb is the OK button ! Thanks for your help !
!

[Sans titre](https://user-images.githubusercontent.com/64143891/80027665-63344000-84e4-11ea-9135-726068a3e9a7.png)

**Comment by marian-m12l** [comment]
Hi. Thanks for the feedback. Actually I think this is the "Customize OK transition" label that is misleading. On story nodes, the OK button is disabled, the "OK transition" is actually there for Autoplay at the end of the audio playback.
To achieve this behaviour, you'd need to use the so-called "expert nodes". A story node can be replaced by 1 action node (with a single entry) followed by a stage node. Enable the "home", "pause" and "autoplay" flags to mimick the behaviour of a story node, and from there you can add the "ok" flag to enable the OK button. You'll need to set the "home" transition too.

**Comment by xstu25** [comment]
Thanks for reply. I will test it and be back with the answer, for anybody who want to know how to do.

**Comment by xstu25** [comment]
Thanks for help. I finally understand what is an "expert node" and how It's work.

For people who want to have like a playlist with some sounds playing,  and OK button going on next sounds each time you click on It, here is a schema with an exemple of 2 songs.

Thanks for help !

![schema 2 songs](https://user-images.githubusercontent.com/64143891/80213016-d2bb4400-8638-11ea-9045-c962cf3919e2.png)

**Comment by marian-m12l** [comment]
Thanks for commenting back. I'll leave this issue open until I provide more documentation on the nodes.

**Comment by marian-m12l** [comment]
Fixed with release 0.1.14
