### ISSUE TITLE
Rss reader/importer

### ISSUE THREAD

**Issue by JEDIBC** [marian-m12l/studio#68]
Hi,

Would it be possible to add a RSS reader or importer to "pre-build" a story pack ? There's a lot of podcasts with nice stories like https://www.franceinter.fr/emissions/une-histoire-et-oli

Regards,

Bruno

**Comment by marian-m12l** [comment]
Hi, thanks for the feedback.

What outcome would you expect when importing a "playlist"?
RSS reader seems like a very specific need, but I can imagine "importing" several audio files at once (each assigned to a new story node) could be useful.

**Comment by wistof** [comment]
Hi Bruno,

I guess is not the main purpose of STUdio, to share content. Take a look here : https://www.hteumeuleu.fr/mettre-ses-propres-histoires-sur-la-lunii/,  at the end of article.

You had to build your own pack. But you can import/export your custom packs.

**Comment by JEDIBC** [comment]
@marian-m12l when importing a RSS of a podcast, it could import the audio files & image (perhaps do some transcoding ?) into story nodes. Then you can edit your pack as you wish.

@wistof I don't want to share content of any kind or create a side "luniithèque". Just being able to easily import free podcasts into the lunii.

**Comment by laruche** [comment]
Hi guys, I develop a Nodejs app to create story pack from RSS and upload to my child's lunii ;)
I have some refactoring before I can publish it :) 

@marian-m12l : there is a way to include it on your project ?

**Comment by laruche** [comment]
I have uploaded my code here : https://github.com/laruche/audiotolunii
and create npm module too : https://www.npmjs.com/package/audiotolunii

**Comment by marian-m12l** [comment]
@laruche Nice work. Hope it helps you guys find a better workflow :-)
However I feel like it should stay a separate tool: "niche" use-case, different tech stack, external dependencies... Still, nice use of the pack archive file format as an interface! FYI the format is not expected to evolve too much, and if it does I'm going to try and keep the software backwards-compatible (hence the format version number in the json file).

**Comment by jersou** [comment]
Hi guys,
I push a tool to generate studio pack from folder or RSS URL : https://github.com/jersou/studio-pack-generator

I hadn't spotted the https://github.com/laruche/audiotolunii project until tonight :-/.

I had checked the "THIRD-PARTY APPLICATIONS" part of the Readme before start studio-pack-generator, without seeing anything like my idea.

Can you update this section to reference related projects ? I can submit a pull request for that, unless you want to keep the section as is.

Anyway, thank you for this great work Marian !!

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
