### ISSUE TITLE
Installation Issue ?

### ISSUE THREAD

**Issue by Billx84** [marian-m12l/studio#69]
Hello, 
First, thanks for your work.

I work on Windows

I have an issue, I can't install your application.
I follow all the steps, but I don't understand what I have to do here : 
"#### Base de données officielle des métadonnées de packs d'histoires

Afin d'afficher les métadonnées des packs d'histoires, celles-ci doivent être téléchargées et stockées dans un fichier local.

* Lancer le logiciel Luniistore\* afin d'obtenir un jeton d'authentification (valable pendant une heure)
* Ouvrez `$LOCAL_LUNIITHEQUE/.local.properties` dans une éditeur de texte, et notez la valeur du jeton :
  * Si vous êtes connecté sur le logiciel Luniistore\*, le jeton se trouve dans la propriété `tokens`, attribut `tokens.access_tokens.data.firebase`
  * Si vous n'êtes pas connecté sur le logiciel Luniistore\*, le jeton se trouve dans la propriété `token`, attribut `firebase`
* Appelez `https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN` et enregistrez le résultat dans `$DOT_STUDIO/db/official.json` (p. ex. `curl -v -X GET https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN > ~/.studio/db/official.json`)
"
I find the key but next what I have to do ?

Thanks for your answer and for my children

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

**Desktop and environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version [e.g. 0.1.11]

**Additional context**

**Comment by marian-m12l** [comment]
Hi,
You should retrieve `https://lunii-data-prod.firebaseio.com/packs.json?auth=TOKEN` (replacing `TOKEN` with your actual token) and save its content into `.studio/db/official.json`

**Comment by wistof** [comment]
Hi, It is not a mandatory step. It just allow to have the cover of the official packs display into STUdio.
You can run the tool without this step.

**Comment by Billx84** [comment]
Thanks for your answer
After my message, I try again and succeed.
But now I have an another problem, I can't load the application. Nothing happens when I launch "localhost".
Thanks for your help

**Comment by Billx84** [comment]
I try again today, 
start from the beginning but I have issues again
![studio-windows](https://user-images.githubusercontent.com/64254497/80276002-aad5ea00-86e5-11ea-9e47-076c81b56658.png)
when I execute studio-windows.bat

and when I execute mvn clean install
![mvn clean install](https://user-images.githubusercontent.com/64254497/80276020-ce009980-86e5-11ea-87a6-a91626a1478b.png)

What did I do wrong ?

Thanks

**Comment by marian-m12l** [comment]
> 
> What did I do wrong ?
> 

If I may, your username :-)
It looks like you have spaces (and superscript character) in you path, which causes issues with the bat script (needs a fix). Try copying STUdio in a folder with no spaces in path.
Hopefully the app itself will be able to find `.studio` despite the spaces. Otherwise please report back.

**Comment by Billx84** [comment]
My username, what's wrong ? ^^

> If I may, your username 

No worry ^^

Thanks for your answer, I will try to change my STUdio folder location.

**Comment by Billx84** [comment]
Just in order to do things in the right way...
I have to create a folder name .studio and copy/paste some element from luniitheque folder.
I have to create a /db folder in my .studio folder for TOKEN and *.json file.
I have to run mvn clean install but I don't really understand where I have to unzip studio files downloaded before. 
Do I create a new folder somewhere or all in the same folder .studio ?
Thanks a lot

**Comment by marian-m12l** [comment]
Sorry, I was not judging your username :) Just pointing that your home folder contains spaces.
You can unzip the application in any folder, just make sure the required stuff is there in `.studio`. The token must be used to fetch the official story packs metadata (`official.json`). You can either use maven to compile, or use a pre-built release downloaded from github.

**Comment by Billx84** [comment]
> Sorry, I was not judging your username :)
Don't worry, no problem my username is a memory from school.

**Comment by Billx84** [comment]
> Just pointing that your home folder contains spaces.
Yes I know but I can't really change that, I can change user name but my home folder name doesn't change. :(

**Comment by wistof** [comment]
Hi, I haven't tested yet, but you can try to put "  to surround all the paths in the .bat.

![image](https://user-images.githubusercontent.com/13451357/80348875-b86aab80-886e-11ea-80fc-b279340f74df.png)

**Comment by marian-m12l** [comment]
> Hi, I haven't tested yet, but you can try to put " to surround all the paths in the .bat.

This may help, indeed.

Also, you can overwrite the paths by defining JVM-wide properties (by adding `-Dthe.property.name=thevalue` to the `java` command):
* For the local library: `studio.library`
* For the official metadata database: `studio.db.official`
* For the unofficial metadata database: `studio.db.unofficial`

**Comment by Billx84** [comment]
> > Hi, I haven't tested yet, but you can try to put " to surround all the paths in the .bat.
> 
> This may help, indeed.
> 
> Also, you can overwrite the paths by defining JVM-wide properties (by adding `-Dthe.property.name=thevalue` to the `java` command):
> 
> * For the local library: `studio.library`
> * For the official metadata database: `studio.db.official`
> * For the unofficial metadata database: `studio.db.unofficial`

Hi
I'm sorry but I think I have reached my limits. Can you be more specific about what I have to do (like recipes) . Java or others manipulations aren't really in my skills but I want to learn ^^

Thanks a lot

**Comment by marian-m12l** [comment]
Hi,
In the bat script, simply add arguments to the `java` command line, e.g. `-Dstudio.library=D:/studio/library` to overwrite the location of local library (where story packs are stored). Search for java system properties to get more context.

**Comment by Billx84** [comment]
> Hi,
> In the bat script, simply add arguments to the `java` command line, e.g. `-Dstudio.library=D:/studio/library` to overwrite the location of local library (where story packs are stored). Search for java system properties to get more context.

Thanks for your answer but I am really really sorry, I understant what I have to do, but I don't know where in the bat add the command line.

`@echo off

set STUDIO_PATH=%~dp0
set DOT_STUDIO=%UserProfile%\.studio
set LOCAL_LUNIITHEQUE=%UserProfile%\AppData\Roaming\Luniitheque

:: Make sure the .studio subdirectories exist
if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
if not exist %DOT_STUDIO%\db\* mkdir %DOT_STUDIO%\db
if not exist %DOT_STUDIO%\lib\* mkdir %DOT_STUDIO%\lib
if not exist %DOT_STUDIO%\library\* mkdir %DOT_STUDIO%\library

:: Copy Luniistore JARs if needed
if not exist %DOT_STUDIO%\lib\lunii-java-util.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-java-util.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-gateway.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-gateway.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-wrapper.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-wrapper.jar %DOT_STUDIO%\lib\

:: Copy agent and metadata JARs
copy %STUDIO_PATH%\agent\studio-agent-0.1.13-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-agent.jar
copy %STUDIO_PATH%\agent\studio-metadata-0.1.13-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-metadata.jar

java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%/studio-web-ui-0.1.13.jar;%STUDIO_PATH%/lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle
`

**Comment by marian-m12l** [comment]
Hi,
On the last line, the `java` command.

**Comment by Billx84** [comment]
> Hi,
> On the last line, the `java` command.

Thanks but not working   ^^(

**Comment by marian-m12l** [comment]
Hi,
What command did you try exactly? And do you get an error message?

**Comment by Billx84** [comment]
Hi, 

I copy/paste but maybe I did it wrong

`@echo off

set STUDIO_PATH=%~dp0
set DOT_STUDIO=%UserProfile%\.studio
set LOCAL_LUNIITHEQUE=%UserProfile%\AppData\Roaming\Luniitheque

:: Make sure the .studio subdirectories exist
if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
if not exist %DOT_STUDIO%\db\* mkdir %DOT_STUDIO%\db
if not exist %DOT_STUDIO%\lib\* mkdir %DOT_STUDIO%\lib
if not exist %DOT_STUDIO%\library\* mkdir %DOT_STUDIO%\library

:: Copy Luniistore JARs if needed
if not exist %DOT_STUDIO%\lib\lunii-java-util.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-java-util.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-gateway.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-gateway.jar %DOT_STUDIO%\lib\
if not exist %DOT_STUDIO%\lib\lunii-device-wrapper.jar copy %LOCAL_LUNIITHEQUE%\lib\lunii-device-wrapper.jar %DOT_STUDIO%\lib\

:: Copy agent and metadata JARs
copy %STUDIO_PATH%\agent\studio-agent-0.1.13-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-agent.jar
copy %STUDIO_PATH%\agent\studio-metadata-0.1.13-jar-with-dependencies.jar %DOT_STUDIO%\agent\studio-metadata.jar

java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp %STUDIO_PATH%/studio-web-ui-0.1.13.jar;%STUDIO_PATH%/lib/*;%DOT_STUDIO%/lib/*;. io.vertx.core.Launcher run studio.webui.MainVerticle 
-Dstudio.library=D:/studio/library
`

And the error message
![image](https://user-images.githubusercontent.com/64254497/81425590-3032b300-9158-11ea-9a3f-e56f46de2fd2.png)

Thanks

**Comment by Billx84** [comment]
Hello everybody, 
Does someone know a solution to my issue?

**Comment by marian-m12l** [comment]
Your script is still referencing `%UserProfile%`, which IIRC contains spaces?
You can comment all the `mkdir` and `copy` commands and do thing manually, just once.
Your `java` command:
- shouldn't use `%DOT_STUDIO%` in the classpath. Change it to the folder where you manually copied the Lunii JARs
- I'm not sure you can add the `studio.library` property at the end, just put it beside the other `-D` options (right after the `java` keyword)

**Comment by Billx84** [comment]
Hi
Sorry for no response, but I have tried to find a way for success by myself but I failed.
I don't really understand what you want me to do?
Do you think you can post the code I have to copy and paste on the file ?
Thanks a lot.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
