### ISSUE TITLE
Coming soon...

### ISSUE THREAD

**Issue by vwasteels** [marian-m12l/studio#70]
FYI

![Screenshot -  2020-04-24 à 11 49 26](https://user-images.githubusercontent.com/1151398/80199532-beb81800-8621-11ea-8a92-3f5b7a4e80e0.jpg)

**Comment by marian-m12l** [comment]
![goodnews](https://user-images.githubusercontent.com/50991156/80209443-64738300-8632-11ea-8005-e0bc649c7120.gif)

**Comment by appenzellois** [comment]
Surtout ne rien lâcher! On ne sait pas encore qui que quoi comment cela va se faire (si ça se fait). Vendre des histoires payantes c'est un super business model difficile à lâcher pour rien... ;-)

**Comment by kaelhem** [comment]
FYI

![reponse-lunii](https://user-images.githubusercontent.com/1114181/84773018-13ea2780-afdc-11ea-833a-c969b59a4006.png)

**Comment by cvandeplas** [comment]
On dirait que c'est lancé: https://www.lunii.fr/studio

En résumé: 
- une appli android/iphone
- il faut enregistrer soi-même l'histoire par le micro du téléphone
- l'histoire apparaît ensuite dans le luniistore pour le mettre sur le lunii. 

![image](https://user-images.githubusercontent.com/1073662/88487231-7e02ce80-cf83-11ea-9959-a875228ee92a.png)

**Comment by marian-m12l** [comment]
This is great news :-)

Closing the issue, though, for easier tracking of the actual issues :-)
