### ISSUE TITLE
Can't link a menu to a third option

### ISSUE THREAD

**Issue by MiX-FR** [marian-m12l/studio#71]
**Describe the bug**
When i add a third option, i can't link an action menu to this option.

**To Reproduce**
1. Add a third option in an action menu.
2. Link an action menu to this third option
3. Export it to the device.
==> Everything seems fine but once using the device,if I selected the third option, it goes back to the action step.
4. Open another time the package, and then the link disapears (but not completly: you can see the extremity of the arrow)
![Image3](https://user-images.githubusercontent.com/64275623/80251833-8989e500-8676-11ea-9856-adb2df4afe17.png)

5. Try to create the link again, it's not possible.
6. Select the extremity of the arrow and delete it.
7. Add one more time a third option and then no link is possible.
==> The link appears while the drag and drop but it does not stay.

I also saw that the new option's tooltip isn't refreshed and displays the previous one.

**Expected behavior**
The link should be created.

**Screenshots**
![Image2](https://user-images.githubusercontent.com/64275623/80249595-6eb57180-8672-11ea-83e6-7de92c91b67b.png)

**Logs**
[studio-latest.log](https://github.com/marian-m12l/studio/files/4531097/studio-latest.log)

**Desktop and environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 75.0 (64 bits)
 - Java version: JDK 14.0.1 and jre1.8.0_251
 - Maven version: No Maven, I use the ui pack.
 - STUdio application version : studio-web-ui-0.1.13

**Additional context**
I can provide the package if needed.
I've tried several times to add this third option.
As a clean basis I use the sample and try to change as few items as possible.

Thanks in advance for your help.

**Comment by bourgouinadrien** [comment]
It seems that the top three node and the bottom 2 nodes aren't compatibles each other.
You should either use one group or the other but you can't mix.

I guess that according to Lunii stories I previously bought.

**Comment by marian-m12l** [comment]
Hi, and thanks for the feed back.

Did you duplicate nodes? It feels like this could be an issue with duplicated ports. The "orphaned arrow" could happen if an outbound link goes back to the same node.

It would help if you can share the `story.json` file from your pack.

**Comment by MiX-FR** [comment]
Thanks for your feedback.

[story.zip](https://github.com/marian-m12l/studio/files/4534896/story.zip)
I did duplicate nodes. I'll try using a new node.

Anyway, here's the story.json file from the package.

**Comment by MiX-FR** [comment]
> 
> 
> It seems that the top three node and the bottom 2 nodes aren't compatibles each other.
> You should either use one group or the other but you can't mix.
> 
> I guess that according to Lunii stories I previously bought.

Thanks for your feedback, I don't get what's the top 3 nodes and the bottom 2 nodes are.
Can you name them?
How do you know that they ain't compatible?
What should I use instead?

**Comment by MiX-FR** [comment]
> I'll try using a new node.
I did try to use new nodes, I get the same result :
Once created, this is what's displayed: (seems right)
![before](https://user-images.githubusercontent.com/64275623/80302494-b93a0980-87aa-11ea-9ef6-efbbdeeeec7b.png)

After saving, exporting the package and then copying it on the lunii device :
![after](https://user-images.githubusercontent.com/64275623/80302495-b9d2a000-87aa-11ea-847e-48dabd59430f.png)

**Comment by bourgouinadrien** [comment]
> > It seems that the top three node and the bottom 2 nodes aren't compatibles each other.
> > You should either use one group or the other but you can't mix.
> > I guess that according to Lunii stories I previously bought.
> 
> Thanks for your feedback, I don't get what's the top 3 nodes and the bottom 2 nodes are.
> Can you name them?
> How do you know that they ain't compatible?
> What should I use instead?

For me, you have to choose between a story made with nodes
Noeud départ, noeud de menu, noeud d'histoire
OR
Noeud de scène, noeud d'action

You can't mix these two lists of nodes.

**Comment by MiX-FR** [comment]
I used "Noeud départ", "noeud de menu" and "noeud d'histoire" only.

There's no "noeud de scène" or "noeud d'action".

Check colors.
![Image6](https://user-images.githubusercontent.com/64275623/80304683-e4772580-87b7-11ea-9836-7c534412020a.png)

**Comment by marian-m12l** [comment]
Will look deeper into your pack when I get some time. Thanks for the feed back.

**Comment by marian-m12l** [comment]
There was indeed an embarrassing bug when using "backwards" links (created from to destination). Now fixed with release 0.1.14

**Comment by MiX-FR** [comment]
Thanks a lot. It works perfectly ! 👍
