### ISSUE TITLE
Error when i plug the lunii box

### ISSUE THREAD

**Issue by imfloflo** [marian-m12l/studio#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> com.lunii.device.wrapper.raw.handler.DeviceHandlerException: com.lunii.device.gateway.DriverException: Cannot get handle for handler, code : LIBUSB_ERROR_NO_DEVICE: Error 500: com.lunii.device.wrapper.raw.handler.DeviceHandlerException: com.lunii.device.gateway.DriverException: Cannot get handle for handler, code : LIBUSB_ERROR_NO_DEVICE	at studio.webui.service.StoryTellerService.deviceInfos(StoryTellerService.java:110)
	at studio.webui.api.DeviceController.lambda$apiRouter$2(DeviceController.java:36)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.13

**Additional context**

**Comment by marian-m12l** [comment]
Hi,
Looks like an error in the USB driver. Seems to happen sometimes for a reason yet to be determined.
Does your setup (including same usb cable) work correctly in the Luniistore?

**Comment by imfloflo** [comment]
Yes i used the luniibos usb cable all time, it seems it depends if i plug the luniibox before or after launching the webserver.
I find a workaround so you can set the priority to low on this bug.
Btw there is an error in the console if there is no official.json file at launch. (you can add a check on this file and display a message -with a link to the wiki- to explain how we should retrieve the token.

**Comment by marian-m12l** [comment]
Log messages can definitely be improved. Good idea.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
