### ISSUE TITLE
Version number not updated in the exported package file name

### ISSUE THREAD

**Issue by MiX-FR** [marian-m12l/studio#74]
**Describe the bug**
The version number is not updated in the exported package file name

**To Reproduce**
1 - Create a package without changing the package version.
2 - Export this package
==> The file name finished with "v1"
3 - Update the version (v2)
4 - Save the package
5 - Export this package
==> The file name finished with "v1"

**Expected behavior**
the exported package name should be coherent with the package version.

**Screenshots**
Not necessary.

**Logs**
Not necessary.

**Desktop and environment (please complete the following information):**
    OS: Windows 10
    Browser: Firefox 75.0 (64 bits)
    Java version: JDK 14.0.1 and jre1.8.0_251
    Maven version: No Maven, I use the ui pack.
    STUdio application version : studio-web-ui-0.1.13

**Additional context**
Not necessary.

**Comment by marian-m12l** [comment]
Hi,
You should get a popup asking if you want to refresh the file name right after blurring the version field. Maybe this part is ignored if you clicked the save button before? Can you make sure you leave the field (using tab or clicking outside the field), see if fixes the issue?

**Comment by MiX-FR** [comment]
I tried and there's no such pop up.

The only pop up I get is when I unselect the package name (whether I modify it or not).

**Comment by marian-m12l** [comment]
Will need to look at this. Thanks for the feedback.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
