### ISSUE TITLE
Dropzone is too small

### ISSUE THREAD

**Issue by nclavaud** [marian-m12l/studio#76]
I had a hard time drag and dropping packs from the local library onto the device (and first thought that the drag & drop did not work) until I found out that the drop zone on the left was too small, and actually constrained to the official pack:

![Screenshot from 2020-04-26 23-54-25](https://user-images.githubusercontent.com/1181770/80320977-f7badd00-8819-11ea-9cea-0031bccc5f38.png)

It would work fine only when dropping the pack onto an existing pack.
I'm using Firefox or Chromium on Ubuntu.

Maybe adding a "drop icon" below the loaded packs would help? Something as simple as:

![Screenshot from 2020-04-26 23-58-55](https://user-images.githubusercontent.com/1181770/80321017-3781c480-881a-11ea-90fa-33d93a89fa4f.png)

Please don't mind the poor design, this is just for the example.

**Comment by marian-m12l** [comment]
Definitely a nice improvement.

**Comment by appenzellois** [comment]
Very good suggestion indeed. I had to struggle a bit finding where to drag the stories.
+1

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
