### ISSUE TITLE
Isssues  when Windows %UserProfile% not in default folder

### ISSUE THREAD

**Issue by appenzellois** [marian-m12l/studio#78]
I had to manually set the UserProfile path in the BAT because I have mine on the D:\ drive.

Also, the DB is only looked after on the C drive despite beeing set up manually in the BAT

**Comment by marian-m12l** [comment]
`%UserProfile%` is used within the bat script to perform copies of the required files, and to reference the JAR libraries to be loaded (in the `java` command).
Within the application, I'm using the `user.home` system property, which on Windows seems to come from a call to `shell32.dll`.

So I'm unsure how your situation reports in both contexts.

Does `%UserProfile%` point to your actual home folder on drive D?
Does this folder also contain `AppData`?

Also, you can override the paths the app is looking into by defining JVM-wide properties (by adding `-Dthe.property.name=thevalue` to the java command):
* For the local library: `studio.library`
* For the official metadata database: `studio.db.official`
* For the unofficial metadata database: `studio.db.unofficial`

**Comment by appenzellois** [comment]
It seems the issue is on my side.

I moved my %UserProfile% long time ago to drive D:\, but currently it points again to my C:\ drive. It might have been caused by a Windpws upgrade or whatever mysterious reason...

Thanks for your time.
