### ISSUE TITLE
Suggestion: icon resize + icon pack

### ISSUE THREAD

**Issue by xberg** [marian-m12l/studio#79]
Hi,
I would like to suggest the following improvements:
1. Automatic icon resizing. 
The documentation states that icons must be 320x240 pixels. Why not have STUdio automatically resize icons that are not the correct size?

2. Provide a default icon pack
Searching for icons is quite time consuming when creating a pack. Perhaps in addition to the current option to upload your own icons you could implement a default icon pack with for instance the font awesome pack? That would give us access to 1500 icons immediately... 

thanks

**Comment by marian-m12l** [comment]
Hi,
Thanks for the suggestions.

Regarding 1., I'm not sure the application should perform "destructive" actions such as resizing an image, without keeping its ratio or by cropping it. But it should definitely raise en error when an image does not meet the required dimensions!

Regarding 2., that would be nice indeed. I'll need to make sure the font awesome icons can indeed be used that way. And to think of a way to integrate this icon library. Maybe a side panel with a filter and draggable images?

**Comment by MiX-FR** [comment]
> Regarding 1., I'm not sure the application should perform "destructive" actions such as resizing an image, without keeping its ratio or by cropping it. But it should definitely raise en error when an image does not meet the required dimensions!

I disagree, I think it would be a great feature : what took me quite some time at the beginning is to understand the size expected (it's described in the read me located in the source code, note in the release or in the wiki) and then resize each picture. It still takes time to resize precisely pictures (btw I use Paint so if anyone has a better tool for resizing ...)

Here is what I suggest : 
1 - Studio identifies whether the picture uploaded is fine or not.
2 - If the size is not correct ==> Pop up to warn the user and suggestion to resize it automatically.
That way, the user won't be bother if it's not resized properly.

However, I don't know whetherit's time consumming and/or complex to implement. ==> It's up to you @marian-m12l  ;-)

**Comment by marian-m12l** [comment]
Hi,
I think the first thing to do would be to properly document this in-app (expected dimensions, formats, as well as nodes' behaviour, etc.). But I'll keep it in mind, shouldn't be too complex to do this client-side.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
