### ISSUE TITLE
Better previews #enhancement

### ISSUE THREAD

**Issue by appenzellois** [marian-m12l/studio#80]
It would be nice to be able to playback the media files used for the stories.
Also it would be nice to have a larger view of the images.

**Comment by marian-m12l** [comment]
Hi,
What do you mean "be able to playback the media files used for the stories"? Isn't that already possible?
Also, the images are already displayed bigger than they are on the device (320x240), why do you want a larger view?
Thanks for the feedback!

**Comment by appenzellois** [comment]
Hi,
In the story editor, there is a "play" (arrow) icon on every nod that has a sound file already attached, but clicking on it shows up the file selection dialog again. I coulnd't find how to play a file from the editor or even how to visualise what file (i.e the filename) is in the node.

Also, the images appear quite small in the editor. They are much more readable on the lunii than on my screen.

See my printscreen for better understanding.

![scshot](https://user-images.githubusercontent.com/64407893/80794011-0ba76b80-8b99-11ea-9636-cb9b0b75beb4.png)

Thanks for the amazing work !

**Comment by marian-m12l** [comment]
Hi,
Did you try the "preview" feature, when clicking the "eye" icon of any node?
The filename wouldn't help as it is lost when saving a story pack.

**Comment by appenzellois** [comment]
O_O
Oh my god, this is great !

I didn't see it before :-)
My only complain would then be that it's not intuitive, but once you know it it's very nice.

**Comment by marian-m12l** [comment]
Indeed, designing an intuitive UI is pretty hard! Add too much info, and it becomes verbose, strip too much and users do not know what to do...
