### ISSUE TITLE
42 stories limitation ? 

### ISSUE THREAD

**Issue by iautran** [marian-m12l/studio#81]
Hello,

I created several custom "short" stories.

Even if I still have free spaces on my SDCard, I have an error every time I try to add a 43th story.

Is there any limitation regarding the maximum number of stories we can add ? 

Thank you

**Comment by marian-m12l** [comment]
Hi,
I have absolutely no idea :-) Didn't load that much stories on the device, isn't that a bit unpractical to select a story pack?
I can imagine the Lunii has some sort of limit, but 42 stories seems like a weird number. Or maybe not ^^

**Comment by iautran** [comment]
Thank you Marian, so it's not a limitation on STUdio (bad news ! as I guess it means that we will not have any other solution to circumvent this value (?)).

One  solution should be  to merge several stories. For example a "Child 1" and "Child 2" top-stories (when we power on the Lunii) and for each child I will have sub-stories (and that will contain all my actual stories).

Is it complicated for you to add this kind of feature (easily merge stories) ?

Thanks again; many children are really happy thanks to you :) 

That should improve the way to navigate on the Lunii when we have many stories :)

**Comment by marian-m12l** [comment]
Hi,
I didn't give it enough thought, but it would be nice indeed to be able to import from another pack. Maybe add a button on the toolbar to select a pack file to add to the current diagram. Not sure how to avoid having the current nodes and imported nodes intertwined, though..

**Comment by Paulguiot** [comment]
> Hi,
> I have absolutely no idea :-) Didn't load that much stories on the device, isn't that a bit unpractical to select a story pack?
> I can imagine the Lunii has some sort of limit, but 42 stories seems like a weird number. Or maybe not ^^

It seems this collection have more than 42 records, is someone have it and detail how it's done?

https://www.lunii.fr/catalogue/categorie/type?categoryId=-LTYps04JmEyYrZ42kSg

Regards,
P.

**Comment by iautran** [comment]
Hi Paul,

The 42 stories limit concerns the limit of your top level stories (the list of stories you can choose when you power on your device). 
I am not sure you are talking about that too.

**Comment by Paulguiot** [comment]
I was not talking about this level of stories, I didn't try to create more than 42 stories on the top level. I was talking about the lower level; my objective was to select a story and next random play one of the 200 short stories.

**Comment by marian-m12l** [comment]
@Paulguiot Did you try making a story with a 42+ options menu? Never tried this, so I couldn't tell.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
