### ISSUE TITLE
Having a way to delete nodes

### ISSUE THREAD

**Issue by athieriot** [marian-m12l/studio#83]
Hello ! This studio is working wonderfully so far. Thank you for your work.

However, I wanted to move some of my stories from one Project to another and so I ended up with a few lone nodes that I can't find a way to remove.

Is there a button I can't find or would it be a good feature to have ?

**Comment by marian-m12l** [comment]
Hi.
You can select a node by clicking on it (or multiple nodes by clicking the canvas and dragging a "selection rectangle"), then press delete. Or am I not understanding what you're trying to do?
Thanks for the feedback!

**Comment by athieriot** [comment]
Ah! Yes of course.
It is exactly what I was looking for. I did not even think of trying this :/

Sorry for the time spent !

And thank you
