### ISSUE TITLE
Error in .bat launch script

### ISSUE THREAD

**Issue by dmist** [marian-m12l/studio#84]
**Describe the bug**
The .bat launch script tries to copy 2 files from %STUDIO_PATH%\agent\xxx, but this causes an error because the path should be %STUDIO_PATH%\lib\xxx .

**To Reproduce**
Launch studio-windows.bat in a terminal (ex: cygwin bash terminal) and watch the file errors.

**Expected behavior**
No errors.

**Logs**
On french terminal, the script displays errors:
Le chemin d’accès spécifié est introuvable.
Le chemin d’accès spécifié est introuvable.

**Desktop and environment (please complete the following information):**
 - OS: Windows 10 w/ Cygwin

**Comment by marian-m12l** [comment]
Hi,
I think you must be running the script from the `target` folder of web-ui. The correct way is to run the script that comes within the distribution archive (studio-web-ui-*-dist.zip).

**Comment by dmist** [comment]
Indeed. Thanks
