### ISSUE TITLE
Je n'arrive pas a enregistrer mes histoires

### ISSUE THREAD

**Issue by ptitju44** [marian-m12l/studio#86]
Bonjour,

Je n'arrive pas a enregistrer le pack dans la bibliothèque.

Pouvez vous me dire d'ou peut venir le problème.

Cordialement.

**Comment by ptitju44** [comment]
mon probleme est peut etre identique au ticket 67

**Comment by marian-m12l** [comment]
Bonsoir,
Comment le problème se manifeste-t-il ? Y a-t-il un message d'erreur ? Des logs côté navigateur ou serveur ?
Merci.

**Comment by HyperCed** [comment]
Bonsoir, j'ai peut être le même souci.
Je n'arrive plus à charger des package zip. En fait, les fichiers .zip sont bien copiés dans le dossier ~/.studio/library/ mais ça me met fetch 0 pack from "library" . Et le résultat, c'est que je n'ai aucun pack qui s'affiche... Bizarrement, ça a marché au début, mais plus rien depuis aujourd'hui.
Pas d'erreur js. L'upload semble bien fonctionner, mais pas le fetch de la library. Je suis sur MacOS 10.13.6, j'ai essayé avec 3 navigateurs.
J'ai aussi essayé les version 0.16, 0.17 et 0.20 beta avec le même résultat...

**Comment by marian-m12l** [comment]
@HyperCed @ptitju44 Le problème est-il résolu ?

**Comment by HyperCed** [comment]
Oui, c'est tout bon pour moi!

**Comment by TheNuru** [comment]
Bonjour
J ai exactement le même problème pouvez vous nous dire comment vous l avez résolu?
Merci d avance

**Comment by HyperCed** [comment]
Comme mentionné plus haut, il y avait un souci avec mes archives zip. J'avais un niveau de répertoire en trop. Sur MacOS, il faut prendre les fichiers contenus dans l'archive et choisir "compresser", et il ne faut surtout pas faire cette opération sur le répertoire parent.
Ca a réglé mes problèmes.

**Comment by TheNuru** [comment]
En effet en passant par Firefox pour ne pas avoir de desarchivage auto ça marche mieux
Merci à vous

**Comment by marian-m12l** [comment]
@TheNuru @HyperCed Le problème semble résolu, mais je n'ai pas bien compris les opérations qui posent problème?! Vous exportez les histoires en téléchargeant l'archive et non en enregistrant directement dans la "bibliothèque"? Et Safari décompresse systématiquement les archives? Il y a peut-être quelque chose à améliorer sur l'application?

**Comment by TheNuru** [comment]
En effet safari décompresse automatiquement et quand je décompresse derrière cela ne fonctionnait pas
En passant avec Firefox et en bloquant la décompression automatique le fichier zip fonctionne sans probleme

**Comment by marian-m12l** [comment]
Glad this is solved :-)
