### ISSUE TITLE
batch doesnt work if user folder has a space

### ISSUE THREAD

**Issue by Bitkhazi2** [marian-m12l/studio#87]
**Describe the bug**
my user floder has a space (something like C:\Users\xxxx yyyy). The batch launcher doesn't work for this reason (missing quotes for "space" compatibility). To correct this I just added quotes to every filename used. For example for the first filename used in the batch : 

before : if not exist %DOT_STUDIO%\agent\* mkdir %DOT_STUDIO%\agent
after :    if not exist "%DOT_STUDIO%\agent\*" mkdir "%DOT_STUDIO%\agent"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Le chemin d’accès spécifié est introuvable.

**Desktop and environment (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by marian-m12l** [comment]
Hi, and thanks for the feedback. Seems similar to #58 ? This spaces issues must be addressed, indeed.

**Comment by Bitkhazi2** [comment]
Hello

Yes it seems similar to me too

Have a nice day, and thanks for the very good work

**Comment by dasebasto** [comment]
I had a similar problem because my STUdio path (`%STUDIO_PATH%`) contains " - "

Because of the lack of escaping, I got this error from Java:

Unrecognized option: -
Error: Could not create the Java Virtual Machine

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
