### ISSUE TITLE
Warning when launched

### ISSUE THREAD

**Issue by Bitkhazi2** [marian-m12l/studio#88]
**Describe the bug**
a warning message appears when launched. I don't know yet if it does work or not after this warning. It says that an illegal access is detected. 

**To Reproduce**
launch the batch

**Expected behavior**
maybe it's ok like that :)
But what are/might be the consequences

**Screenshots**

![image](https://user-images.githubusercontent.com/64708358/80891778-a2257b00-8cc6-11ea-91bd-8494499420d8.png)

**Logs**

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (file:/C:/Users/Lemoine%20Luiz/.studio/lib/netty-resolver-dns-4.1.30.Final.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Desktop and environment (please complete the following information):**
 - OS: Windows 10
 - Browser : firefox (not used yet at this step)
 - Java version: jdk-14.0.1 (open JDK)
 - Maven version: not used
 - STUdio application version : 0.1.14 (also appears in 0.1.13)

**Additional context**
Thank you for your work. I haven't used yet, though it's promissing and I like very much the idea of realy creating our own stories

**Comment by marian-m12l** [comment]
Hi,
I think this warning may be due to using JDK 14 (I target JDK 11). Will need to investigate.
Thanks for the feedback!

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
