### ISSUE TITLE
Suggestion: verify diagram when saving

### ISSUE THREAD

**Issue by nicojlt** [marian-m12l/studio#90]
Hi, 
1st of all, thanks for all the work accomplished ;)

I had a javascript error trying to upload one of my creations to the lunii.
#72 saved me : I had error in my diagram.

It would be great to have an non-blocking alert message "warning your diagram has errors" when saving our stories.

thanks !

**Comment by marian-m12l** [comment]
Hi,
Good suggestion. Thanks.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
