### ISSUE TITLE
Can't go back to pack selection menu by clicking on home button ?

### ISSUE THREAD

**Issue by DavidZurmely** [marian-m12l/studio#92]
Hello,
First let me thank you for your great job.
I succesfully created a pack for the Lunii. It works fine except that I can't go back by clicking on the home button to select another pack when I am in my story.  Is this normal or am I missing something ?
Thanks

**Comment by marian-m12l** [comment]
Hi,
Are you using the latest version? I added some documentation regarding the diagram nodes. If you are using a single story node after the cover node, this is indeed a corner case where the HOME button and autoplay behaviour is incorrect. Not a trivial fix, though.

**Comment by DavidZurmely** [comment]
Hi! I'm using the latest version. Actually, I can refine the "problem" : I noticed I can go back using the home button during a simple node, but not during an advanced node unless I define the home button behavior. I guess this is in fact a normal behavior ?

**Comment by marian-m12l** [comment]
Hi,
Not sure how you are configuring your stage nodes? You'd need to enable the home button. An empty home transition should then get back to the "pack-selection" node (that is the behaviour built into the lunii).

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
