### ISSUE TITLE
Feature request: normalize audio

### ISSUE THREAD

**Issue by itdaboyz** [marian-m12l/studio#93]
When transfering to Lunii, it would be great if STUdio could normalize audio to avoid having volume difference between stories.
Thank you!

**Comment by anoril1979** [comment]
Hi!
This is a good idea, but should be managed by an option/setting.
For stories with multiple parts, if audio are normalized one by one, every part may be of different volume power :P

**Comment by marian-m12l** [comment]
Hi,
Thanks for the feedback.
Even though it could be nice to have a few handy tools to prepare the assets, I don't think any of this should be "automagically" done by the app. Maybe in the future, I could add another tab to manage a library of assets, where you can fine-tune your images and audio files, but honestly there may be other priorities.
Regarding the volume difference issue, however, I am no sound engineer but I understand that it is more complex than simply normalizing peak levels. Achieving a consistent _perceived loudness_ seems to imply compressors and limiters, which I'm frankly not familiar enough with to even _use_ on off-the-shelf software like Audacity, let alone implement it on my own software. If someone with a background in audio engineering is willing to lend a hand... :-)

**Comment by itdaboyz** [comment]
I think you have to define a standard, ie a file that play at a decent volume on the Lunii, ideally the same volume than an official story.
After that, all files added to the library can be matched against this standard. This way you avoid the issue pointed by @anoril1979.

Yes, I think it's a huge thing to implement on your own, but maybe you could use something like http://mp3gain.sourceforge.net/ ?

Thank you for the time put in this project :)

**Comment by marian-m12l** [comment]
I actually added a few hints in the in-app documentation (in the latest update). I generally aim for -3dB peak volume and a mean RMS volume between -30dB and -20dB. But as I said, volume normalization and perceived loudness and two different beasts. As you point out, there are ways to "normalize" loudness, like mp3gain or [ReplayGain](https://en.wikipedia.org/wiki/ReplayGain). But maybe then the best workflow is still to use external tools dedicated to audio processing ? Maybe this can even be done in batch with ffmpeg ?
Regarding the issue pointed by @anoril1979 I believe he was actually saying that volume varies during a story, and normalizing the whole story vs normalizing each chunk individually can be wildly different; i.e. some chunks **should** stay at a lower volume.
Thanks for your feedback! :)

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
