### ISSUE TITLE
Cannot save the story pack to library

### ISSUE THREAD

**Issue by Lorenzinaccio** [marian-m12l/studio#94]
**Describe the bug**
Cannot save the story pack to library

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> undefined is not a function (near '...A.getNodes().filter(function(e){return"menu"===e.getType()}).flatMap...')

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.1.14

**Additional context**

**Comment by marian-m12l** [comment]
Hi. Looks like `flatMap` is only supported since Safari 12. Is there a specific reason you're using Safari 11? I don't know much about the macOS ecosystem...
Thanks for the feedback!

**Comment by Lorenzinaccio** [comment]
Thanks a lot, everything works perfectly :)Amazing..Crescendo fxVideo expertLe 11 mai 2020 07:58, marian-m12l <notifications@github.com> a écrit :
Hi. Looks like flatMap is only supported since Safari 12. Is there a specific reason you're using Safari 11? I don't know much about the macOS ecosystem...
Thanks for the feedback!
