### ISSUE TITLE
Add an option to set library (or .studio) folder location [improvement]

### ISSUE THREAD

**Issue by ioExpander** [marian-m12l/studio#96]
Hi. I love this new tool. Thank you.
As a lot of work can go into creating some stories and the library folder can get very big, I think it could be valuable to be able to specify a custom directory to host the library. A simple Java option could do the trick in order to keep the interface simple.
What do you think ?

**Comment by marian-m12l** [comment]
Hi. Well, actually, even though it is undocumented, there _are_ system properties to override some of the paths:

* `studio.library` to override the path to local library folder (defaults to `USER_HOME/.studio/library/`)
* `studio.db.official` to override the path to official metadata json file (defaults to `USER_HOME/.studio/db/official.json`)
* `studio.db.unofficial` to override the path to unofficial metadata json file (defaults to `USER_HOME/.studio/db/unofficial.json`)

Let me know if that works for you. And thanks for the feedback!

**Comment by ioExpander** [comment]
Are those the only elements required to backup and to restore an working version of Studio ? If so it should do the trick for me yes !

**Comment by marian-m12l** [comment]
What do you mean by "to backup and to restore an working version of Studio" ? These properties define where the application looks for the local library (the packs that are stored on your hard drive) and metadata databases (containing the official packs' name, as well as your own packs').

**Comment by ioExpander** [comment]
Sorry I did not express this correctly :  I'm thinking of setting studio's library to be able to share the same data on 2 different laptops (both would not be open at the same time of course) so I'm trying to identify the data that requires to be in the shared folder (for example dropbox). Thank you.

**Comment by marian-m12l** [comment]
If you're syncing with dropbox, is synchronizing `.studio` a problem? The system properties should be enough, though. If you're planning on using a network share, I wouldn't recommend it, as the application is not optimized regarding disk access.

**Comment by ioExpander** [comment]
ah this was my initial thought, but I could not find the option to move the entire .studio folder so I can put it in my dropbox instead of ~/.studio.

**Comment by marian-m12l** [comment]
Hi,
I don't get what you're trying to achieve. IIUC you want the `.studio` folder to be synchronized between 2 machines, using dropbox? Then what keeps you from synchronizing `.studio` in-place?
Otherwise, use the system properties to customize the subfolders.

**Comment by ioExpander** [comment]
I was suggesting to have a startup option to move `.studio` into `~/Dropbox/`.  
But no worries. I'll try with the subfolders and report back later in the week.
Thank you.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
