### ISSUE TITLE
Test and improve homegrown USB driver

### ISSUE THREAD

**Issue by marian-m12l** [marian-m12l/studio#97]
Version [0.2.0-beta.1](https://github.com/marian-m12l/studio/releases/tag/0.2.0-beta.1) is the first version using a **homegrown USB driver**! :tada: 

Before I push this driver into the official release, I'll ask for your feedback. The driver will have to be tested against a variety of devices, especially with different firmware versions, to tackle the remaining corner cases. I you're willing to help, please let me know below.

**DISCLAIMER**
**Be aware that this driver is mostly untested**. Well, actually it was tested against my own device, which has no firmware version (probably an old-ish revision of the device), and it would be great if someone with a more recent revision could test it.
The USB communication is, in theory, very close to what the official driver does, and I would be **very** surprised if it bricked a device : it only writes to the SD card, never to the internal Flash memory which holds the firmware, and the Luniistore does a great job at restoring story packs when a error occurs. However, please acknowledge that there is no such thing as zero risk.

-----

## How to test the new driver

**If you did try this beta version, please comment on this issue, whether you encountered errors or things worked perfectly. If you are running a device with firmware 1.1, I'm even more curious to know how things went!**

**YOU DON'T HAVE TO FOLLOW ALL THESE STEPS if you don't feel like it, any feedback will be greatly appreciated.**

### Just use the application

First and foremost, you can simply **use the application** and see how it behaves regarding the following operations involving the device:
* Get device infos (uuid, firmware version, S/N, total space and free/used space, error code)
* Get the list of story packs
* Extract a story pack to the local library
* Add a story pack from the local library
* Remove a story pack
* Reorder story packs

Does everything work as usual? Are you seeing the same informations about your device?

**Please make sure to unplug and check that everything is OK on the device after each operation involving a change in packs list (any of the last 3 operations), as it is important to check the device is OK with the changes made by the driver.**

If you are comfortable with it, here are the corresponding curl commands:

- `curl -v -X GET http://localhost:8080/api/device/infos`
- `curl -v -X GET http://localhost:8080/api/device/packs`
- `curl -v -X POST -H 'Content-Type: application/json' -d '{"uuid":"12345678-1234-1234-1234-1234567890ab"}' http://localhost:8080/api/device/addToLibrary`
- `curl -v -X POST -H 'Content-Type: application/json' -d '{"uuid":"12345678-1234-1234-1234-1234567890ab","path":"file_name_in_library_folder.pack"}' http://localhost:8080/api/device/addFromLibrary`
- `curl -v -X POST -H 'Content-Type: application/json' -d '{"uuid":"12345678-1234-1234-1234-1234567890ab"}' http://localhost:8080/api/device/removeFromDevice`
- `curl -v -X POST -H 'Content-Type: application/json' -d '{"uuids":["11111111-1111-1111-1111-111111111111","33333333-3333-3333-3333-333333333333","22222222-2222-2222-2222-222222222222"]}' http://localhost:8080/api/device/reorder`

### Gather data

If you are seeing incorrect behaviour, I'd love to get a bit more data. Here is what you can do to collect the good bits.

#### 1) Enable debug logs

**Download and extract** `log4j2-debug.xml` [here](https://github.com/marian-m12l/studio/files/4624552/log4j2-debug.zip) and copy it in the same folder as the studio launch script.

**Edit** the script to add, right after `java` in the last line:
- `-Dlog4j2.configurationFile=$STUDIO_PATH/log4j2-debug.xml` on Linux and macOS
- `-Dlog4j2.configurationFile=%STUDIO_PATH%/log4j2-debug.xml` on Windows

The last line should look like this:
`java -Dlog4j2.configurationFile=$STUDIO_PATH/log4j2-debug.xml -Dvertx.disableDnsResolver=true -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -Dfile.encoding=UTF-8 -cp $STUDIO_PATH/studio-web-ui-0.2.0-beta.1.jar:$STUDIO_PATH/lib/*:. io.vertx.core.Launcher run studio.webui.MainVerticle`

Your `studio-latest.log` will contain much more valuable data.

You can **run the script** again.

#### 2a) Execute problematic operations in the browser

In your browser:
- If you are comfortable with it, look for **errors in the console**, and open the **network tab** to monitor the HTTP calls
- Perform operations involving the device
- If you opened the network tab, look for errors. You can also export the whole traffic to an HAR file.

It will be easier to follow if you can also **explain in a few words what operations you did** during this test.

#### 2b) Execute problematic operations with curl

You can execute the above curl commands if you wish, this will give you clean JSON responses on the console.

#### 3) Dump important sectors from the device

If you are familiar with curl (or a similar tool), you can execute this request to **dump a few relevant sectors from the device** into a local folder of your choice. These sectors contain the device infos, the packs index, and the first, second and last sector of each pack, along with their addresses.

`curl -v -X POST -H 'Content-Type: application/json' -d '{"outputPath":"/absolute/path/to/a/new/folder"}' http://localhost:8080/api/device/dump`

#### 4) Share the data

You can either post the results on this issue, or let me know if you prefer to share privately. The logs, JSON payloads and sector dump **will contain information that you may find sensitive**, such as your device identifiers, the identifier/name of all packs in your device and in your local library. I can open and assign you to a "security advisory", which will only be visible to you and me.

**Comment by nicojlt** [comment]
Hi, what kind of tests do you need ?

**Comment by marian-m12l** [comment]
Hi.
Well, first and foremost, does everything work with your device ? :-)

I'll need to take the time to give more precise instructions on what to test, but there are basically 6 operations that can be performed with the device:
* Get device infos (uuid, firmware version, S/N, total space and free/used space, error code)
* Get the list of story packs
* Extract a story pack to a file
* Add a story pack from a file
* Remove a story pack
* Reorder story packs

If you're comfortable with it, you can monitor the HTTP calls in your browser's "network" tab and in the application's log file.

If you notice some quirks, especially on the device infos, you can also manually call the following endpoint to extract a few relevant sectors from the device into a local folder (these are the sectors containing the device infos, the packs index, and the first, second and last sector of each pack, along with their addresses):

> curl -v -X POST -H 'Content-Type: application/json' -d '{"outputPath":"/absolute/path/to/a/new/folder"}' http://localhost:8080/api/device/dump


Thanks!

**Comment by marian-m12l** [comment]
Updated the issue description to add detailed instructions on how to test the driver.

**Comment by mmaret** [comment]
'curl -v -X POST -H 'Content-Type: application/json' -d '{"uuid":"12345678-1234-1234-1234-1234567890ab","path":"12345678-1234-1234-1234-1234567890ab.pack"}' http://localhost:8080/api/device/addFromLibrary' Put my Lunii in error mode (I may have used another path with a different uuid ?). I could recover the Error mode using the Luniistore.

Otherwise 

```
curl -v -X GET http://localhost:8080/api/device/infos
curl -v -X GET http://localhost:8080/api/device/packs
curl -v -X POST -H 'Content-Type: application/json' -d '{"uuid":"12345678-1234-1234-1234-1234567890ab"}' http://localhost:8080/api/device/addToLibrary
```

where fine 

Linux 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux

**Comment by marian-m12l** [comment]
@mmaret Thanks for giving it a try!

Indeed, if you are using the curl commands, you'll have to replace the uuids with the ones of your story packs.

However for the transfer commands from/to the device, it's probably easier to use the UI. Actually, contrary to what I wrote, these commands won't give you a clear response, as you'll probably get false positive (like you had with the `addToLibrary` command), and fail later on (which should appear in the logs).

**Comment by jfl42** [comment]
Hi,

Thank you so much for your great work. In fact, without knowing your project exists, I would NOT have bought the device.

**Firmware version: 1.2**
Everything seems ok (only tested with UI) :

- Get device infos : uuid, firmware version, S/N, total space and free/used space : OK  (didn't see error code)
- Get the list of story packs : OK
- Extract a story pack to the local library : OK (I removed SimplifiedSamplePack from the library and was able to got it back from the device)
- Add a story pack from the local library : OK (tried with SimplifiedSamplePack)
- Remove a story pack : OK (tried with SimplifiedSamplePack)
- Reorder story packs : OK

I made sure to unplugged and check the result on the device for the last three tests. Everything is fine.

**Comment by marian-m12l** [comment]
Hi @jfl42 

Thanks for the feedback! Good to know everything's fine with a recent firmware! Hadn't seen a firmware 1.2 yet.

Can you confirm that all the device infos give you the same values as the "stable" version? UUID, S/N, available space, etc. all match?

Indeed the error code is not used in STUdio, so it only appears in JSON payloads, and is not critical.

It's good that you tought of checking on the device after each operation, I'll update the main post to stress this as it is important to check the device is OK after each change.

**Comment by athieriot** [comment]
Hello,

Just wanted to say that I just tried the basics with my Lunii: Firmware 1.1.

Uploading a pack onto the Lunii and Deleting one I previously uploaded with a different version of STUdio.

This basic scenario (which is all I'm doing anyway) worked well so far. As well as getting the Firmware info / UUID

Thanks for the work

**Comment by DevUzer** [comment]
Hello, Feedback after few weeks of using that version. No bugs (delete stories, add stories, etc.)... it works like a charm !

**Comment by jfl42** [comment]
Hello,
I can confirm that I got the exact same data from studio-web-ui-0.1.16 and from studio-web-ui-0.2.0-beta.1 : UUID, S/N, Firmware, available space and pack list.
Firmware version is 1.2 (device bought 1 month ago)
For both STUdio versions I got the exact same response for the two GET urls http://localhost:8080/api/device/infos and http://localhost:8080/api/device/packs (saved responses have the same SHA256).

**Comment by marian-m12l** [comment]
Thank you all for the great feedback!
Sounds like it is doing pretty good, I think I'll add an "announce" to let everyone know about this beta version, and if I don't get bad feedback I'll push it as the main release.

**Comment by crazymonster999** [comment]
Hi Marian,

First of all, many thanks for your amazing work !
I installed the 0.2.0-beta.2, build a new story and push it successfully on my lunii box with firmware v1.1.
Integration of the official lunii metadata with the token worked well also.

I was not able to download/export build it stories from official lunii store. I don't know if it's normally an available feature or not.

**Comment by marian-m12l** [comment]
@crazymonster999 Thanks for your feedback! Indeed, extracting official stories is not a feature, but are you able to extract your own story back to the local library?

**Comment by crazymonster999** [comment]
When I reopen the app it loads automatically the storyI built.

However it says the message "No story packs in the library yet". But I have one already, and I can edit it.

![image](https://user-images.githubusercontent.com/1176052/84704497-350a3400-af5a-11ea-935f-0ffb6a696ef2.png)

I'm not able to drag&drop a story from the box to local library (or I didn't understood how to), but I can delete the story, and then upload it again to the box.

**Comment by marian-m12l** [comment]
@crazymonster999 That display is strange, does it still happen ? If so, you can open a separate issue.
If you have a custom story pack in the device, you should be able to drag it and drop it into the "local library", over your existing packs.

**Comment by adebisi187** [comment]
Hello,

I don't have the official library on the left, so i'm not able to transfer my ne story into the lunii (studio-web-ui-0.2.0)
![image](https://user-images.githubusercontent.com/72342472/95015000-e4266480-064a-11eb-8dcb-78bd25df84f4.png)


Best regards

**Comment by MathieuIko** [comment]
I just started to use and test this wonderful application!
An impressive work, and a great tool to get full control on existing and custom stories. May thanks to the developers! :+1: 

**I haven't found how to create a new pack (from scratch)**.
There seems to be no button or link on neither of the two main pages (Pack library or Pack editor).
In case this button/link was just hidden, I checked the DOM, but no "create"-something on neither of the two pages.
Did I miss something?

I will continue testing the app. For now, I successfully:
- mounted my Lunii in STUdio ;
- downloaded the two packs from my Lunii to STUdio (the two packs being the official default pack, with metadata, and a custom story created on the Android app) ;
- open these two packs in the Pack editor, and test/simulate them in STUdio (listen and interact).

I haven't tried yet to add/remove nodes in a pack, nor upload a created/edited pack back to my Lunii.

My environment:
- Lunii v2 with firmware version 2.20
- STUdio 0.3.0-alpha.3-SNAPSHOT (cloned the repo and built few hours ago)
- (X)Ubuntu 20.04.1 (64 bits)
- Mozilla Firefox 84.0.1

**Comment by agademer** [comment]
@m.iko : there is no "create from scratch button" (to my knowledge).

But if you switch to the editor view (icon in the top right of the window)
it will open the sample pack (Marc / Julie) that is meant to be modified to
make new pack.

Hope this help.

**Comment by marian-m12l** [comment]
@MathieuIko Thanks for the feedback. I moved your comment to a new issue (#158) as this one relates to the usb driver.
