### ISSUE TITLE
Temp folder not emptied

### ISSUE THREAD

**Issue by freeKC** [marian-m12l/studio#98]
**Describe the bug**
After the creation of the .pack temporary file into /tmp folder (and after the succeeded transfer on the Lunii device), the file is not deleted.

-rw-r--r-- 1 root root 2,0G mai   13 20:39 /tmp/frigiel_et_fluffy-b336fc47-d928-408c-bc7c-12e112dcf548-v1.zip6548141806078938866.pack

**To Reproduce**
1. drop the pack on the left panel
2. wait the end of the transfer (drink a beer, yep, it's slow :-) )
3. goto step 1 with another pack until my VM free space is full

**Desktop and environment (please complete the following information):**
 - OS: [Linux 64bits]
 - Browser [Firefox]
 - STUdio application version [e.g. 0.1.15]

**Comment by marian-m12l** [comment]
Hi,
Indeed, that would be better :-)
Thanks for noticing.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
