### ISSUE TITLE
http://localhost:8080/ inaccessible 

### ISSUE THREAD

**Issue by Pedrostone** [marian-m12l/studio#99]
Bonjour,
j ai decouvers votre programme et merci beaucoup de le developper.
J ai reussi toutes les etapes, mais lorsque je me connecte au localhost j ai ceci:

**Ce site est inaccessiblelocalhost n'autorise pas la connexion.
Voici quelques conseils :

Vérifier la connexion
Vérifier le proxy et le pare-feu
ERR_CONNECTION_REFUSED**

Je suis sous Windows10, j utilise Chrome, tout est a jour, j ai java14.0.1 et studio 1.15

J ai aussi essaye la commande  **mvn clean install** mais ca ne marche pas:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.049 s
[INFO] Finished at: 2020-05-15T00:19:33-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\marin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Ah aussi, au debut dans studio windows, j ai remplace java par le lien direct de mon program files pour que ca puisse fonctionner, mais depuis que j ai rajouter le path dans l environnement ( j ai rajoute java et mvn) ca fonctionne sans mettre le chemin mais juste en laissant java.

Je precise que je ne sais pas code ni rien du tout, donc peut etre que ca n a rien a voir mais sait on jamais :)

Merci beaucoup.

**Comment by marian-m12l** [comment]
Bonjour,
Avez-vous vérifié les logs dans la ligne de commande ? Quelle URL chargez-vous exactement ? Je n'utilise pas beaucoup Windows, mais est-il possible que le pare-feu bloque les connexions vers localhost ?
Pour ce qui est du build Maven, cela ne vous apportera rien de plus que l'archive déjà disponible sur GitHub.

**Comment by Pedrostone** [comment]
Merci pour votre reponse. (je n ai pas ete notifie de votre reponse)
Cela s affiche quand je vais sur http://localhost:8080/ sur Chrome
Il y a une fois ou cela a marche donc je pense exclure le probleme de pare feu windows.

**Comment by marian-m12l** [comment]
@Pedrostone Avez-vous essayé sur un autre navigateur ? Il y a peut-être un message d'erreur dans les logs ?

**Comment by tibodut** [comment]
@Pedrostone Ne s'agirait-il pas tout simplement du temps de lancement de l'appli serveur (non encore disponible au moment où la page s'ouvre) ?
Est-ce que ça fonctionne si vous rafraichissez la page (CTRL + R) ?
(J'ai ce comportement sur MacOS High Sierra)

**Comment by Pedrostone** [comment]
Bonjour, j avoue avoir lâcher l affaire depuis, j essaierai de m y remettre dedans. EN tout cas merci pour vos retours. Et depuis je vois qu il y a une nouvelle version.

**Comment by yodavador** [comment]
Bonjour à tous, j'ai eu le même problème qui venait au final d'un programme qui était déjà entrain d'écouter le port 8080. 
Pour trouver et tuer le process et rendre accessible le port à STUdio, vous pouvez utiliser le logiciel proposé par windows https://docs.microsoft.com/fr-fr/sysinternals/downloads/tcpview?redirectedfrom=MSDN

**Comment by GuillaumeFege** [comment]
Bonjour à tous,
Le port 8080 étant assez largement utilisé par beaucoup d'outils maintenant, serait il possible de rendre le numéro de port paramétrable ? Ou, si le BIND échoue, de tester 8081, puis 8082, ... ?
Merci.

**Comment by marian-m12l** [comment]
I'm closing issues from past years. Feel free to reopen if needed.
